#+HUGO_SECTION: zettels
#+HUGO_SLUG: today_i_learn
#+TITLE: today-i-learn
#+OPTIONS: ^:nil ~:nil num:nil timestamp:nil
#+roam_tags:


* [[https://github.githistory.xyz/peng051410/today_i_learn/blob/main/README.org][Quick history]]

* [[./english/vocabulary.org][English]]

* [[./english/sentence.org][English Sentence]]

* [[./english/listen.org][English listen]]

* [[./emacs/lisp.md][Lisp]]
* [[./history/china_history.org][History]]

* Command line
** 打印文本第一行
#+begin_src sh
awk 'NR==1{print}' filename
#+end_src
** 获取文本最后一列
主要是$NF
#+begin_src sh
awk -F ',' '{print $NF}'
#+end_src

** Delete all broken soft link
# https://stackoverflow.com/questions/22097130/delete-all-broken-symbolic-links-with-a-line
#+begin_src sh
find -L . -name . -o -type d -prune -o -type l -exec rm {} +
#+end_src

** Rotate a image
#+begin_src sh
function ro() {
    szFile=$1
    convert $1 -rotate 90 $(basename "$szFile").png
}
#+end_src

** Split image
#+begin_src sh
convert -crop 100%x20% in.png output.png
#+end_src
https://dev.to/ko31/using-imagemagick-to-easily-split-an-image-file-13hb

** Nohup to file and console
#+begin_src sh
nohup ./program  > Output.txt | tail -F Output.txt &
#+end_src

** 检验文件或者文件夹是否存在

*** 判断文件是否存在
#+begin_src sh
if [ -e x.txt ]
then
    echo "ok"
else
    echo "nok"
fi
#+end_src

*** 判断文件夹是否存在
#+begin_src sh
if [ -d folder1 ]
then
    echo "ok"
else
    echo "nok"
fi
#+end_src

*** 判断软链接存在并且可用虽
#+begin_src sh
[ -L ${my_link} ] && [ -e ${my_link} ]
#+end_src

*** 判断文件夹不存在
#+begin_src sh

#+end_src

** 获取本机ip
#+begin_src sh
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
# linux only
hostname -i
#+end_src

** Delete file expect few files
#+begin_src sh
rm -v !("filname1"|"file2")
#+end_src

** Sync file from source to target increment
#+begin_src sh
rsync -av Documents/* /tmp/documents
#+end_src

** Scp with port
#+begin_src sh
scp -P 2222 file host@localhost:~/linux-study
#+end_src

** Check url exist

*** Method1
#+begin_src sh
url=http://www.baidu.co
if wget --spider $url 2>/dev/null; then
  echo "File exists"
else
  echo "File does not exist"
fi
#+end_src

*** Method2
#+begin_src sh
url=http://www.baidu.co
if wget -q --method=HEAD $url;
 then
  echo "This page exists."
 else
  echo "This page does not exist."
fi
#+end_src

** Get host ip
#+begin_src sh
curl ipaddy.net
#+end_src

** Generate short link
#+begin_src sh
curl -s 'tinyurl.com/api-create.php?url=http://www.baidu.com'
#+end_src

** Get weather
#+begin_src sh
curl wttr.in
#+end_src

** Pass passphrase to gpg
[[https://unix.stackexchange.com/questions/60213/gpg-asks-for-password-even-with-passphrase][shell script - gpg asks for password even with --passphrase - Unix & Linux Stack Exchange]]
#+begin_src sh
gpg -c --batch --passphrase 1234 -o file.gpg
#+end_src

** Where xhost
[[https://apple.stackexchange.com/questions/378348/xhost-on-macos-catalina][x11 - xhost on MacOS Catalina - Ask Different]]
#+begin_src sh
/opt/X11/bin/xhost
#+end_src

** Display custom date
显示3小时之前的时间
#+begin_src sh
date -d '3 hours ago' +"%Y-%m-%d %T"
# another way
date -d "-3 Hours" "+%Y-%m-%d %T"
#+end_src

** Extract filename and extension from file
https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash?page=1&tab=scoredesc#tab-top
#+begin_src sh
fullfile=~/Downloads/main-webapp_log_Onl_jar_backend.yml
filename=$(basename -- "$fullfile")
extension="${filename##*.}"
filename="${filename%.*}"
echo "filanme is $filename, file extendsion is $extension"
#+end_src

#+RESULTS:
| filanme is main-webapp_log_Onl_jar_backend | file extendsion is yml |

** Truncate file
truncate file only retain 10 line

*** In-place
#+begin_src sh
sed -i.bak '11,$ d' myfile.txt
#+end_src

*** New file
#+begin_src sh
head -n10 myfile.txt > myfile.txt.bak
#+end_src
https://stackoverflow.com/questions/19017994/how-do-i-limit-or-truncate-text-file-by-number-of-lines

** Cut file
#+begin_src sh :exports both :results output code
echo "hello world" | cut -b 2-5
#+end_src

#+RESULTS:
#+begin_src sh
ello
#+end_src

** Quick rename file name
#+begin_src sh
cd /tmp
touch aa.txt
mv aa.{txt,doc}
ls aa.doc
#+end_src

#+RESULTS:
: aa.doc

** Use default value for shell
#+begin_src sh
FOO="${VARIABLE:-default}"  # FOO will be assigned 'default' value if VARIABLE not set or null.
# The value of VARIABLE is kept intouched.

FOO="${VARIABLE:=default}"  # If VARIABLE not set or null, set it's value to 'default'.
# Then that value will be assigned to FOO
#+end_src
*** [[https://stackoverflow.com/questions/2013547/assigning-default-values-to-shell-variables-with-a-single-command-in-bash][Assigning default values to shell variables with a single command in bash - Stack Overflow]]
Captured On: [2023-10-09 Mon 16:50]
** export ls result to txt with absolute path
https://unix.stackexchange.com/questions/268474/how-to-list-all-files-in-a-directory-with-absolute-paths
#+begin_src sh
ls -d "$PWD"/* >> ~/work/repos.txt
#+end_src
** Export proxy app req to curl

*** Charles
url -> 右键 -> Copy cURL Request

*** Fidder
File -> Export -> Selected Sessions -> cURL script

*** Browser
url -> 右键 -> Copy cURL Request

* Maven
** How to get Maven project version from cmd
#+begin_src sh
mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:
#+end_src

** Maven use alternative repo
#+begin_src sh
mvn -DaltDeploymentRepository=repoid::default::http://ip/nexus/content/repositories/releases clean source:jar-no-fork deploy
#+end_src

** Maven download dependency source code
mvn can download all project dependency jar source code by the [[https://maven.apache.org/plugins/maven-dependency-plugin/][maven-dependency-plugin]]
, there are two approach to reach the goal.
*** Run dependency command directly
#+begin_src sh
mvn dependency:sources -Dsilent=true
#+end_src

I prefer this way.
*** Config on pom.xml
#+begin_src xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.5.0</version>
    <executions>
      <execution>
        <id>download-sources</id>
        <goals>
          <goal>sources</goal>
        </goals>
        <configuration>
        </configuration>
      </execution>
    </executions>
  </plugin>
#+end_src

After add the plugin config, run normal mvn command to download source code

*** [[https://stackoverflow.com/questions/11361331/how-to-download-sources-for-a-jar-with-maven][java - How to download sources for a jar with Maven? - Stack Overflow]]
Captured On: [2023-03-16 Thu 16:04]

** Maven get settings file location
#+begin_src sh
mvn -X clean | grep "settings"
#+end_src
*** [[https://www.baeldung.com/maven-settings-xml][The settings.xml File in Maven | Baeldung]]
Captured On: [2023-03-16 Thu 16:35]
** [[https://stackoverflow.com/questions/65910112/maven-clean-install-failed-to-execute-goal-org-apache-maven-pluginsmaven-resou][java - Maven clean install: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:resources - Stack Overflow]]
Captured On: [2023-10-31 Tue 17:41]


add nonFilteredFileExtensions config works for me.
#+begin_src xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.3.0</version>
    <configuration>
        <encoding>UTF-8</encoding>
        <nonFilteredFileExtensions>
            <nonFilteredFileExtension>db</nonFilteredFileExtension>
        </nonFilteredFileExtensions>
    </configuration>
</plugin>

#+end_src
* Emacs
** 给Emacs文档增加目录
给Entry增加标签 =:TOC:=，限定目录层级#+OPTIONS: toc:1
** Add command to keyboard macro
https://www.gnu.org/software/emacs/manual/html_node/emacs/Basic-Keyboard-Macro.html
C-u f3 能执行macro直接到按下f4
** Set major mode on file
https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html
#+begin_src emacs-lisp
;; set major mode, with this, other set will be ignore
; -*-Lisp-*-
#+end_src
** Add minor mode on file
#+begin_src emacs-lisp
; -*- eval: (rainbow-mode) -*-
#+end_src
** Straight use builtin org
将下面的配置加到straight配置前
#+begin_src emacs-lisp
(straight-use-package '(org :type built-in))
#+end_src
** Delete blank line
https://www.masteringemacs.org/article/removing-blank-lines-buffer
#+begin_example
M-x flush-lines RET ^$ RET
#+end_example
** Insert file contents to org source area
In src area, run *C-x i*
#+begin_src sh
grep 'cool thing' ~/Donwnloads
#+end_src
** Add note to blog
1. #+STARTUP: logdrawer
2. 在需要加note的item执行 *C-c C-z*
** Yas add custom style date
[[https://emacs.stackexchange.com/questions/27158/insert-current-date-with-yasnippet][Insert current date with yasnippet - Emacs Stack Exchange]]
#+begin_src emacs-lisp
`(format-time-string "%Y-%m-%d")`$0
#+end_src
** Change org babel export language
[[https://stackoverflow.com/questions/68085596/how-to-change-the-language-of-a-result-of-results-output-code-in-emacs-org-mo][How to change the language of a result of ":results output code" in emacs org-mode - Stack Overflow]]

#+BEGIN_SRC sh :exports results :results output code
pwd
#+END_SRC
** Ignore error info
#+begin_src emacs-lisp
(condition-case nil
    (progn
      (message "hello")
    t)
  (error nil)
#+end_src
** Org add repeated task for weekday
#+begin_src org
,* TODO Study 09:00-10:00
<%%(memq (calendar-day-of-week date) '(1 2 3 4 5))>
#+end_src
** Org babel python output always Nono
[[https://emacs.stackexchange.com/questions/17926/python-org-mode-source-block-output-is-always-none][Python org-mode source block output is always ': None' - Emacs Stack Exchange]]
Can use *return* or add *:results output*
** Org add current time
#+begin_src sh
C-u C-c .
#+end_src
*** [[https://stackoverflow.com/questions/11295973/how-to-insert-current-time-in-the-emacs-org-mode][How to insert current time in the emacs org-mode - Stack Overflow]]
Captured On: [2023-05-24 Wed 10:22]

** Handle swiper search result
Ctrl+s搜索后，再按 *Ctrl+c Ctrl+o* 打开处理结果的buffer
** Change org reveal font color
[[https://emacs.stackexchange.com/questions/38532/change-font-color-on-a-org-reveal-slide][org mode - Change font color on a =org-reveal= slide - Emacs Stack Exchange]]

1. Add header
#+begin_src emacs-lisp
#+MACRO: color @@html:<font color="$1">$2</font>@@
#+end_src

2. Use macro
#+begin_src emacs-lisp
{{{color(red, 基于2019.1版本.)}}}
#+end_src
** So-long mode
When a file very big, [[https://elpa.gnu.org/packages/so-long.html][so-long]] mode can fixed it
** Trim changed line white space
https://github.com/redguardtoo/emacs.d/issues/1014
Emacs has an minor mode called [[https://github.com/lewang/ws-butler][ws-butler-mode]] can trim white space only with changed line.
** Open chrome-extension: prefix url
#+transclude: [[id:BC157E91-6C94-4678-8764-3AEF52CD430B][Chrome browser]] :only-contents
** Copy rectangle area content
It's useful to yank org table cols without additional custom func.
https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/copy-rectangle.gif
** Insert stuff like vi column mode but with string-rectangle
https://twitter.com/i/status/1620721190536114177
** Run region code with command line
I have an request to run curl script with shell, normaly the content is paste from other place, so I think this is any way the emacs can do this, After search emacs doc and
request google, I found the 'shell-commond-on-region'. When I run this command, it works, but another issue occurs that the result only shows in the minibuffer which I can't
do it more like search or copy. Fortunately, the SO user @[[https://emacs.stackexchange.com/users/3889/xuchunyang][xuchunyang]] give me the perfect anwser, an customed 'shell-command-on-region' which output the result after the
request bufer. With this, I can do more imaginable.

*** [[https://emacs.stackexchange.com/questions/55506/run-current-line-or-selection-in-shell-then-insert-result-in-emacs-buffer-acme][key bindings - Run current line or selection in shell then insert result in Emacs buffer (Acme workflow) - Emacs Stack Exchange]]
Captured On: [2023-03-14 Tue 15:03]

** Joint multi lines to one line
Sometimes in develop, we need to convert multi line content to one line, we can realize with Emacs 'join line' command.
#+begin_src xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-core</artifactId>
  <version>5.3.23</version>
  <scope>compile</scope>
</dependency>
#+end_src

https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/emacs-join-lines.gif
** Save all org buffer
Realize with *org-save-all-org-buffers* command
** Org mode search complete task
search previous week done task
#+begin_src sh
TODO="DONE"&CLOSED>="<-1w>"
#+end_src
** Search and replace txt in folder

M-x replace-string RET ; RET C-q C-j.
C-q for quoted-insert,
C-j is a newline.

*** [[https://stackoverflow.com/questions/613022/how-can-i-replace-a-character-with-a-newline-in-emacs][How can I replace a character with a newline in Emacs? - Stack Overflow]]
Captured On: [2023-10-09 Mon 11:02]

** Copy url txt only
With evil
#+begin_example
yi[
#+end_example


** Profile on emacs
1. M-x profiler-start and select cpu from the prompt
2. do the thing that is slow
3. M-x profiler-stop
4. M-x profiler-report
5. Look for the cpu hogs and drill down in to them by hitting TAB on them to find what's slowing down your Emacs.

*** [[https://emacs.stackexchange.com/questions/61463/improve-emacs-performance-when-working-on-large-files][evil - Improve emacs performance when working on large files - Emacs Stack Exchange]]
Captured On: [2023-12-14 Thu 20:08]

** Run jshell with org mode
#+BEGIN_SRC bash :results verbatim
jshell
int a[] = {0,1,3,5,8}
a
a[3] = 42
a
#+END_SRC
https://emacs-china.org/t/emacs-org-mode-jshell/12491/2

** Sort org entries
Use *org-sort* command
支持按字母、数字、优先级、属性、时间等进行排序

https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/K9RHdv.png

** Org list support alphabetical
#+begin_src emacs-lisp
(setq org-list-allow-alphabetical t)
#+end_src
* Org hugo add shortcode
Hugo支持短代码形式在生成html时填充模板内容，shortcode配置的html文件放在 */layouts/shortcodes* 目录下即可，下面的代码就可以实现在博客中嵌入[[https://www.bilibili.com/video/BV1pD4y1K7iw/][B站]]的视频
#+begin_export hugo
{{< bilibili 736118195 >}}
#+end_export

Hugo也支持 *begin_myshortcode* 方式进行嵌入，使用中发现这种形式都是要成对出现的，类似html的闭合标签，目前的使用方式就是 *代码+参数* ，先记住 *export hugo* 方式就可以了
*** [[https://ox-hugo.scripter.co/doc/shortcodes/][Shortcodes — ox-hugo - Org to Hugo exporter]]
Captured On: [2023-01-30 Mon 17:16]

*** [[https://blog.iyu.icu/posts/shortcode_bilibili/][使用Shortcodes在Hugo博客中优雅的嵌入B站视频 – Yu's Blog]]
Captured On: [2023-01-30 Mon 17:10]

** Batch modify file name in emacs
借助库 [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][dired]] 即可实现，参照 [[http://xahlee.info/emacs/emacs/rename_file_pattern.html][李杀]] 的教程

https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/emacs-dired-batch-file.gif
* git

** 查看git配置的来源
在正常工作中会针对不同的工作目录设置不同的配置，可以根据以下命令来确认当前仓库使用的配置来源
#+begin_src sh
git config --show-origin --get user.email
#+end_src

** 删除大于指定大小的仓库信息
迁移仓库时遇到异常，提示镜像文件大于了100M，无法操作，经同事帮助找到此工具，减少仓库信息没得说
#+begin_src sh
bfg --strip-blobs-bigger-than 100M some-big-repo.git
#+end_src

** Rebase user info
#+begin_src sh
git rebase -i "commit id"
# pick to edit then save change
git commit --amend --author="{username} <{email}>" --no-edit
git rebase --continue
git push
#+end_src

** Migrate code to new origin
#+begin_src sh
git clone --mirror <url_of_old_repo>
git remote add new-origin <url_of_new_repo>
git push new-origin --all
#+end_src

** Remove untracked file
#+begin_src sh
git clean -xf
#+end_src

交互式的进行删除
#+begin_src sh
git clean -i
#+end_src

** How to clone git repo wiki
add .wiki after repo

*** clone today_i_learn repo
#+begin_src sh
git clone https://github.com/peng051410/today_i_learn
#+end_src

*** clone today_i_learn repo wiki
#+begin_src sh
git clone https://github.com/peng051410/today_i_learn.wiki
#+end_src

** Create new repo from other existing repo branch
#+begin_src sh
git push new_repo_address +old_repo_branch:master
#+end_src
*** [[https://stackoverflow.com/questions/9527999/how-do-i-create-a-new-github-repo-from-a-branch-in-an-existing-repo][git - How do I create a new GitHub repo from a branch in an existing repo? - Stack Overflow]]
Captured On: [2023-02-23 Thu 14:22]
** Clone single branch
#+begin_src sh
git clone <url> --branch <branch-to-clone> --single-branch [folder-to-store]
#+end_src
https://igorstechnoclub.com/my-everyday-git-commands/
* Github

** Add profile page to github
https://twitter.com/tomylitoo/status/1580396505118441472
Create a repositoy with name same to github name.

** Github emoji shortcode
https://github.com/ikatyang/emoji-cheat-sheet

** Get repo starts
#+begin_src sh
wget https://api.github.com/repos/emacs-eaf/eaf-rss-reader/stargazers
#+end_src

Authenticate requests can do more req.

** Query config file
Search aerospace config files

Search with *path:*aerospace.toml*

https://github.com/search?q=path%3A*aerospace.toml&type=code
* JAVA

** How to judge byte[] is compressed with gzip
#+HEADERS: :classname TestCase
#+begin_src java
private boolean isCompressed(byte[] bytes) {
    if ((bytes == null) || (bytes.length < 2)) {
        return false;
    } else {
        return ((bytes[0] == (byte) (GZIPInputStream.GZIP_MAGIC)) && (bytes[1] == (byte) (GZIPInputStream.GZIP_MAGIC
                >> 8)));
    }
}

#+end_src

** Jenv export java_home
#+begin_src sh
jenv enable-plugin export
#+end_src

** Iterable to list
#+begin_src xml
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-collections4</artifactId>
    <version>4.4</version>
</dependency>
#+end_src
#+begin_src java
IterableUtils.toList(list);
#+end_src

** JVM

*** Show java program jvm params
#+begin_src sh
jcmd 2886 VM.flags
#+end_src

*** Why set -XX:NativeMemoryTracking=detail got ative memory tracking is not enabled
Os security, must execute with root
[[https://stackoverflow.com/questions/42295509/why-jcmd-throws-native-memory-tracking-is-not-enabled-message-even-though-nmt][java - Why JCMD throws "native memory tracking is not enabled" message even though NMT is enabled? - Stack Overflow]]

*** Where is the heap dump file created by jcmd?
Java recommand use jcmd instead of jmap to generate heap file, like:
#+begin_src sh
jcmd 271709 GC.heap_dump Myheapdump.hprof
#+end_src

but, where the generated file?

We can use lsof commd to find the output path
#+begin_src sh
lsof -p pid | grep wd
#+end_src

or genrate with an absolute path
#+begin_src sh
jcmd 271709 GC.heap_dump /data/log/Myheapdump.hprof
#+end_src

https://stackoverflow.com/questions/58519663/where-is-the-heap-dump-file-created-by-jcmd

*** find jvm thread stack size
#+begin_src sh
java -XX:+PrintFlagsFinal -version | grep ThreadStackSize
#+end_src

https://stackoverflow.com/questions/6020619/where-can-i-find-default-xss-stack-size-value-for-oracle-jvm

*** show jvm loaded class
#+begin_src sh
jcmd <jvm_pid> VM.classloaders show-classes
#+end_src

https://stackoverflow.com/questions/16559430/get-a-listing-of-all-currently-loaded-classes-in-a-given-jvm-instance
** Get two date interval days by java8
[[https://stackoverflow.com/questions/27005861/calculate-days-between-two-dates-in-java-8][Calculate days between two Dates in Java 8 - Stack Overflow]]
#+begin_src java
LocalDate today = LocalDate.now()
LocalDate yesterday = today.minusDays(1);
Duration.between(today.atStartOfDay(), yesterday.atStartOfDay()).toDays() // another option
#+end_src

** Convert Milliseconds to LocalDateTime
#+begin_src java
long millis = 1614926594000L; // UTC Fri Mar 05 2021 06:43:14
LocalDate dateTime = Instant.ofEpochMilli(millis)
        .atZone(ZoneId.systemDefault()) // default zone
        .toLocalDate(); // returns actual LocalDate object
#+end_src

** Convert LocalDate to Milliseconds
#+begin_src java
ocalDate dateTime1 = LocalDate.of(2021, 3, 5);
long seconds = dateTime1.atStartOfDay(ZoneId.systemDefault())
        .toEpochSecond(); // returns seconds
long millis1 = seconds * 1000; // seconds to milliseconds
#+end_src

** com.google.protobuf.GeneratedMessageV3.isStringEmpty not found
need import protobuf-java dependency
#+begin_src xml
<dependency>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protobuf-java</artifactId>
  <version>3.19.1</version>
</dependency>
#+end_src

** Get returntype by aspectj joinpoint
#+begin_src java
Method method = ((MethodSignature) proceedingJoinPoint.getSignature()).getMethod();
Class<?> returnType = method.getReturnType();

//or
Class<?> returnType1 = ((MethodSignature) proceedingJoinPoint.getSignature()).getReturnType();
#+end_src

** SpringFlux+Netty config access log

*** add netty system param
#+begin_src sh
-Dreactor.netty.http.server.accessLogEnabled=true
#+end_src

*** config log4j for access log
#+begin_src xml
<RollingFile name="RollingFileAccess"
             fileName="${sys:logPath}/access.log"
             filePattern="${sys:logPath}/access.log.%d{yyyy-MM-dd_HH}.gz">
  <ThresholdFilter level="INFO"/>
  <PatternLayout>
    <pattern>%d{HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n</pattern>
  </PatternLayout>
  <Policies>
    <TimeBasedTriggeringPolicy/>
  </Policies>
</RollingFile>

<Logger name="reactor.netty.http.server.AccessLog" level="info" additivity="false">
  <AppenderRef ref="RollingFileAccess"/>
</Logger>

#+end_src

** Difference between Class.this and this in java
Class.this used in nested class to resolved ambiguous
*** [[https://www.geeksforgeeks.org/difference-between-class-this-and-this-in-java/][Difference Between Class.this and this in Java - GeeksforGeeks]]
Captured On: [2023-11-17 Fri 16:17]
** JDK base module not found
Need add vm options to IDEA
#+begin_src sh
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
#+end_src
*** [[https://stackoverflow.com/questions/74006627/module-java-base-does-not-opens-java-lang-java-17-0-4-1][Module java.base does not "opens java.lang" (Java 17.0.4.1) - Stack Overflow]]
Captured On: [2023-12-28 Thu 16:44]
** Change java.util.logging log level
https://stackoverflow.com/questions/6307648/change-global-setting-for-logger-instances

#+begin_src sh
-Djava.util.logging.config.file="logging.properties"
#+end_src
*** logging.properties
#+begin_src sh
.level = INFO #global
com.xyz.foo.level = SEVERE
#+end_src


* Spring

** How to get handleMethod from webflux
1. inject handleMapping
2. you got it!
#+HEADERS: :classname Solution
#+begin_src java
(HandlerMethod) this.handlerMapping.getHandler(serverWebExchange).toProcessor().peek();
#+end_src

** Spring profie effect scope
Profiles affect only bean creation, not method.


** [[https://stackoverflow.com/questions/49367006/spring-value-with-arraylist-split-and-default-empty-list][java - Spring @Value with arraylist split and default empty list - Stack Overflow]]
Captured On: [2023-11-29 Wed 17:43]
I want to transfer a value from config to list, and need to set default value, I don't like two write value keys twice, like this:
#+HEADERS: :classname SpringValue
#+begin_src java
@Value("#{'${my.list}'.split(',') : T(java.util.Collections).emptyList()}")
#+end_src

Fortunately, I found a beautiful solution to face it. Thanks SO.

#+HEADERS: :classname SpringBeautifulValue
#+begin_src java
@Value("#{T(java.util.Arrays).asList('${my.list:}')}")
private List<String> list;
#+end_src

* KM

** How to show km error log
#+begin_src sh
tail -f ~/Library/Logs/Keyboard\ Maestro/Engine.log
#+end_src

* Python

** python with git
#+begin_src sh
pip3 install GitPython
#+end_src

** python with clipboard
#+begin_src sh
pip3 install pyperclip
#+end_src

** python urldecode
#+begin_src python
from urllib.parse import unquote
url = unquote(url)
#+end_src

** python with cross-platform home directory
[[https://stackoverflow.com/questions/4028904/what-is-a-cross-platform-way-to-get-the-home-directory][python - What is a cross-platform way to get the home directory? - Stack Overflow]]
#+begin_src python :results output
from pathlib import Path
home = str(Path.home())
print(home)
#+end_src

** python set to string
#+begin_src python :results output
s = {'a', 'b'}
str = ', '.join(s)
print(str)
#+end_src

** python decimal to binary
https://stackoverflow.com/questions/3528146/convert-decimal-to-binary-in-python

#+begin_src python :results output
abinary = bin(1024)
print(abinary)
#+end_src

** [[https://blog.heyfe.org/blog/2022-mac-12-3-python-not-found.html][关于 Mac 12.3 出现 python not found 的解决方法 | HeyFE]]
Captured On: [2023-12-05 Tue 19:04]

1. 安装pyenv
2. set python globel
3. 修改alfred命令的python路径

我的alfred插件又可以用了

#+begin_src sh
pyenv install 2.7.18
pyenv global 2.7.18
#+end_src
* Brew

** get installed program path

#+begin_src sh
(brew --prefix go)
#+end_src

** handle rebase-apply error
#+begin_src sh
brew update-reset
#+end_src

** Make brew python and pyenv togehter
# https://stackoverflow.com/questions/30499795/how-can-i-make-homebrews-python-and-pyenv-live-together
#+begin_src sh
ln -s $(brew --cellar python)/* ~/.pyenv/versions/
#+end_src

** fixed font exists in multiple taps
[[https://github.com/Homebrew/homebrew-cask/issues/59227][How can I fix Error: font exists in multiple taps ? · Issue #59227 · Homebrew/homebrew-cask]]
#+begin_src sh
brew untap caskroom/fonts
brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font
#+end_src

** Clean brew cache
#+begin_src sh
brew cleanup -s
#+end_src
** Cask adoptopenjdk8 exists in multiple taps
Del homebrew cask rb

#+begin_src sh
rm /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/adoptopenjdk8.rb
#+end_src

https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106#issuecomment-487269671
** Brew install with .rb file
#+begin_src sh
brew install qemu-virgl.rb
#+end_src
** Brew tap modify
#+begin_src sh
brew tap knazarov/qemu-virgl
brew edit qemu-virgl
#+end_src
* MAC

** del macOS Xcode CoreSimulator folder
#+begin_src sh
xcrun simctl delete unavailable
#+end_src

** Brew mysql install connect issue
因为有老的mysql数据没有清理完全，执行完以下操作后，重新安装即可
#+begin_src sh
sudo rm -rf /usr/local/var/mysql
#+end_src

** Mount/unmount smbs
#+begin_src sh
sudo mount -t smbfs '//vagrant:vagrant@localhost:10139/kernel-source' /Volumes
unmont kernel-source
#+end_src

** Get running app
#+begin_src sh
osascript -e 'tell application "System Events" to get name of (processes where background only is false)'
#+end_src

** Reset macos accessibility
#+begin_src sh
sudo tccutil reset Accessibility
#+end_src

** Find app url schema
1. go to /Application folder
2. find target app
3. show package contents
4. oppen info.plist
5. search CFBundleURLSchemes

https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/Peza8y.png

** Mac dictionary file path
/System/Library/AssetsV2/com_apple_MobileAsset_DictionaryServices_dictionaryOSX

** Find ios app data path
#+begin_src sh
open ~/Library/Containers/appNames
#+end_src

** Show lunar day in Calendar app
https://cdn.jsdelivr.net/gh/peng051410/bucket@main/img/JL7jS1.png

** Add debug info to app
Add *-_NS_4445425547 YES* param to app
* Linux

** Change default program
#+begin_src sh
update-alternatives --set java java-11-openjdk.x86_64
#+end_src
You can issue java path by
#+begin_src sh
update-alternatives --config java
#+end_src

** SSH passwordless with public key authentication

*** Generate key from host
#+begin_src sh
ssh-keygen -t rsa
#+end_src

*** Scp to dest machine
#+begin_src sh
scp .ssh/id_rsa.pub user@host:.
#+end_src

*** Add pub key to dest machine auth key
#+begin_src sh
cat id_rsa.pub >> .ssh/authorized_keys
#+end_src

** Man with color
[[https://gist.github.com/supermarin/6dca255da372c3f9eb26][Colored `man` pages on OSX]]
#+begin_src sh
man() {
	env \
		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
		LESS_TERMCAP_md=$(printf "\e[1;31m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
		man "$@"
}
#+end_src

** Config linux ssh with rsa login
*** [[https://www.runoob.com/w3cnote/set-ssh-login-key.html][设置 SSH 通过密钥登录 | 菜鸟教程]]
Captured On: [2023-10-24 Tue 10:33]
** Show glibc version
#+begin_src sh
ls -l /lib/libc.so.*
#+end_src
* Mysql

** Show db table create/update time
#+begin_src sql
select table_name, create_time, update_time
from information_schema.TABLES
where information_schema.TABLES.TABLE_SCHEMA = 'yw_cooperate_oppo' and information_schema.TABLES.TABLE_NAME = 'book_mrg';
show table status like 'book_mrg';
#+end_src

** Query db size
data size with M.
#+begin_src sql
select table_schema as database_name,
       table_name,
       round(1.0*data_length/1024/1024, 2) as data_size,
       round(index_length/1024/1024, 2) as index_size,
       round((data_length + index_length)/1024/1024, 2) as total_size
from information_schema.tables
where table_schema not in('information_schema', 'mysql',
                          'sys', 'performance_schema')
      -- and table_schema = 'your database name'
order by total_size desc;
#+end_src
https://dataedo.com/kb/query/mysql/list-of-tables-by-the-size-of-data-and-indexes

** Partition table
#+begin_src sh
alter table `ugc_ent` PARTITION BY RANGE (TO_DAYS(create_time)) (
  PARTITION p20240210 VALUES LESS THAN (TO_DAYS('2024-02-10')) ENGINE = InnoDB
)
#+end_src

*** [[https://stackoverflow.com/questions/11859481/how-to-make-partitioning-in-existing-mysql-table][database - How to make partitioning in existing mysql table? - Stack Overflow]]
Captured On: [2024-01-08 Mon 16:41]


** Change primary key
#+begin_src sql
alter table `ugc_comment` drop primary key, add primary key(`comment_id`,`create_time`);
#+end_src
*** [[https://stackoverflow.com/questions/2341576/updating-mysql-primary-key][Updating MySQL primary key - Stack Overflow]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

* IDEA

** Use alt key quickly on commit window
Alt+i not work, need to use Alt+Ctrl+i

** Rm unused code
#+begin_notes
Just use Analyze | Inspect Code with appropriate inspection enabled (Unused declaration under Declaration redundancy group).
#+end_notes
* Convert vvt to srt
#+begin_src sh
ffmpeg -i in.vvt out.srt
#+end_src

* Save video part stuff
截取视频的特定时间的内容
#+transclude: [[id:EDE33AD7-AA31-4C77-850E-4BA357F3F073][Split video]] :only-contents

* JACKSON

** JsonNode to class
#+begin_src java
MyClass newJsonNode = jsonObjectMapper.treeToValue(someJsonNode, MyClass.class);
#+end_src

** Json to Map
#+begin_src java
String jsonInput = "{\"key\": \"value\"}";
TypeReference<HashMap<String, String>> typeRef
  = new TypeReference<HashMap<String, String>>() {};
Map<String, String> map = mapper.readValue(jsonInput, typeRef);
#+end_src

** Unwarp map
[[https://stackoverflow.com/questions/57312679/jackson-hashmap-ignore-map-name-when-writing-to-string][java - Jackson HashMap, ignore map name when writing to String - Stack Overflow]]
#+begin_src java
private Map<String, TaskStatusDTO> taskMap;

@JsonAnySetter
public void setTaskMap(String key, TaskStatusDTO value) {
    this.taskMap.put(key, value);
}

@JsonAnyGetter
public Map<String, TaskStatusDTO> getTaskMap() {
    return taskMap;
}
#+end_src

* Redis

** Batch del key
#+begin_src sh
redis-cli keys "*match" | xargs redis-cli del
#+end_src

** Find big key
#+begin_src sh
redis-cli --bigkeys
#+end_src

** Set pass
#+begin_src sh
config set requirepass p@ss$12E45
#+end_src

This will be invalid when redis server restart, for permanently valid set in redis.conf
* Nginx

** underscore header issue
Must set *underscores_in_headers* to tell nginx not drop it.
#+begin_src sh
underscores_in_headers on
#+end_src
[[https://stackoverflow.com/questions/22856136/why-do-http-servers-forbid-underscores-in-http-header-names][apache - Why do HTTP servers forbid underscores in HTTP header names - Stack Overflow]]

* Wexin develop
** [[https://blog.csdn.net/medivhq/article/details/49659971][微信模板消息换行 - Jinx - CSDN博客]]
** [[https://blog.csdn.net/X_hazel/article/details/85206241][微信公众号开发者模式回复信息带表情（QQ，emoji） - X_hazel的博客 - CSDN博客]]
* JS
** Get table td content
:PROPERTIES:
:ID:       15B61F24-749B-41D7-81DD-FF18552D66A2
:END:
#+begin_src js
var table = document.getElementById("mytable");
var rows = table.rows;//获取所有行
console.log("lenth",rows.length) //
for(var i=1; i < rows.length; i++){
  var row = rows[i];//获取每一行
  var id = row.cells[1].innerHTML;//获取具体单元格
  console.log(id)
}
#+end_src
* VIM
** indent code
= indicate indent
#+begin_src sh
gg
=G
#+end_src

*** [[https://unix.stackexchange.com/questions/19945/auto-indent-format-code-for-vim][Auto indent / format code for Vim? - Unix & Linux Stack Exchange]]
Captured On: [2023-05-18 Thu 19:22]
* GCC
** Compile c program to assembly language

#+begin_src sh
gcc -S helloworld.c
#+end_src
After run this command, a new file named helloworld.s prevent.

* NPM
** sh: react-scripts: command not found after running npm start
Project need install dependency package
#+begin_src sh
npm install
#+end_src
*** [[https://stackoverflow.com/questions/40546231/sh-react-scripts-command-not-found-after-running-npm-start][reactjs - sh: react-scripts: command not found after running npm start - Stack Overflow]]
Captured On: [2023-06-09 Fri 14:06]
* GO
** Go compile to assembly language
#+begin_src sh
go build -gcflags=-S main.go
#+end_src

https://github.com/golang/go/issues/58629

https://colobu.com/2018/12/29/get-assembly-output-for-go-programs/
* VSCode
** Setting go for workspace
https://townsyio.medium.com/how-to-configure-your-go-modules-proxy-in-vscode-fa41f29192fe

1. run "open setting workspace (json)" command in VSCode
2. add config
#+begin_src js
{
    "go.toolsEnvVars": {
        "GOPRIVATE": "townsy.private-github.com",
        "GOPROXY": "https://athens-proxy.townsy.io",
        "GONOPROXY": "none;",
        "GONOSUMDB": "townsy.private-github.com"
    },
    "terminal.integrated.env.linux": {
        "GOPRIVATE": "townsy.private-github.com",
        "GOPROXY": "https://athens-proxy.townsy.io",
        "GONOPROXY": "none;",
        "GONOSUMDB": "townsy.private-github.com"
    }
}

#+end_src
* Pandoc
** convert md to docx
#+begin_src sh
pandoc -o output.docx -f markdown -t docx filename.md
#+end_src
* Xcode
** [[https://github.com/nodejs/node-gyp/issues/569][xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance · Issue #569 · nodejs/node-gyp]]
Captured On: [2023-10-30 Mon 20:12]

#+begin_src sh
xcode-select --install # Install Command Line Tools if you haven't already.
sudo xcode-select --switch /Library/Developer/CommandLineTools # Enable command line tools
# Change the path if you installed Xcode somewhere else.
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
#+end_src
* Chrome
** [[https://support.google.com/chrome/thread/162555856/why-does-chrome-display-your-connection-to-this-site-is-not-secure-if-content-is-empty?hl=en][Why does Chrome display "Your connection to this site is not secure" if content is empty? - Google Chrome Community]]
Captured On: [2023-10-31 Tue 11:48]
** Close QUIC
1. chrome://flags/#enable-quic
2. Experimental QUIC protocol to *Disabled*
* Firfox
** Get current tabe url from terminal
#+begin_src sh
osascript -e  'tell application "System Events" to get value of UI element 1 of combo box 1 of toolbar "Navigation" of first group of front window of application process "Firefox"'
#+end_src

https://apple.stackexchange.com/questions/404841/get-url-of-opened-firefox-tabs-from-terminal

* Anki
** [[https://stackoverflow.com/questions/42206812/how-do-you-embed-a-youtube-video-into-an-anki-card][pyqt - How do you embed a YouTube video into an Anki Card - Stack Overflow]]
Captured On: [2023-11-22 Wed 11:20]
#+begin_src html
<iframe width="560" height="315" src="https://www.youtube.com/embed/dmcfsEEogxs?start=30" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_src
* Arthas
** Modify java file and reload
#+begin_src sh
jad --source-only com.example.demo.arthas.user.UserController > /tmp/UserController.java

mc /tmp/UserController.java -d /tmp

retransform /tmp/com/example/demo/arthas/user/UserController.class
#+end_src

*** [[https://arthas.aliyun.com/doc/retransform.html#%E7%BB%93%E5%90%88-jad-mc-%E5%91%BD%E4%BB%A4%E4%BD%BF%E7%94%A8][retransform | arthas]]
Captured On: [2023-12-12 Tue 17:22]

* Twitter

** Search user hot tweets
from:baibanbaonet min_faves:10

* Logseq

** Install local plugin
Place unpacked plugin folder under *~/.logseq/plugins* ,then restart logseq

* MAT

** Install mat on mac arch m2
版本：Eclipse Memory Analyzer Version 1.15.0，需要JDK17以上版本

打开访达 -> 应用程序 -> 找到mat【右键点击 “显示包内容”】 -> 找到info.plist文件，在其dict节点内，追加下列环境变量：

#+begin_src sh
<string>-vm</string>
<string>/Users/tomyli/.sdkman/candidates/java/17.0.9-jbr/bin</string>
#+end_src

* System

** Use vcpkg in clion
In clion setting -> CMake options, Add
#+begin_src sh
-DCMAKE_TOOLCHAIN_FILE=[vcpkg root]/scripts/buildsystems/vcpkg.cmake
#+end_src

https://www.cnblogs.com/lancediarmuid/p/17333985.html

** Make file rule
prerequisites中如果有一个以上的文件比target文件要新的话，command所定义的命令就会被执行。这就是Makefile的规则

https://blog.csdn.net/haoel/article/details/2886

* Clion

** Disable clang errors to fixed unknown typename
Go to: Languages & Frameworks -> Clangd
Disabled "Show errors and warnings from clangd"

http://pic.imcompany.cn/pic/c6DWuA.png

http://pic.imcompany.cn/pic/c6DWuA.png

* C

** Use compat memory allocate
#+begin_src C
struct __attribute__ ((__packed__)) sdshdr8 {};
#+end_src
