#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil

* [[https://www.youtube.com/watch?v=DFZRg8z_AJg][(10) 读懂英语新闻（第186期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Judges rejected TikTok's effort to avoid a U.S. ban
TikTok, a video app used by more than 170 million Americans,
moved one step closer today to disappearing from the U.S. market. A
panel of federal judges unanimously upheld a new law that requires
the app's Chinese owner to either sell TikTok to a non-Chinese owner
by mid-January or face a nationwide ban in the U.S. While Donald
Trump has promised to save the app, the law is set to go into effect
the day before his inauguration and it's unclear how he could evade
an act of Congress and whether he wants to risk much political
capital on this given his hawkish stance on China.
*** upheld
*** inauguration
*** evade
** Two
2. N.Y.P.D. said the shooting suspect may have left the city
New York's police commissioner said today that the man who
fatally shot a health insurance executive in Midtown
Manhattan might have left the city. The authorities said they
have video of the man taking a cab to an interstate bus station
in Upper Manhattan and entering it on the day of the attack,
but never exiting. So far, there have been no arrests and the
authorities have not established a motive.
*** NYPD
:LOGBOOK:
- Note taken on [2024-12-11 Wed 09:51] \\
  纽约市警察局（NYPD）是美国最大的市警局，下设多个部门，负责维护纽约市治安。
:END:
https://en.wikipedia.org/w/index.php?title=New_York_City_Police_Department&useskin=vector
*** Manhattan
https://en.wikipedia.org/wiki/Manhattan?useskin=vector
*** interstate
