#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil
#+FILETAGS: ANKI
#+STARTUP: indent
#+ANKI_DECK: English

* [[./news-100-200.org][news-100-200]]
* [[./news-200-300.org][news-200-300]]

* [[https://www.youtube.com/watch?v=_kyKBD2NEdQ][(51) 读懂英语新闻（第301期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Trump threatens to use brute force to lower prices
With many Americans frustrated over the high cost of living, the president has embraced a strategy of brute force. He has pressured the Federal Reserve in an effort to make mortgages more attractive, demanded credit card companies lower their fees and lashed out at businesses over high costs, among other threats. Consumer prices were 2.7 percent higher than a year ago, according to the latest data, and food prices climbed sharply last month.

*** brute force
https://www.bing.com/dict/search?q=brute%20force

*** lash out
https://www.bing.com/dict/search?q=lash+out&lq=0&pq=

** Two
2. Donald Trump urged protesters in Iran to "TAKE OVER" state institutions, saying that "HELP IS ON ITS WAY" as nationwide protests continued. He said all meetings with Iranian representatives would be cancelled until the killings stopped. An Iranian official estimated that around 2,000 people have died since the demonstrations erupted in late December, according to Reuters, a news agency.

*** Reuters
https://en.wikipedia.org/wiki/Reuters?useskin=vector

** Three
3. Prosecutors resign over Justice Dept.'s response to ICE shooting
Six federal prosecutors in Minnesota resigned today over the Trump administration's push to investigate the widow of the woman an ICE agent killed last week in Minneapolis. They also objected to the Justice Department's reluctance to investigate the shooter.

*** prosecutor
https://www.dicts.cn/dictword20181/html/31c70222fa13dbc17000c6c324ddd220.html?prosecutor

* [[https://www.youtube.com/watch?v=g2rP3Bw5LFw][(51) 一周听力合集（第300期+第301期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第301期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** fist
https://www.dicts.cn/dictword20181/html/d3818eae2938c4a0400daba891818f78.html?fist

* [[https://www.bilibili.com/video/BV15GkaBXEpt][读懂英语新闻（第302期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** One
1. What's the best activity for longevity?
Research has repeatedly shown that regular exercise is one of the most effective ways to lengthen your life. Even just a few minutes a day has real benefits. However, some activities seem to come with extra benefits. In particular, tennis has been linked with longevity. One study found that tennis players lived almost 10 years longer than their sedentary peers — and longer than soccer players, cyclists and swimmers. That may be because tennis is a full-body workout that often involves socializing and can be played later in life.

*** longevity
https://www.dicts.cn/dictword20181/html/e291106ed285bcc652fe84de0e883fe1.html?longevity

** Two
2. Venezuelan opposition leader María Corina Machado said she "presented" President Trump with her Nobel Peace Prize during an Oval Office meeting yesterday. Trump, who has publicly campaigned for the prize, wrote on Truth Social: "María presented me with her Nobel Peace Prize for the work I have done. Such a wonderful gesture of mutual respect."

*** mutual
https://www.dicts.cn/dictword20181/html/fc64263140871358a7e9c55f8bc57904.html?mutual

** Three
3. Donald Trump announced that he would impose escalating tarifis on Denmark and other European countries, including Britain, France and Germany, that fail to support his bid to purchase Greenland. Writing on his Truth Social platform, he threatened a 10% levy on all goods starting on February 1st, increasing to 25% on June 1st. His threats followed mass protests in Denmark and Greenland in response to America's push to acquire the Arctic territory.

*** Arctic
https://en.wikipedia.org/wiki/Arctic?useskin=vector
* [[https://www.youtube.com/watch?v=9uxZlZ7C6Xg][(57) 看美剧练听力（第302期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第302期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** dormant
https://www.dicts.cn/dictword20181/html/0a37fb433c659bba5ec0e5b130b62b23.html?dormant
* [[https://www.youtube.com/watch?v=0_78c8bBzBE][(59) 读懂英语新闻（第303期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Canadian Prime Minister Mark Carney used a major address in Davos to urge world leaders to see the reality of a world that's increasingly governed by superpower aggression. Recent events have shown the "rules-based international order" is effectively dead, Carney said, which means Canada and other countries have no choice but to create new alliances to oppose pressure tactics and intimidation.
   
*** Davos
https://en.wikipedia.org/wiki/Davos?useskin=vector
*** effective
https://www.dicts.cn/dictword20181/html/25926b7d34dd0f019fe250777f933563.html?effective
*** tactic
https://www.dicts.cn/dictword20181/html/d58d0ac1436d0103df3c7ce6d139e6fe.html?tactic
** Two
2. Fewer people are jumping off the Golden Gate Bridge
The Golden Gate Bridge, the iconic span that hangs between San Francisco Bay and the Pacific Ocean, has been the site of more than 2,000 confirmed suicide leaps since it opened in 1937. For decades, the death toll hovered around 30 a year. But now, after the completion of a $224 million project to install stainless-steel nets below the bridge, the number of suicides has noticeably dropped. There were none in the second half of 2025.

*** jump off
https://www.bing.com/dict/search?q=jump%20off
*** Golden Gate Bridge
https://en.wikipedia.org/wiki/Golden_Gate_Bridge?useskin=vector
*** stainless-steel
https://en.wikipedia.org/w/index.php?title=Stainless_steel&useskin=vector
** Three
3. After deadly train crash, investigators focus on the track
Spanish authorities struggled today to identify those killed in Sunday's high-speed train collision, which left at least 41 people dead. Investigators there are focusing on whether a track problem may have caused the incident, and a train undercarriage found in a stream may be a clue.

*** [#A] track
https://www.dicts.cn/dictword20181/html/9577da8e56547833c5c7982a66c0df80.html?track
*** stream
https://www.dicts.cn/dictword20181/html/fdd35a283c3c1e300ca192e9fdea4e7f.html?stream
* [[https://www.youtube.com/watch?v=pW-ibJl2-UE][(62) 一周听力合集（第302期+第303期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第303期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** distress
https://www.dicts.cn/dictword20181/html/6f6f163ece0ac37fbb9a126643802080.html?distress
** pour
https://www.dicts.cn/dictword20181/html/e9795bd9cfc73ee676039a1eb1b35437.html?pour