#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil
#+FILETAGS: ANKI
#+STARTUP: indent
#+ANKI_DECK: English

* [[./news-100-200.org][news-100-200]]
* [[./news-200-300.org][news-200-300]]
* [[./news-301-350.org][news-301-350]]

* [[https://www.youtube.com/watch?v=B91Dgb8fJKI][(11) Understanding English News (Episode 351) | Learn English Through News | Rapid Vocabulary Expansio... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-15 Wed 09:35]
:END:

** One
1. Team USA's run in the World Cup came to an end, losing 4-1 to Belgium who will face Spain in the next round. FIFA's reversal of US striker Folarin Balogun's one-game ban hung over the game, after soccer's global governing body denied a Belgian appeal of the decision. Earlier, Spain beat Portugal 1-0 bringing soccer legend Cristiano Ronaldo's World Cup career to an end.

*** reversal
https://www.dicts.cn/dictword20181/html/fd0dd7eb88e1fb95ea5b44306eb1a988.html?reversal

*** hang over
https://www.bing.com/dict/search?q=hang%20over

** Two
2. In a new national survey, a record 11 percent of Americans said they were currently taking a weight-loss drug. That's a huge jump from the 3 percent who reported taking one in 2024, a sign that lower prices and positive results have elevated the drugs. Poll data also showed that the percentage of Americans who are obese is falling, from 39.9 percent in 2022 to 36.4 this year. And rates of diabetes diagnoses are now steady, after climbing for over a decade.

*** elevate
https://www.dicts.cn/dictword20181/html/457f086780511024a57b2901803bea62.html?elevate

*** diabetes
https://www.dicts.cn/dictword20181/html/813fb138f0dc6be88389da55c57872e6.html?diabetes

** Three
3. What turns a scent into a sensation?
Bath & Body Works hit the jackpot when it released Japanese Cherry Blossom in 2006. The fragrance, which smells of pear and basmati rice, has alone generated $1.5 billion in sales, making it the company's top-selling scent. Now, as revenues have slipped, Bath & Body Works is spending millions of dollars in search of its next hit.

*** scent
https://www.dicts.cn/dictword20181/html/d233f6232f0c67507f46fefc77467bee.html?scent

*** sensation
https://www.dicts.cn/dictword20181/html/1130ccbb838b1ee11961885c6e0ffad2.html?sensation

*** Bash & Body Works
https://en.wikipedia.org/wiki/Bath_%26_Body_Works?useskin=vector

*** hit the jackpot
https://www.bing.com/dict/search?q=hit%20the%20jackpot

*** fragrance
https://www.dicts.cn/dictword20181/html/23aa5f1c5af83f132c450d9021acb019.html?fragrance

* [[https://www.youtube.com/watch?v=HmNmOg9oo0w][(11) Weekly Listening Compilation (Issues 350 + 351) | Intensive Vocabulary Listening | Authentic Amer... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-16 Thu 09:32]
:END:

** spike
https://www.dicts.cn/dictword20181/html/688821703214b40d69cee9db5b5d524f.html?spike

* [[https://www.youtube.com/watch?v=SZwSHSsUHa4][(12) Understanding English News (Ep. 352) | Learn English Through News | Rapid Vocabulary Expansion | ... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-17 Fri 09:21]
:END:

** One
1. Getting driverless cars to obey traffic laws is a big headache for police.
State and local governments, as well as federal regulators, are playing catch-up as autonomous vehicles spread across the country. Law-enforcement agencies have largely been on their own in figuring out how to ticket and even punish-robotaxis that break traffic rules or get involved in crashes.

*** play catch-up
https://www.bing.com/dict/search?q=play%20catch-up

** Two
2. Chronically high living costs are helping reshape the milestones of early adulthood in America. Last year, 49% of adults under age 30 said they lived with a parent, up 12 percentage points from 2019. Living at home is now often viewed as a sign of financial prudence, and for some, a long-term prospect. But it can be an adjustment for both generations.

*** chronic
https://www.dicts.cn/dictword20181/html/90744c0320bcf68b6aced3dd9d09e5ff.html?chronic

*** prudence
https://www.dicts.cn/dictword20181/html/854fc265cd6bf3594f47ec8edb3477ae.html?prudence

*** [#A] prospect
https://www.dicts.cn/dictword20181/html/0fbac5beba7e12190b1c0307664cdbcd.html?prospect

** Three
3, China's space program launched a rocket today and then, six minutes later, caught the bottom part with a sea platform fitted with nets. The demonstration suggested that the Chinese engineers were getting closer to a partly reusable rocket - the technology that allowed SpaceX, Elon Musk's American rocket maker, to dominate the satellite industry for years. As of now, SpaceX has more than 10,000 satellites in orbit, compared with just over 400 combined from two of its Chinese rivals.

*** as of now
https://www.bing.com/dict/search?q=as%20of%20now

* [[https://www.youtube.com/watch?v=JFWOPMd5aJE][(4) Improve Your English Listening with US TV Series (Ep. 352) | Intensive Vocabulary Listening | Aut... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-21 Tue 09:33]
:END:
        
** tribe
https://www.dicts.cn/dictword20181/html/d0dc7c1dab3ed14b9b9a8f594a9d4828.html?tribe

* [[https://www.youtube.com/watch?v=Yy4t2vVT0hY][(7) 读懂英语新闻（第353期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-23 Thu 09:41]
:END:

** One
1, Delayed federal health tracking and limited testing are making it harder to trace the source of an ongoing outbreak of a parasitic disease that's triggering "explosive diarrhea," Axios' Herb Scribner reports. The CDC has identified at least 843 confirmed domestic cases and over 1,500 that require further analysis.

*** parasitic
https://www.dicts.cn/dictword20181/html/fc41b50d60fbe03692af0e6b2ac4b3e1.html?parasitic

*** explosive
https://www.dicts.cn/dictword20181/html/9caa2f779849a8cb7135e820b19b03f7.html?explosive

** Two
2. The king of dinosaurs has reclaimed his throne. A 38-foot-long, 67-million-year-old Tyrannosaurus Rex named Gus sold for $50.1 million at Sotheby's. It's an auction record for a fossilized dinosaur skeleton, beating a 150-million-year-old Stegosaurus that sold for $44.6 million two years ago.

*** Sotheby's
https://en.wikipedia.org/wiki/Sotheby's?useskin=vector

*** throne
https://www.dicts.cn/dictword20181/html/9cccbff0db46d32e2425380a28d6c6cf.html?throne

** Three
3. President Trump's new plan to wrest control of the Strait of Hormuz by resuming strikes and reimposing the blockade is his third major shift in military strategy. A stable peace appears elusive, some former officials say. Meanwhile, Trump abruptly backed off a plan to charge a 20% fee for commercial ships transiting the strait that he'd announced yesterday, and Iran is attacking a crucial oil-market lifeline: shuttle runs.

*** elusive
https://www.dicts.cn/dictword20181/html/e3ba9d8f06d3377bc541135e87fbf160.html?elusive

*** back off
https://www.bing.com/dict/search?q=back%20off

*** shuttle
https://www.dicts.cn/dictword20181/html/1bd5b859c5f5020fea5bb57aa1a6f125.html?shuttle
* [[https://www.youtube.com/watch?v=0dXpdr65Z60][(8) Weekly Listening Compilation (Issues 352 & 353) | Intensive Listening | Authentic American Englis... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-24 Fri 09:23]
:END:
** barge into
https://www.bing.com/dict/search?q=barge%20into

** heir
https://www.dicts.cn/dictword20181/html/10b01a34ec1150b2f4c086f1b1a35e2e.html?heir

** unassailable
https://www.dicts.cn/dictword20181/html/80eff981338ecd498572c8be24c6cdcc.html?unassailable

** cosmic
https://www.dicts.cn/dictword20181/html/cd5bdce999b90efad856391fe6706269.html?cosmic

** rite
https://www.dicts.cn/dictword20181/html/b00108822a89701e5f2d9533a665e0cc.html?rite

* [[https://www.youtube.com/watch?v=l04b-inG64s][(8) 读懂英语新闻（第354期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-24 Fri 09:40]
:END:

** One
1, Taylor Farms, one of the nation's largest producers of leafy greens and fresh vegetables, said today that it would remove its products at the center of a cyclosporiasis outbreak that has sickened more than 1,600 people. The C.D.C. linked the outbreak to iceberg lettuce that the company had supplied to Taco Bell. Federal investigators are now turning their attention to Mexico, where the lettuce was grown and shredded.

*** Taylor Farms
https://en.wikipedia.org/wiki/Taylor_Farms?useskin=vector

*** shred
https://www.dicts.cn/dictword20181/html/6bcf53b52921b403ca47ebf34d4b1103.html?shred

** Two
2. Trump Administration Plans to Limit Length of Student Visas
New rule would cap duration of visas at four years and require holders to apply for extensions to stay longer. For roughly the last five decades, student visas were valid for the years that an educational program lasted, plus optional practical training.

*** cap
https://www.dicts.cn/dictword20181/html/b8e62ecbb1c615d1a1157a89ca38d2e1.html?cap

** Three
3. A surprise breakthrough from Chinese Al startup Moonshot rumbled through global markets, sending chip stocks reeling, as queasiness returned about the industry's voracious spending. The company claims its new Kimi K3 model rivals top offerings from OpenAI and Anthropic in a release reminiscent of last year's "DeepSeek moment."

*** reel
https://www.dicts.cn/dictword20181/html/9b3ea000e0ed48eda35157e9d67135e9.html?reel

*** voracious
https://www.dicts.cn/dictword20181/html/97cd6b6d413e65a26450a7158b39bd6f.html?voracious

*** reminiscent
https://www.dicts.cn/dictword20181/html/97bee575fa449af6f7db39d89110f485.html?reminiscent

* [[https://www.youtube.com/watch?v=WqlH3Miu_oA][(7) Improve Your Listening Skills with American TV (Episode 354) | Intensive Vocabulary Listening | A... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-27 Mon 09:35]
:END:

** cattle
https://www.dicts.cn/dictword20181/html/fcc032ae954dc0bfac0d379950e0cf91.html?cattle

* [[https://www.youtube.com/watch?v=6wgwtyyYVpw][(9) Understanding English News (Episode 355) | Learn English Through News | Rapid Vocabulary Growth |... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-28 Tue 09:44]
:END:

** One
1. Revelers celebrated in the streets of Madrid after Spain's men's national soccer team hoisted this year's World Cup trophy. Their victory over Argentina — a composed display of control-first soccer — was a thrilling end to a tournament that brought the world to its feet time and time again.

*** Madrid
https://en.wikipedia.org/wiki/Madrid?useskin=vector

*** compose
https://www.dicts.cn/dictword20181/html/9cc21d728c39904ad8cdf865e45d5f55.html?compose

***  thrill
https://www.dicts.cn/dictword20181/html/134336d90da03874d580f0159e4946f4.html?thrill

** Two
2. Fake influencers are trying to sell you supplements
The Times has uncovered hundreds of A.I.-generated videos designed to sell supplements on social media. The videos often feature fake doctors, healers and wellness influencers making claims about the supposed health benefits of particular wellness regimens. Many of the claims are misleading and unfounded, and they often target older women.

*** regimen
https://www.dicts.cn/dictword20181/html/8b2d412e73af85a43caba335b15986e6.html?regimen

** Three
3. France voted today to become the first European country to restrict access to social media for anyone under 15. The new law also bans the use of cellphones in high schools. The country joins a wave of governments around the world promising to protect young people from online harm. In Australia, enforcement of their ban has largely failed. For France, success may rely on intervention from the European Union, which can penalize internet platforms.

* [[https://www.youtube.com/watch?v=-cPrBtx5PCg][(10) Weekly Listening Compilation (Issues 354 & 355) | Intensive Vocabulary Listening | Authentic Amer... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-29 Wed 09:49]
:END:
** colors
https://www.dicts.cn/dictword20181/html/89cfae3eff10eb14029e806083a0a93d.html?color

** prone
https://www.dicts.cn/dictword20181/html/2977c01e551e7703f43d4395dea679d8.html?prone

** up someone's sleeve
https://www.sohu.com/a/340797997_120066543

** recess
https://www.dicts.cn/dictword20181/html/9091a95f7b697c90e412b5613a77161c.html?recess

* [[https://www.youtube.com/watch?v=hhs6py2s5gA][(11) 读懂英语新闻（第356期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-30 Thu 09:25]
:END:

** One
1. Every four years, the prestigious Fields Medals are awarded to some of the most accomplished mathematicians under the age of 40. This year's prizes were handed out today to Hong Wang, Jacob Tsimerman, John Pardon and Yu Deng. They each have spent their careers working on problems that seem almost impossibly complex. But it's always fun to read about what the some of the world's sharpest minds are spending their time on. Pardon focused on theoretical loops; Wang delivered a proof about a spinning pencil.

*** prestigious
https://www.dicts.cn/dictword20181/html/677d2735b44c801643d55f06c8ef0036.html?prestigious

*** Fields Medals
https://en.wikipedia.org/w/index.php?title=Fields_Medal&useskin=vector

*** hand out
https://www.bing.com/dict/search?q=hand%20out

*** [#A] sharp
https://www.dicts.cn/dictword20181/html/64d63a0c3ba2f7d3ee89fe8029b9e25a.html?sharp

** Two
2. Tons of golf fans learned this week they didn't win the Masters ticket lottery — an annual rejection that has become almost as much of a tradition as the tournament itself. About 2 million people apply for Masters tickets for each tournament day, with applicants having just a 0.55% chance - roughly 1 in 182 - of being selected, according to one estimate from Bookies.com. Those are better odds than being struck by lightning or winning the lottery.

*** lottery
https://www.dicts.cn/dictword20181/html/285fd807d70ac6b85aee234b0ba9c5be.html?lottery

*** odds
https://www.dicts.cn/dictword20181/html/4ae7841bcd0dd5eeeaac26c8578da7b3.html?odds

** Three
3. "Choke point" — an increasingly popular shorthand for the bottlenecks tying up the oil market and the Al buildout — is having a moment. The latest choke point is in the Red Sea. Saudi Arabia has been routing more oil there via pipeline, bypassing the OG choke point in the Strait of Hormuz.

*** choke point
https://www.bing.com/dict/search?q=choke%20point

*** bottleneck
https://www.dicts.cn/dictword20181/html/27be977a6710a95ffc64a80b617ce65e.html?bottleneck

*** tie up
https://www.bing.com/dict/search?q=tie%20up


* [[https://www.youtube.com/watch?v=7GLoO52d3GA&t=11s][(11) 美剧练听力（第356期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第356期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-31 Fri 09:27]
:END:


** pocket
https://www.dicts.cn/dictword20181/html/8cb743293808bbb546ea1b7b13df33c3.html?pocket

* [[https://www.youtube.com/watch?v=UyQ3p3-TDf0][(11) 读懂英语新闻（第357期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-07-31 Fri 09:39]
:END:

** One
1. It has been a rough season when it comes to food-borne illnesses A salmonella outbreak led to the recall of 19 million eggs. An E. coli infection was traced to some organic blueberries. And as of its latest update, the C.D.C. has confirmed or is investigating a record 11,500 cases of cyclosporiasis, an intestinal illness caused by a parasite and transmitted through food or water contaminated with human feces. But top health regulators insisted this week that consumers could still trust what they were eating.

*** [#A] recall
https://www.dicts.cn/dictword20181/html/bb51f584dea04cf11e69cf01cf1cafea.html?recall

*** parasite
https://www.dicts.cn/dictword20181/html/026fa5087ef985a4a2d6d87f182382e9.html?parasite

*** contaminate
https://www.dicts.cn/dictword20181/html/7ff27b0c103988cb56abcd6cc136763d.html?contaminate

*** feces
https://www.dicts.cn/dictword20181/html/40ad3d4b5816708ef9d2ca9dece7a98d.html?feces

** Two
2. Al chatbots know how to make biological weapons. Some will teach you.
After OpenAl enhanced the brain power of its chatbot last summer, hundreds of users worldwide began asking it how to make and deploy biological weapons and poisons. The models gave step-by- step instructions. OpenAI banned these accounts but didn't alert authorities.

** Three
3. A 6.8-magnitude earthquake hit southwest Japan today, igniting fires, destroying buildings, homes and highways, and injuring dozens. Rescuers searched through the rubble of a partly collapsed shopping mall after fire officials said that people appeared to be trapped inside. Social media video captured the moment that the quake damaged Kumamoto Castle, one of Japan's oldest and grandest castles.

*** ignite
https://www.dicts.cn/dictword20181/html/22476af4e043de1a66e1ff1020ef73e2.html?ignite

*** rubble
https://www.dicts.cn/dictword20181/html/c4a5696055178fa226085094c0b283cf.html?rubble

        
* [[https://www.youtube.com/watch?v=ML_nSr3Btqo][(11) Weekly Listening Compilation (Issues 356 & 357) | Intensive Vocabulary Listening | Authentic Amer... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-03 Mon 09:38]
:END:

** swell
https://www.dicts.cn/dictword20181/html/cb4f79c000a348bc0015c8c875c330cd.html?swell
* [[https://www.youtube.com/watch?v=cw_vhX9lnTY][(11) 读懂英语新闻（第358期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-03 Mon 09:44]
:END:

** One
1. The Trump administration is considering a $100,000 fee for international students who want to work in the U.S. after graduating from an American university, people familiar with the matter said. If enacted, the fee would make studying in the U.S. less attractive for foreigners. It also would significantly advance President Trump's efforts to restrict legal immigration. The proposed policy would particularly harm universities, which rely on recruiting international students as a reliable source of revenue, as well as top Silicon Valley and Wall Street firms, which disproportionately hire international graduates to fill technical roles.

*** enact
https://www.dicts.cn/dictword20181/html/7b8cea921fd591b296f754a2a50db98f.html?enact

** Two
2. The Big Mac Index — a clever project from The Economist that compares prices of McDonald's burgers in different countries — is turning 40.McDonald's makes the Big Mac in a near-identical way everywhere, so its price acts as a rough gauge of whether a currency is undervalued or overvalued. Right now, the index shows the euro is overvalued against the dollar, while China's yuan and Japan's yen are undervalued.

*** Big Mac Index
https://en.wikipedia.org/wiki/Big_Mac_Index?useskin=vector

*** gauge
https://www.dicts.cn/dictword20181/html/daf1b8d390d6f263c8a7a3441b27ea8e.html?gauge

** Three
3. The artful boomer. Nearly $1 trillion of art is expected to change hands in the coming decade as the generation born during the post-war baby boom bequeaths its vast trove of collectibles. Problem is, there won't be enough buyers or museums to absorb it all.

* [[https://www.youtube.com/watch?v=21b8Gw-S9w8][(11) English Listening Practice with US TV Shows (Ep. 358) | Intensive Vocabulary Study | Authentic Am... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-04 Tue 09:30]
:END:

** wit
 https://www.dicts.cn/dictword20181/html/879efd5ef69f78694236f8902148c8dc.html?wit       

* [[https://www.youtube.com/watch?v=ZwjjSx77oDI][(13) Understanding English News (Ep. 359) | Learn English Through News | Rapid Vocabulary Expansion | ... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-06 Thu 09:22]
:END:


** One
1. Health officials in Michigan, which has been at the center of a nine-state outbreak of cyclosporiasis, said that two deaths had been linked to the intestinal illness. The two people who died had "significant underlying health conditions that may have been impacted by cyclosporiasis and dehydration," officials said. The infection causes lengthy bouts of diarrhea, which can be dangerous for vulnerable groups including infants, older adults and those who are pregnant or have weakened immune systems.

*** intestinal
https://www.dicts.cn/dictword20181/html/6b1c020be8fbc6206da8251b3ddaba65.html?intestinal

*** lengthy
https://www.dicts.cn/dictword20181/html/ec42eacc1fdfb5219eb59d41f8d50722.html?lengthy

*** bout
https://www.dicts.cn/dictword20181/html/afbe43cdd580cb5c8ed8cb70b2244e13.html?bout

** Two
2. China's Al industry is flooding the market with increasingly capable models, rapidly closing the gap with Silicon Valley. For OpenAI and Anthropic, whose trillion-dollar ambitions depend on premium pricing, China's low-cost Al offensive is becoming the biggest threat yet. The US has threatened sanctions over alleged intellectual property theft, while China has vowed to respond.

*** premium
https://www.dicts.cn/dictword20181/html/3e1720af0d154e927f39fc813fe3df56.html?premium

*** offensive
https://www.dicts.cn/dictword20181/html/62247e509b0ef4623dcbc0508a405d47.html?offensive

** Three
3. U.S. families expect to spend over $900 on average on back- to-school shopping this year. Total K-12 back-to-school spending could climb around 10% this year compared to last, hitting a record $43.3 billion, the National Retail Federation forecasts. Northeast families plan to spend the most, $1,076 on average, well above the $922 national average. That figure covers clothes, tech, after-school gear, books, supplies and other one-time purchases.

*** National Retail Federation
https://en.wikipedia.org/wiki/National_Retail_Federation?useskin=vector

*** gear
https://www.dicts.cn/dictword20181/html/1070395ef733c433c61c62112378cb95.html?gear


* [[https://www.youtube.com/watch?v=fc5tx1lAsy0][(2) Weekly Listening Compilation (Ep. 358 + Ep. 359) | Intensive Vocabulary Listening | Authentic Ame... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-07 Fri 09:31]
:END:


** chance
https://www.dicts.cn/dictword20181/html/3013cbade66457ea36f340901e630773.html?chance

* [[https://www.youtube.com/watch?v=lc9nb2NnGag][(4) 读懂英语新闻（第360期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-11 Tue 09:29]
:END:


** One
1, OpenAI's highly anticipated consumer device will cost more than $300 and have a "unique look, complete with moving parts that help give it personality" .The device will be shaped like a donut and about the size of a hockey puck — designed to make it easy to carry around the home. It'll work like ChatGPT's voice mode on a phone but powered by more advanced models built for humanlike interaction. The device is designed to learn more about its user over time so it can act less like a typical voice assistant and more like a real person.

*** anticipate
https://www.dicts.cn/dictword20181/html/5fd61d0e5281d9d706de66e97b32d78b.html?anticipate

*** complete with
https://www.bing.com/dict/search?q=complete%20with

** Two
2. Google Earth released its own generative A.I. feature — which, for about 24 hours last week, allowed the creation of deepfake aerial images. The company had intended to unleash users' imaginations. ("What did my neighborhood look like 100 years ago?") Instead, people showed how easily it could be used to generate very realistic nuclear power plants, refugee camps, burned forests, flooded cities and even a fatal car crash.

*** aerial
https://www.dicts.cn/dictword20181/html/dc69d1313190f68a4bad19a8c84cc21c.html?aerial

*** neighborhood
https://www.dicts.cn/dictword20181/html/f56e48a5f7ecfa5c77a029a7daba30c6.html?neighborhood

** Three
3. Trump signed two executive orders targeting birthright citizenship - one aimed at limiting who qualifies and the other at restricting visas for some pregnant women. Aides say the orders do not go against the Supreme Court ruling upholding the right.

* [[https://www.youtube.com/watch?v=1eM2Bm5gEOw][(6) American TV Show Listening Practice (Episode 360) | Intensive Vocabulary Listening | Authentic Am... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-12 Wed 09:31]
:END:

* [[https://www.youtube.com/watch?v=ioJ1RgVbBEo][(7) 读懂英语新闻（第361期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-13 Thu 09:28]
:END:

** One
1, Taylor Farms is pulling more than a dozen prepared foods containing jalapeños, including salsas and guacamole, from retailers due to concerns over salmonella. The recall follows the largest outbreak of cyclospora last month linked to Mexican iceberg lettuce supplied by Taylor Farms to companies including Yum! Brands Inc.'s Taco Bell.

** Two
2. Americans worry about artificial intelligence stealing their jobs and making electricity more expensive. And they hate the giant data centers that power this technology; more than half say they'd support banning them. Trump has maintained a much more sanguine view about the coming digital revolution. He has called data centers "Money Machines, " saying they amount to "tremendous WINS for the States and Communities that are lucky enough to get them.

*** [#A] power
https://www.dicts.cn/dictword20181/html/d00421d8797b7e44c0237b3f1c5c1930.html?power

*** amount to
https://www.bing.com/dict/search?q=amount%20to

*** tremendous
https://www.dicts.cn/dictword20181/html/5c65f3a8eb208793732cd9a6b178ca2b.html?tremendous

** Three
3. A 7.4-magnitude earthquake struck Colombia, trapping people under collapsed buildings and presenting an early challenge to the country's new president. Local officials reported more than 100 killed in the country's west. Authorities said the death count could rise because an unknown number of people were trapped under rubble after the quake hit at 7:34 a.m. local time.
* [[https://www.youtube.com/watch?v=3Qi8IeKXEZw][(8) 一周听力合集（第360期+第361期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第361期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-17 Mon 09:30]
:END:
* [[https://www.youtube.com/watch?v=m7dEdmWZZXI][(8) 读懂英语新闻（第362期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-17 Mon 09:38]
:END:

** One
1, Luigi Mangione admitted that he shot and killed Brian Thompson, a health care executive, as he pleaded guilty to two federal charges of stalking resulting in death. Mangione still faces a murder charge in state court. But his lawyers have filed a motion to dismiss it, saying it violates his legal protection against double jeopardy. He faces the possibility of life in prison when he is sentenced in December on the federal charges.

*** stalk
https://www.dicts.cn/dictword20181/html/7b5b8c4a54418936da3d628c5a08c23a.html?stalk

** Two
2. OpenAI keeps on getting bigger. The ChatGPT maker is on track to generate annualized revenue of more than $40 billion, roughly doubling its run rate from the end of 2025, people familiar said. Revenue has accelerated in recent months thanks to subscription sales and its nascent advertising business, bolstering plans for an IPO.

*** run rate
https://www.bing.com/dict/search?q=run%20rate

*** nascent
https://www.dicts.cn/dictword20181/html/8a5771c823f6da3abb6964780e21f39a.html?nascent

*** bolster
https://www.dicts.cn/dictword20181/html/bac66edf7519c3b274b6b435160701c0.html?bolster

** Three
3. Be it needlework, scrapbooking or marathon running, if you've got a weekend of crafting or hobbies ahead, you're not alone. Americans are dipping into their savings to fund them, pushing pastime spending to a record share of US goods consumption — above even pandemic-era highs.

*** marathon
https://www.dicts.cn/dictword20181/html/d11cc7e0bf907a429df731d3eb0dc0d7.html?marathon

*** dip into
https://www.bing.com/dict/search?q=dip%20into
* [[https://www.youtube.com/watch?v=iuVsRN4tUl4][(10) 美剧练听力（第362期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第362期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-19 Wed 09:33]
:END:

* [[https://www.youtube.com/watch?v=WCwapMqd89A][(11) Understanding English News (Episode 363) | Learn English Through News | Expand Your Vocabulary | ... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-20 Thu 09:24]
:END:


** One
1. The Justice Department will allow felons who lost their gun rights to apply to have them reinstated. The regulation is expected to spur a surge in applications from people whose convictions automatically barred them from owning firearms. An estimated 330,000 people are expected to apply to the Justice Department during the first year of the initiative.

*** surge
https://www.dicts.cn/dictword20181/html/a73ab5a5569a792ff6af05d50ffc4de5.html?surge

** Two
2. Marathon runners are adding heat training to their routines as climate change becomes a variable they can't ignore. From $234 cooling headbands to regular visits to the sauna, there's a growing emphasis on helping the body cope with higher temperatures.

*** cope with
https://www.bing.com/dict/search?q=cope%20with

** Three
3. Yields on American 30-year Treasuries briefly rose above 5.3%, to their highest level since 2007, because of growing fears about inflation, the country's $40trn debt and rising oil prices. Government borrowing costs also jumped in Britain and Japan, and hit multi-year highs in France and Germany.

*** yield
https://www.dicts.cn/dictword20181/html/93225ab7d5aaebece75ea9546457eabb.html?yield

* [[https://www.youtube.com/watch?v=s2oRzpwzr6c][(11) Weekly Listening Compilation (Issue 362 + Issue 363) | Intensive Vocabulary Listening | Authentic... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-21 Fri 09:50]
:END:


** come across
https://www.bing.com/dict/search?q=come%20across

** freelancer
https://www.dicts.cn/dictword20181/html/635b8ea863a0b77c9d7d9cc8ce28d5ce.html?freelancer

* [[https://www.youtube.com/watch?v=CY9wBA7W33k][(11) 读懂英语新闻（第364期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-24 Mon 09:42]
:END:

** One
1. America's royal couple in residence are returning to England, bringing an end to their American dream. After six years in California, Prince Harry and Meghan Markle are making a surprise return to the U.K. The unexpected move comes after a secret summer meeting with King Charles III which sparked hopes of a royal reconciliation. It's still unclear if the couple has mended all fences with the king and whether they'll resume their royal duties.

*** reconciliation
https://www.dicts.cn/dictword20181/html/65d9e4df89a93fd8d98f7fc85ad86be5.html?reconciliation

*** mend
https://www.dicts.cn/dictword20181/html/4549274b014d0864f0ac28fd65c1eed3.html?mend

** Two
2. A personalized vaccine developed by Merck and Moderna, whose Covid-19 shot proved critical to curbing the global pandemic, reduced the recurrence of melanoma in a large, late-stage trial. The news raised expectations for treating the deadliest form of skin cancer and the potentially wider promise of mRNA technology.

*** recurrence
https://www.dicts.cn/dictword20181/html/edb449374f43b6e9032a6ffa9980c99d.html?recurrence

** Three
3. A tiny slice of Italy is rolling into America's golf-cart market. Fiat's $15,000 Topolino, Italian for "little mouse," is drawing early demand from affluent buyers looking for an alternative to traditional carts.

*** affluent
https://www.dicts.cn/dictword20181/html/e12a610c9421a4ddabe0580674ffb33b.html?affluent
* [[https://www.youtube.com/watch?v=8m9NJrUT_aE][(11) American TV Show Listening Practice (Episode 364) | Intensive Vocabulary Listening | Authentic Am... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-27 Thu 09:38]
:END:
** colonial
https://www.dicts.cn/dictword20181/html/1608c38997c7ccaf10cd287b9ee2447e.html?colonial

* [[https://www.youtube.com/watch?v=BsM8U-Kc8AA][(11) 读懂英语新闻（第365期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-27 Thu 09:45]
:END:


** One
1. This morning, Canada announced retaliatory tariffs as high as 50 percent on hundreds of American products. The biggest blow: doubled duties on steel and aluminum. But the catalog of affected goods is huge and includes railway locomotives, smartphones, dishwashers and a variety of fishes, frozen and fresh.

*** blow
https://www.dicts.cn/dictword20181/html/e2c22c7313f78c09a003352c5886aca9.html?blow

*** locomotive
https://www.dicts.cn/dictword20181/html/e4a49ac967444e398c221cb009afe3d4.html?locomotive

** Two
2. At this weekend's World Humanoid Robot Games in Beijing, a robot sprinted down a track and completed a 100-meter dash in just 9.39 seconds. That's faster than any human has ever run the distance, including Usain Bolt, the world-record holder. The robot finished the race by slamming full speed into a padded wall, falling down and being carried away by human assistants — a reminder that the technology is still far from perfection.

*** sprint
https://www.dicts.cn/dictword20181/html/a19953e22d8cd4fbf44eba3ba271b450.html?sprint

*** dash
https://www.dicts.cn/dictword20181/html/dce3666f92aaf4f4ea55bcade52bcde2.html?dash

*** slam into
https://www.bing.com/dict/search?q=slam%20into

** Three
3. The college admissions process is shifting once again
Standardized testing requirements, which fell out of fashion during the Covid era, are being revived, or are under consideration, at colleges and universities across the country. At the same time, supplementary essays are disappearing, in part because students can now use A.I. tools to write their submissions.

*** admission
https://www.dicts.cn/dictword20181/html/8abc81af076d0d7f5e68765fa6f28f36.html?admission

*** essay
https://www.dicts.cn/dictword20181/html/7cee957c6fca27b4b3cd889587d352eb.html?essay
* [[https://www.youtube.com/watch?v=J4lQA6v-cWo][(1) Weekly Listening Compilation (Issues 364 + 365) | Intensive Vocabulary Practice | Authentic Ameri... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-08-31 Mon 09:40]
:END:
** bat
https://www.dicts.cn/dictword20181/html/ab1e6d0926471951c3252aa68ba468d4.html?bat

** pierce
https://www.dicts.cn/dictword20181/html/2acbd7c109708b8c7b9bc4d4cf953b83.html?pierce
* [[https://www.youtube.com/watch?v=S57DDLOeS0A][(2) 读懂英语新闻（第366期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读学英语 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-09-01 Tue 09:37]
:END:
** One
1. Trump orders the creation of a space academy
Declaring today that "space is the hot thing, " the president signed an executive order to establish a space academy, similar to the Naval Academy in Maryland or the Coast Guard Academy in Connecticut. Plans are still preliminary, but the order said that the academy would feed its graduates into the U.S. Space Force and NASA.

*** Naval Academy
https://en.wikipedia.org/wiki/United_States_Naval_Academy?useskin=vector

*** Coast Guard Academy
https://en.wikipedia.org/w/index.php?title=United_States_Coast_Guard_Academy&useskin=vector

** Two
2. The $18 billion settlement Meta reached with 48 states over social media's harm to teenagers has brought an end to a massive federal trial and is ushering in a new era of legal accountability for tech platforms. As part of the settlement agreement, Meta will also make sweeping changes to Facebook and Instagram, including implementing a default two-hour time limit on its apps for users under 18.

*** settlement
https://www.dicts.cn/dictword20181/html/cc417416f34e4704c50fc1b3055ba95c.html?settlement

*** usher
https://www.dicts.cn/dictword20181/html/cca872a37c8d1abc994d51c7fc9c7011.html?usher

*** sweeping
https://www.dicts.cn/dictword20181/html/a4d6dc8c19597be36a85ee2d2459156f.html?sweeping
** Three
3. Nepal's catastrophic flood is exposing gaps in the warning systems designed to watch out for extreme rain and rivers - not for sudden collapses high in the mountains during good weather. Such glacier-driven floods under clear skies — sometimes called "blue-sky floods" — can happen in the U.S. too, especially in Alaska and the Pacific Northwest, where sudden releases of glacial water can send floods and debris racing down mountain valleys.

*** watch out
https://www.bing.com/dict/search?q=watch%20out

*** glacial
https://www.dicts.cn/dictword20181/html/8ca5964b1aff2b9c6f4091f7cfe16524.html?glacial

*** debris
https://www.dicts.cn/dictword20181/html/661915ff886fa8eb72b714775a825cdf.html?debris

* [[https://www.youtube.com/watch?v=5x5Bgtq1FY4][(2) Understanding English News (Episode 367) | Learn English Through News | Rapid Vocabulary Growth |... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-09-16 Wed 09:28]
:END:

** One
1. New York City Mayor Zohran Mamdani released more than 170,000 pages of records about the aftermath of the Sept. 11, 2001 attacks, including documents showing officials were weighing potential liability from toxic exposure while trying to reassure the public about the safety of Lower Manhattan. The twin towers' collapse created massive dust clouds that enveloped much of downtown, covering highly populated neighborhoods with ash, debris and harmful particles.

*** weigh
https://www.dicts.cn/dictword20181/html/2b152268b101b648d01592aa05635143.html?weigh

*** liability
https://www.dicts.cn/dictword20181/html/05bbc029928a6ec91790e3cafef7db58.html?liability

*** toxic
https://www.dicts.cn/dictword20181/html/f05dc6245a59c72a7dacc126d1373893.html?toxic

*** reassure
https://www.dicts.cn/dictword20181/html/49ece4f4f6de9f5652c3843c36f4facb.html?reassure

*** ash
https://www.dicts.cn/dictword20181/html/79878521277c1fce8dedfe4a82739a21.html?ash

** Two
1. OpenAI said today that its newest artificial intelligence tool had solved one of the most closely watched unanswered questions in mathematics, in just 88 hours. The problem, called Navier-Stokes, involves a series of equations often used to predict the weather. Humans have been working to solve it for decades.

** Three
3. U.S. health providers are increasingly either encouraging prepayment, requiring it or collecting a payment method on file during the estimate process. It is causing sticker shock for patients, and headaches for those who overpay and then try to collect refunds.

*** on file
https://www.bing.com/dict/search?q=on%20file

*** sticker shock
https://www.bing.com/dict/search?q=sticker%20shock
* [[https://www.youtube.com/watch?v=ZKY9iBzunjs][(5) Understanding English News (Episode 368) | Learn English Through News | Rapid Vocabulary Growth |... - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2026-09-20 Sun 09:27]
:END:
** One
1. Microsoft artificial intelligence chief Mustafa Suleyman is warning that infusing tools like Anthropic's Claude with humanlike characteristics increases the risks of such systems going rogue. Claude's constitution expresses ambiguity about whether the assistant is a moral entity, positing that the software may have "some functional version of emotions or feelings.

*** infuse
https://www.dicts.cn/dictword20181/html/0bc87228c4f5afaeca456e49cbe3566a.html?infuse

*** go rogue
https://www.bing.com/dict/search?q=go%20rogue

*** posit
https://www.dicts.cn/dictword20181/html/9865a54aaa30cf7edf1fc3f869883a9a.html?posit
** Two
2. The U.S. has space weapons in orbit right now, Air Force Secretary Troy Meink said this week at the Air, Space & Cyber Conference in National Harbor, Md. The declaration is a first and marks a significant shift in how the world discusses such systems, which are considered highly sensitive and provocative.

** Three
3. In a unanimous vote, the Federal Reserve raised interest rates by a quarter percentage point and penciled in an additional hike later this year, steps aimed at containing rising inflation that's been fueled in part by a global energy crisis triggered by the US-Israel war with Iran.It was the central bank's first rate increase since July 2023.

*** unanimous
https://www.dicts.cn/dictword20181/html/c19679c5bae1c72afab179ab9ce3e886.html?unanimous

*** pencil in
https://www.bing.com/dict/search?q=pencil%20in

*** contain
https://www.dicts.cn/dictword20181/html/049d38decf97edd08fdbeb0725441aaa.html?contain

