#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil
#+FILETAGS: ANKI
#+STARTUP: indent
#+ANKI_DECK: English

* [[https://www.youtube.com/watch?v=DFZRg8z_AJg][(10) 读懂英语新闻（第186期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Judges rejected TikTok's effort to avoid a U.S. ban TikTok, a video app used by more than 170 million Americans, moved one step closer today to disappearing from the U.S. market. A panel of federal judges unanimously upheld a new law that requires the app's Chinese owner to either sell TikTok to a non-Chinese owner by mid-January or face a nationwide ban in the U.S. While Donald Trump has promised to save the app, the law is set to go into effect the day before his inauguration and it's unclear how he could evade an act of Congress and whether he wants to risk much political capital on this given his hawkish stance on China.

*** uphold
https://www.dicts.cn/dictword20181/html/989df1761b1b75533204b66f97db2cfc.html?uphold
*** inauguration
https://www.dicts.cn/dictword20181/html/9750f77fcc333d0063e48dc4a46a7dab.html?inauguration
*** evade
https://www.dicts.cn/dictword20181/html/229c6d84081dfac701273bd8616fe3f6.html?evade
** Two
2. N.Y.P.D. said the shooting suspect may have left the city New York's police commissioner said today that the man who fatally shot a health insurance executive in Midtown Manhattan might have left the city. The authorities said they have video of the man taking a cab to an interstate bus station in Upper Manhattan and entering it on the day of the attack, but never exiting. So far, there have been no arrests and the authorities have not established a motive.

*** NYPD
:LOGBOOK:
- Note taken on [2024-12-11 Wed 09:51] \\
  纽约市警察局（NYPD）是美国最大的市警局，下设多个部门，负责维护纽约市治安。
:END:
https://en.wikipedia.org/w/index.php?title=New_York_City_Police_Department&useskin=vector
*** Manhattan
https://en.wikipedia.org/wiki/Manhattan?useskin=vector
*** interstate
https://en.wikipedia.org/w/index.php?title=Interstate_Highway_System&useskin=vector

https://www.dicts.cn/dictword20181/html/c0e3157f58d94568d3ad6590ef88c905.html?interstate
* [[https://www.youtube.com/watch?v=46AovK1-eX4][(10) 读懂英语新闻（第187期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Suspect in C.E.O. killing is fighting extradition
The 26-year-old man who was charged with murder in the assassination of a health insurance executive in Midtown Manhattan was denied bail today. Mangione saw himself as a hero fighting a corrupt health insurance industry, the authorities said in an internal report obtained by The Times. The police also expressed concern that the attack could inspire violence against similar executives or other extreme behavior. Here's what we know about the suspect: Mangione was a high school valedictorian and an Ivy League tech graduate from a prominent Maryland family. The subject of a missing-person report filed in San Francisco by his mother last month, he had stopped communicating with friends and family about six months ago.

*** extradition
https://en.wikipedia.org/wiki/Extradition?useskin=vector

引渡是一个复杂的问题，涉及主权、司法合作和人权等多方面因素。
*** bail
https://www.dicts.cn/dictword20181/html/b2968cb6e96623280f4a9d8b49a7546b.html?bail
*** Ivy League
https://en.wikipedia.org/wiki/Ivy_League?useskin=vector

常春藤联盟（Ivy League）是美国东北部八所私立研究型大学组成的大学体育联盟，也是全球知名的精英大学联盟，以其学术卓越、录取率极低以及社会精英地位而闻名。
** Two
2. Hundreds of firefighters are racing to control a fast-moving Southern California wildfire that's threatening the wealthy town of Malibu and has forced the evacuation of thousands of residents. The Franklin fire has swelled to more than 2,700 acres and remained completely out of control as of Tuesday afternoon.

*** Malibu
:LOGBOOK:
- Note taken on [2024-12-12 Thu 10:03] \\
  马里布独特的地理位置、气候条件和历史文化，使其成为一个备受瞩目的海滨城市，但同时也面临着自然灾害和环境保护等方面的挑战。
:END:
https://en.wikipedia.org/wiki/Malibu%2C_California?useskin=vector

*** evacuation
https://www.dicts.cn/dictword20181/html/7cdd8f0f5734b59e602a41fe86175a51.html?evacuation

** Three
3. Syrian rebels rushed to impose order in Damascus after Bashar al-Assad's regime collapsed over the weekend. Leader Abu Mohammed al-Jawlani moved to form a transitional government, get the buses running and turn the power back on. Many foreign countries, including the U.S., classify his group as a terrorist organization.

*** rebel
https://www.dicts.cn/dictword20181/html/943d697a82b0197f2cf4a6063218f1cc.html?rebel
*** rush to
https://dictionary.cambridge.org/dictionary/english/rush
*** regime
https://www.dicts.cn/dictword20181/html/63c5693d1234e8452cf3681d876706cf.html?regime
*** move to
https://www.merriam-webster.com/dictionary/move%20to

* [[https://www.youtube.com/watch?v=zrmOoQ8bwBw][(12) 读懂英语新闻（第188期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Trump had his perfect 1980s day. He rang the bell to open the stock exchange and was named Person of the Year by Time magazine. Trump, speaking with Time, pledged to start pardoning Jan. 6 rioters once he enters office. He sounded open to banning some childhood vaccines and reversing protections for transgender kids. During the campaign, Trump said he'd lower grocery prices. Yesterday, he told Time that "it's hard to bring things down once they're up," but he added that he was still hopeful.

*** pardon
https://www.dicts.cn/dictword20181/html/85220aa4f9c05244644b05582ec1136d.html?pardon
*** rioter
https://www.dicts.cn/dictword20181/html/9484d9d841e0df3024a750062075561e.html?rioter
*** it's hard to bring things down once they're up
** Two
2. Lisa Su - chief executive of chipmaker AMD — is TIME's " CEO of the Year." AMD's stock price has increased 50x since Su took over a decade ago, fueled by Al - as well as smart planning that put the company in a position to benefit when some of its rivals, like Intel, have faltered. "It really is one of the great turnaround stories of modern American business history," Chris Miller, a historian of the semiconductor industry, told TIME.

*** falter
https://www.dicts.cn/dictword20181/html/cb117eba831e03c6c0c0737250a885cf.html?falter
** Three
3. The NYPD is investigating a number of 'WANTED' posters of senior executives that are showing up in parts of Manhattan. They included images of UnitedHealth's Brian Thompson, who was murdered last week, as well as executives from American Express, Goldman Sachs, Bank of America and JPMorgan Chase. The arrest of Luigi Mangione this week has failed to fill in some key details of Thompson's killing, while dark glee over the murder is stoking fear among insurers about copycats.

*** WANTED poster
https://en.wikipedia.org/wiki/Wanted_poster?useskin=vector
*** fill in
https://www.bing.com/dict/search?q=fill%20in
*** glee
https://www.dicts.cn/dictword20181/html/26c4d110ea2fe58dc4ea910d2fddae86.html?glee
*** stoke
https://www.dicts.cn/dictword20181/html/0ed4f4b78b9f510d92ee35b57826ee9a.html?stoke
*** copycat
https://www.dicts.cn/dictword20181/html/01082bf951b1606a60cc68b82c4e6ea4.html?copycat
** Four
1. Extreme weather this year across chili planting regions from Mexico to India has sapped supply, pushed up prices and-worst of all-distorted their flavor. The perfect growing conditions for chili peppers and other crops are becoming harder to find as climate change increases the frequency of weather extremes such as drought and floods, according to researchers. Some suppliers are under pressure and chefs will soon be forced to innovate.

*** chili
https://www.dicts.cn/dictword20181/html/445eef9240b6e8d4e3ff6b0c0ebd6538.html?chili
*** sap
https://www.dicts.cn/dictword20181/html/533238291a2d9da6fe24026d0ab1eed7.html?sap
*** flavor
https://www.dicts.cn/dictword20181/html/239912541da6d31b48cadb3c5443cf11.html?flavor
*** drought
https://www.dicts.cn/dictword20181/html/31525edc0f83746564600e3570dcf834.html?drought
*** chef
https://www.dicts.cn/dictword20181/html/7d8ba6ebb64b009730594b4ecbea4c84.html?chef
* [[https://www.youtube.com/watch?v=0V-erwAAzeM][(13) 读懂英语新闻（第189期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-25 Wed 09:53] \\
  [[https://www.youtube.com/watch?v=UzzqHPzyrCo][(13) 听懂英语新闻｜一周英语新闻听力｜纯正美音｜听力练习合集｜听新闻学英语｜单词轻松记｜一起读懂美国新闻｜听力跟读版｜第188期+第189期｜外刊精听｜(2024.12.12—12.18) - YouTube]]
:END:
** One
1. Madison mourned after a school shooting
A makeshift memorial grew on a sidewalk outside a Christian school in Madison, Wis., where a teenage student fatally shot a teacher and a fellow student yesterday. Police identified the shooter as Natalie Rupnow, a 15-year-old student who died from what appeared to be a self-inflicted gunshot wound. Much is still unknown about the attack.

*** Madison
https://en.wikipedia.org/wiki/Madison,_Wisconsin?useskin=vector
*** mourn
https://www.dicts.cn/dictword20181/html/8299d11f09eca98fe03b27d4bffe01b6.html?mourn
*** makeshift
:LOGBOOK:
- Note taken on [2025-06-25 Wed 09:40] \\
  https://www.dicts.cn/dictword20181/html/6a7b4fb01a458ab97ef70f192aec3011.html?makeshift
:END:
https://en.wiktionary.org/wiki/makeshift
*** fellow student
https://www.bing.com/dict/search?q=fellow%20student
** Two
2. Mangione Faces First-Degree Murder Charge That Brands Him a Terrorist
A grand jury formally indicted Luigi Mangione in the killing of Brian Thompson, the chief executive of UnitedHealthcare. "This was a frightening, well-planned, targeted murder that was intended to cause shock and attention and intimidation, " said Alvin L. Bragg, the Manhattan district attorney, at a news conference on Tuesday. A lawyer for Mr. Mangione, Karen Friedman Agnifilo, declined to comment on the new charges. If convicted on the highest charges, Mr. Mangione faces a sentence of life in prison without parole.

*** brand
https://www.dicts.cn/dictword20181/html/4c9cd049681abeb1aa4bcdddbd8a0537.html?brand
*** indict
https://www.dicts.cn/dictword20181/html/0de29f06899f34e3dc92d2dbfef0032e.html?indict
*** intimidation
https://www.dicts.cn/dictword20181/html/22471f08fae98218f73617e7e599bc63.html?intimidate

*** declined
:LOGBOOK:
- Note taken on [2024-12-25 Wed 09:49] \\
  https://www.dicts.cn/dictword20181/html/fe911eb0a594a4f847ef6f0548db4270.html?decline
:END:

*** parole
:LOGBOOK:
- Note taken on [2025-06-25 Wed 09:38] \\
  https://www.dicts.cn/dictword20181/html/3beac348a0aec4b349c19fe5b8eb62e8.html?parole
:END:
https://en.wikipedia.org/wiki/Parole?useskin=vector

** Three
3. A Russian general was killed today by a bomb on a Moscow street. Ukraine claimed responsibility for what appears to be one of the most brazen assassinations since Russia's full-scale invasion nearly three years ago. Yesterday, Kyiv had blamed him for the "massive use of banned chemical weapons" in Ukraine.

*** what appears to be
https://www.bing.com/dict/search?q=what%20appears%20to%20be
*** brazen
:LOGBOOK:
- Note taken on [2024-12-25 Wed 09:53] \\
  https://www.dicts.cn/dictword20181/html/73cd04c35219dfdd2975c5c74bde97b6.html?brazen
:END:

*** full-scale
https://www.bing.com/dict/search?q=full-scale
*** Kyiv
https://en.wikipedia.org/wiki/Kyiv?useskin=vector

* [[https://www.youtube.com/watch?v=xv5OLy8J5wU][(15) 读懂英语新闻（第190期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. A driver plowed a vehicle into a Christmas market in the city of
Magdeburg in central Germany this evening, killing at least two
people and injuring more than 65 others, 14 of them severely. The
driver, identified as a 50-year-old Saudi Arabian citizen, was
arrested, the authorities said. They said they believe it was a
deliberate attack. More than 1,000 Christmas markets pop up every
year in Germany, and have been targeted by terrorists before.
*** plow into

*** Magdeburg
https://en.wikipedia.org/wiki/Magdeburg?useskin=vector
*** deliberate

*** pop up

** Two
2. Hopes were high that the Fed's rate cuts could make homes
more affordable, but so far, that hasn't happened. Average rates
on 30-year mortgages have climbed to around 6.7% from
roughly 6.1% since the central bank started lowering rates in
September, according to Freddie Mac. And they're only poised
to rise further. That's because mortgage rates move with the
yield on the 10-year Treasury, which has surged this week.
*** mortgage
https://en.wikipedia.org/wiki/Mortgage?useskin=vector
*** poised to

*** yield
https://en.wikipedia.org/wiki/Yield_(finance)?useskin=vector
** Three
3. Anthony Loke, Malaysia's transportation minister, announced
plans for a robotics company to renew a search for the plane that
disappeared in 2014. "We think that this is another attempt to find
[Malaysia Airlines Flight] 370, and it is our responsibility, and our
obligation, and our commitment to the families." The flight was en
route to Beijing from Kuala Lumpur with 239 people on board. An
approximately $150 million multiyear search effort-the most
expensive in aviation history— ended in 2017.
*** en route
:LOGBOOK:
- Note taken on [2024-12-24 Tue 09:48] \\
  on the way
:END:

*** aviation
https://en.wikipedia.org/wiki/Aviation?useskin=vector
* [[https://www.youtube.com/watch?v=Gb63l2VsyWQ][(15) 读懂英语新闻（第191期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, American Airlines briefly grounded all U.S. flights
On one of the busiest travel days of the year, American Airlines grounded all
its flights in the U.S. this morning for about an hour. American said a vendor
technology issue had affected systems needed to release flights. While
relatively brief, the ground stop could result in heavy delays in the coming
days. Tens of millions of people fly from mid-December to shortly after New
Year's Day, and a travel record is expected to be set this year. The airline
issued a waiver allowing people flying through some airports to reschedule
their flights through Thursday.
*** American Airline
https://en.wikipedia.org/wiki/American_Airlines?useskin=vector
*** briefly
*** ground
*** vendor
*** ground stop
https://en.wikipedia.org/wiki/Ground_stop?useskin=vector
*** waiver
** Two
2. Believe it or not, there's a long tradition of Santa Claus
polls. The Times ran one in 1985 and, over the years, belief has
held quite steady, even if some parents now wonder if joy will
turn to trauma for their children when the truth comes out.
Americans don't just believe in Santa. They approve of his
performance. In a 2020 poll, 73 percent of respondents gave
him a positive rating.
*** believe it or not
*** Santa Claus
https://en.wikipedia.org/wiki/Santa_Claus?useskin=vector
*** trauma
*** come out
** Three
3. President-elect Trump has big plans to make America
greater — in terms of square mileage. He has floated
acquiring Greenland, reclaiming the Panama Canal,
annexing Canada, and potentially invading Mexico - to the
intense consternation of their leaders.
*** in terms of
*** float
*** reclaim
*** Panama Canal
https://en.wikipedia.org/wiki/Panama_Canal?useskin=vector
*** annex
*** consternation

* [[https://www.youtube.com/watch?v=SDEGEVFrvOM][(18) 读懂英语新闻（第192期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1, "Physical and technical external interference" caused the plane crash
that killed 38 people flying to southern Russia, Azerbaijan Airlines said.
That's the closest officials have come to confirming mounting suspicions
that a Russian air-defense system downed the jet. Russia's aviation
authority said that the plane had tried to land in Grozny in Russia's
Chechnya region amid difficult conditions during a Ukrainian drone
strike. Missiles are now the biggest killer of airline passengers, aviation
safety data show.
*** Azerbaijan Airline
https://en.wikipedia.org/wiki/Azerbaijan_Airlines?useskin=vector
*** mounting
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:00] \\
  https://en.wiktionary.org/wiki/mounting
:END:

*** drone
** Two
2. Musk vowed last night to "go to war" to defend the H-1B visa program for
foreign tech workers, branding some Republican opponents as "hateful,
unrepentant racists." The MAGA-DOGE civil war that erupted over the last 48
hours has hit a tipping point, with President-elect Trump's new techno-libertarian
coalition of billionaires taking full aim at his base. Steve Bannon, one of the
longest-tenured voices in Trump's orbit, had multiple guests on his show this week
to talk about his hardline anti-H-1B views. Bannon tells Axios he helped kick off
the debate with a now-viral Gettr post calling out a lack of support for the Black
and Hispanic communities in Big Tech.
*** unrepentant
*** tipping point
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:00] \\
  https://en.wiktionary.org/wiki/tipping_point
:END:

*** take aim at
*** Steve Bannon
https://en.wikipedia.org/wiki/Steve_Bannon?useskin=vector
*** kick off
*** call out
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:04] \\
  https://en.wiktionary.org/wiki/call_out
:END:

** Three
3. Your so-called face age can tell doctors important
information about your health. Scans of face photos can
estimate people's "biological age." A study found that
an Al-trained model did a better job than doctors of
predicting how long cancer patients will live.
Researchers hope that one day the tool could be a
standard part of assessing health.
* [[https://www.youtube.com/watch?v=1law8VzRdNE][(19) 读懂英语新闻（第193期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Wall Street sees more gains ahead
The S&P 500 index was down slightly today, the final trading day of
2024, but it rose about 23.3 percent this year, roughly matching its gain
in 2023. It was the first time the benchmark index had risen more than
20 percent in consecutive years since 1998. Investors are heading into
2025 in an optimistic mood, believing that, with the economy on firm
footing and the White House in their corner, the stock market will
continue to climb.
*** see
*** gain
*** ahead
*** on firm footing
*** in their corner
:LOGBOOK:
- Note taken on [2025-01-02 Thu 09:50] \\
  来自拳击
:END:

** Two
2. Jimmy Carter, the 39th US president who brokered peace between
Israel and Egypt in the historic Camp David Accords, has died at 100.
His one-term presidency was marred by high inflation, an oil shortage
and the Iran hostage crisis, but some of his most notable achievements
came after he left the White Househis humanitarian work won him
the 2002 Nobel Peace Prize. The former president will get a state
funeral, and Joe Biden designated Jan. 9 as a national day of mourning.
*** Jimmy Carter
https://en.wikipedia.org/wiki/Jimmy_Carter?useskin=vector
*** broker
:LOGBOOK:
- Note taken on [2025-01-03 Fri 09:35] \\
  https://www.dicts.cn/dictword20181/html/f9f7e3234c205ab0e2874dd07c3bd46d.html?broker
:END:

*** Egypt
https://en.wikipedia.org/wiki/Egypt?useskin=vector
*** mar
:LOGBOOK:
- Note taken on [2025-01-03 Fri 09:36] \\
  https://www.dicts.cn/dictword20181/html/897567e13a4312342fb2dace4bec593f.html?mar
:END:

** Three
3. More people of all sizes and speeds are taking on
26.2-mile runs, thanks to super-cushioned sneakers,
running groups and the races' appeal to Gen Z athletes.
The pandemic helped fuel the running craze because
folks wanted exercise they could do alone and outdoors.
*** sneaker
https://en.wikipedia.org/wiki/Sneakers?useskin=vector
*** Gen Z
https://en.wikipedia.org/w/index.php?title=Generation_Z&useskin=vector
* [[https://www.youtube.com/watch?v=oz75nCQjgCA][(3) 读懂英语新闻（第194期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Alcoholic drinks like beer and wine should carry warnings of their links to
cancer, the US's top doctor said. Evidence of links between drinking and cancer
has been rising for decades, yet fewer than half of Americans recognize that it
raises their chances of developing several cancers, Surgeon General Vivek
Murthy said Friday. Alcohol causes about 100,000 cases of cancer and 20,000
related deaths each year in the US, far more than the 13,500 alcohol-associated
annual traffic fatalities. Adding a cancer warning would highlight severe health
concerns for products that more than 70% of US adults consume at least once a
week, with some $260 billion in 2022 nationwide sales. Shares of drinks makers
declined after the announcement.
*** Surgeon General
https://en.wikipedia.org/wiki/Surgeon_general?useskin=vector
** Three
3. The Green Beret who blew up a Tesla outside a Trump hotel in
Las Vegas left notes praising Donald Trump and Elon Musk. Friends
said he had struggled with P.T.S.D. and mental health issues.
*** Green Beret
https://en.wikipedia.org/w/index.php?title=United_States_Army_Special_Forces&useskin=vector
*** blew up
** Four
4. A New York judge upheld Donald Trump's criminal conviction in
the hush-money trial, but signaled that he was likely to spare Trump
jail time. The sentencing is set for Jan. 10.
*** spare
* [[https://www.youtube.com/watch?v=AEK8NHChUGs][(3) 读懂英语新闻（第195期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1 • Wildfires are spreading rapidly in Los Angeles, fanned by a
fierce windstorm. Gusts of up to 100 m.p.h., stronger than any the
region has seen in a decade, are forecast to blow through the night.
The flames are threatening Pacific Palisades, an affluent coastal
neighborhood that is home to about 24,000 people, roughly 20
miles west of downtown Los Angeles. Officials ordered residents
to evacuate immediately.
*** gust
*** evacuate
** Two
2 • Donald Trump said today at a news conference that he
would not rule out the use of military or economic coercion
to retake control of the Panama Canal and to force Denmark
to sell Greenland to the U.S. He also suggested that Canada
should become a U.S. state by getting "rid of that artificially
drawn line." The four nations have rejected his entreaties.
*** rule out
*** coercion
*** Denmark
*** entreaty
** Three
3 • Prime Minister Justin Trudeau is resigning after more
than nine years leading Canada, bowing to sagging
approval numbers and a rebellion within his own party.
Currently the longest-serving leader of any Group of Seven
country, the 53-year-old said Monday he'll step down as
head of the governing Liberal Party within months. He will
remain as prime minister until a new leader is selected.
*** bow
*** sag
*** rebellion
*** Group of Seven
*** step down
* [[https://www.youtube.com/watch?v=x8jeSzbSsqQ][(19) 读懂英语新闻（第204期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Get ready for Super Bowl Sunday
We're just two days away from America's biggest annual sporting event, the
Super Bowl. Kansas City and Philadelphia will meet at New Orleans's famous
Superdome, where Kansas City is narrowly favored to win its third consecutive
title. Kendrick Lamar will headline the halftime show, President Trump is
expected to show up and Taylor Swift will almost certainly be there. Most of us
will watch from home - a ticket costs more than most mortgage payments —
where treats like chicken wings and artichoke dip will be the real stars.
*** headline
*** treat
** Two
2. A federal judge temporarily blocked Elon Musk and some
of his team at the Department of Government Efficiency from
accessing sensitive Treasury payment systems. Last week Mr
Musk claimed doge was cancelling "illegal" payments,
sparking concerns that he had gained access to systems
handling trillions in Social Security and Medicare funds.
*** spark
** Three
3. How to sanitize your kitchen sink
After the effort of cooking a meal and clearing a sink full of dishes, cleaning
the sink itself may be the last thing you want to do. Unfortunately, it's
important: It kills pathogens from produce and raw meat, and it helps keep the
kitchen from getting smelly. Luckily, cleaning your sink can be an easy, two-
step process. Scrub off grime with a bit of dish soap on a brush or sponge and
then rinse the sink down. Next, sanitize it with a spray containing bleach,
making sure to cover the faucets and handles. Let the spray sit for the
recommended time, rinse with water, and voilà.
*** sanitize
*** sink
*** produce
*** scrub off
*** grime
* [[https://www.youtube.com/watch?v=LBUKbSskiSU][(4) 读懂英语新闻（第205期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Trump plans to put the brakes on a law that forbids U.S. A blit
companies from bribing foreign officials to win business. The
measure disadvantages U.S. firms because they can't do what
overseas rivals do, and excessive enforcement crimps the president's
authority to conduct foreign affairs, the White House said. From big
bucks to one cent: Trump said he instructed the Treasury to stop
producing pennies because minting them is a waste of money. Others
say abolishing the penny would impact traders and consumers.
*** brake
*** buck
*** Treasury
https://en.wikipedia.org/wiki/Treasury?useskin=vector
*** mint
** Two
2. Trump announced a 25% tariff on all steel and
aluminum imports. Trump said the new tariffs would
apply to "everybody," including Canada and Mexico,
and take effect immediately. He also plans to introduce
reciprocal tariffs to match duties imposed by other
nations on U.S. goods.
*** reciprocal
** Three
3. Musk led a bid to buy OpenAI
A group of investors led by Elon Musk has made a $97.4 billion bid to buy the
nonprofit that controls OpenAl, the artificial intelligence company that created
ChatGPT. OpenAI declined to comment, but Sam Altman, the company's
chief executive, posted a response on social media: "No thank you but we will
buy twitter for $9.74 billion if you want." Musk, who has had a yearslong
rivalry with Altman, replied to the post: "Swindler," he said.
*** bid
* [[https://www.youtube.com/watch?v=vlYkm1B2rO0][(4) 读懂英语新闻（第206期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. A man in Chile was briefly "swallowed' by a whale
Adrián Simancas was rafting with his
father in the waters of Chilean Patagonia
when a humpback whale suddenly lunged
at him, mouth open, from the waves
below. In an interview, Simancas said he
quickly realized he was trapped in the
whale's mouth: "Something dark blue or
white enveloped me, and a slimy texture
brushed my face." He emerged unharmed.
and his father caught it all on video.
*** Chile
https://en.wikipedia.org/wiki/Chile?useskin=vector
*** brief
https://www.dicts.cn/dictword20181/html/3f1c95fe12f6ed69d08688ef418c34bd.html?brief
*** raft
https://www.dicts.cn/dictword20181/html/220952e78c7fa4650f13a52dc7434e53.html?raft
*** humpback whale
https://en.wikipedia.org/wiki/Humpback_whale?useskin=vector
*** lunge
https://www.dicts.cn/dictword20181/html/c6ae78b7872e4f24c8f3f79a6fca8040.html?lunge
*** envelope
https://www.dicts.cn/dictword20181/html/cbac5e558b06a004b7899f7f4d778fef.html?envelope
*** slimy
https://www.dicts.cn/dictword20181/html/cfc208a5e81e8912c7f1dbc44a67506f.html?slimy
*** texture
https://www.dicts.cn/dictword20181/html/67b3671cf8ebdb8fc49d5a63e844d3bf.html?texture
** Two
2. Every year, Americans import hundreds of millions of rioweis in
the weeks leading up to Valentine's Day. Most of them, of course,
are roses — the classic symbol of love. But the tulip is becoming an
increasingly popular alternative. They are usually less expensive and
more environmentally friendly. And florists we spoke to said they
actually preferred the aesthetic of tulips, which, unlike roses,
continue to change and grow after they're cut.
*** lead up to
*** Valentine's Day
https://en.wikipedia.org/wiki/Valentine%27s_Day?useskin=vector
*** tulip
https://www.dicts.cn/dictword20181/html/3d601b6c3338f8d3f0f8b3729589ea8f.html?tulip
*** florist
https://www.dicts.cn/dictword20181/html/1cb6b06e3a3938fda0b38b46d7d8ba33.html?florist
*** aesthetic
https://www.dicts.cn/dictword20181/html/6aa905ab743076bfe978860df4d13df8.html?aesthetic
** Three
3. Good news, Gen Z! Apple and Google plan to restore
TikTok to their app stores following a letter from the
Department of Justice saying a ban wouldn't be immediately
enforced. The two companies had removed TikTok in the US
last month to comply with a law passed in 2024, before
Trump delayed it taking effect.
*** Department of Justice
https://en.wikipedia.org/w/index.php?title=Ministry_of_justice&useskin=vector
https://en.wikipedia.org/wiki/United_States_Department_of_Justice?useskin=vector
* [[https://www.bilibili.com/video/BV14XAre8EBq/][读懂英语新闻（第207期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. A Delta plane from Minneapolis crashed and flipped on its
back while landing in Toronto yesterday - injuring 18 but not
killing anybody. Officials said all 80 on board were evacuated
from the aircraft, which flipped amid windy weather after a
weekend snowstorm hit the area. One of the plane's wings was
torn off during the incident, which left three people — including
a child — critically injured.
*** Minneapolis
https://en.wikipedia.org/wiki/Minneapolis?useskin=vector
*** Tornonto
https://en.wikipedia.org/w/index.php?title=Toronto&useskin=vector
*** evacuate
https://www.dicts.cn/dictword20181/html/46a6ad040c1d60d7d8e92ce24f01b059.html?evacuate
*** tear off
https://www.dicts.cn/dictword20181/html/8d97007ab591fb684dc7248e507eec62.html?tear%20off
*** critically
https://www.dicts.cn/dictword20181/html/82d6e5335735a5fa7e2c7c31c9e811b6.html?critically
** Two
2. The worst flu season in 15 years has left hundreds of thousands
of Americans hospitalized while straining physicians' offices and
emergency departments. The virus is causing more severe
complications and hitting young children especially hard. This flu
season is classified as a "high-severity" season, with estimates of
at least 29 million cases - the most since the 2009-2010 flu
season, according to CDC data. There have been at least 370,000
hospitalizations and 16,000 deaths from flu as of Feb. 8.
*** strain
https://www.dicts.cn/dictword20181/html/0510eab5dad48207914fa152b60043a9.html?strain
*** complication
https://www.dicts.cn/dictword20181/html/54fef76b059890a1b874e8ce16ade4d3.html?complication
*** CDC
https://en.wikipedia.org/wiki/Centers_for_Disease_Control_and_Prevention?useskin=vector
*** as of
** Three
3. The U.S. and Russia began talks to try to end the war in Ukraine.
At meetings in Saudi Arabia, Washington will push for a quick
cease-fire, and Moscow is expected to call for large concessions.
Ukraine wants to be a party to the talks and has said it's not
obliged to agree to a peace deal negotiated in its absence.
*** call for
https://www.dicts.cn/dictword20181/html/4732c04a96cae8551afec1c841ce6a45.html?call%20for
*** concession
https://www.dicts.cn/dictword20181/html/72c7b3f70891bb51525832609e9f85e6.html?concession
* [[https://www.bilibili.com/video/BV1QdASebEza/][读懂英语新闻（第208期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Archaeologists found a pharaoh's tomb
Egypt's ministry of antiquities announced this week that
researchers had discovered what they described as the "the last
missing royal tomb of the 18th Dynasty." It belonged to Thutmose
II, who is believed to have reigned around 1480 B.C. The Egyptian
officials described the finding as the first excavation of a pharaoh's
tomb since Tutankhamen's burial chamber was unearthed in 1922.
*** archaeologist
*** tomb
*** Egypt
https://en.wikipedia.org/wiki/Egypt?useskin=vector
*** antiquity
https://www.dicts.cn/dictword20181/html/3bfa37a2d6854c03774cd89c74c76b6c.html?antiquity
*** Thutmose II
https://en.wikipedia.org/wiki/Thutmose_II?useskin=vector
*** reign
*** excavation
https://www.dicts.cn/dictword20181/html/44f9545cb2ae962412c865b6bc0bdb9b.html?excavation
*** unearth
https://www.dicts.cn/dictword20181/html/99640a1f16a29e60383d1848fa6ae0d5.html?unearth
** Two
2. The Broccoli family, who've long controlled the
007 franchise, agreed to hand over creative control to a
new joint venture with Amazon MGM Studios. Amazon
will now decide who will play Bond, who will write
the next script and when the film goes into production
—three critical components held up by a yearslong
stalemate.
*** franchise
https://www.dicts.cn/dictword20181/html/19fc5834efb1cbdbfb9dbae0431760c1.html?franchise
*** hand over
*** hold up
*** stalemate
https://www.dicts.cn/dictword20181/html/21b9400777ae09f28cadc5a3cb361abf.html?stalemate
** Three
3. Luigi Mangione, the 26-year-old accused of killing UnitedHealthcare
CEO Brian Thompson, had his first court appearance on Friday since he
was arraigned in December on charges which include murder as an act of
terrorism. Mangione appeared in Manhattan Criminal Court handcuffed
and wearing a bulletproof vest. His lawyer, Karen Friedman Agnifilo,
protested the unfair treatment of her client, who is battling three sets of
criminal charges. Friday morning shares of UnitedHealth Group fell after
reports that the Department of Justice has started investigating the
company's Medicare billing practices.
*** arraign
https://www.dicts.cn/dictword20181/html/269f05d39afb9ae54fc2b6339d819e2e.html?arraign
*** handcuff
https://www.dicts.cn/dictword20181/html/48e4adea7bb174cf290e397efd95ab15.html?handcuff
*** bulletproof
https://www.dicts.cn/dictword20181/html/906e9536aedfd51e936f35d40aa275f5.html?bulletproof
* [[https://www.bilibili.com/video/BV1YwP7egEXi/][读懂英语新闻（第209期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Ukraine agreed to turn over mineral revenue to the U.S. billb
The agreement came under heavy pressure from the Trump
administration. It's unclear what Ukraine will gain from the deal,
the final details of which are not yet public. President Trump had
suggested that the U.S. need not give up anything in exchange for
the mineral revenue. He described it as "payback" for past U.S. aid
to Ukraine during its war against Russia.
*** turn over
https://www.dicts.cn/dictword20181/html/24625630fe25b0342092283690500822.html?turn%20over
*** in exchange for
** Two
2. Trump backed adviser Elon Musk's Saturday email that demanded
millions of federal workers justify what they did last week. Musk had
said that nonresponses would be considered resignations. The email gave
workers until 11:59 p.m. today to respond with a list of their five
accomplishments. Musk is bringing his 2022 Twitter-takeover playbook
to the Department of Government Efficiency, though critics say it doesn't
translate to government. Trump-appointed top officials at several federal
agencies told employees to ignore Elon Musk's demand.
** Three
3. Warren Buffett is still sitting on a huge pile of cash.
His Berkshire Hathaway hoard grew to a record $334.2
billion in the fourth quarter as operating earnings surged
71%. The billionaire's firm has paid Uncle Sam more
than $101 billion in taxes since he took the helm 60 years
ago, more than any other company in history.
*** pile
https://www.dicts.cn/dictword20181/html/0dd4ede3f546816241c651dc44507052.html?pile
*** hoard
https://www.dicts.cn/dictword20181/html/1787e02d20db54a97cd10d18259be049.html?hoard
*** take the helm
* [[https://www.bilibili.com/video/BV1kRP1eqEod/][读懂英语新闻（第203期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. The leaders of Canada and Mexico made last-minute deals with
President Trump to avoid a trade war. Trump postponed tariffs of up
to 25 percent after the leaders said they would do more to block
drugs and migrants. China hit back with new tariffs on US products
and started an antitrust probe into Google in response to Donald
Trump's 10% levies. Beijing also added Calvin Klein owner PVH
and gene sequencing company Illumina to a blacklist of entities.
*** hit back
https://www.collinsdictionary.com/dictionary/english/hit-back
*** probe
https://www.dicts.cn/dictword20181/html/4f595a9232346e4ca5855f3e2b777566.html?probe
** Two
2. Video game executives did not expect The Sims to be a
hit when it was released on this day in 2000. It was a
virtual dollhouse where players could raise families, build
houses and cause disasters. But unlike popular games at
the time, there was no clear objective. Now a quarter
century later, more than 500 million people have played
games in the Sims franchise.
*** franchise
** Three
3. A shooting today at an adult education campus in
central Sweden left at least 10 people dead. The prime
minister called it the worst mass shooting in the country's
history. The suspect was among the dead, officials said.
But the authorities released few other details, including
the person's identity and a possible motive.
*** campus
https://www.dicts.cn/dictword20181/html/e06ab55a7671736469f7e815d5bfa2a8.html?campus
*** suspect
https://www.dicts.cn/dictword20181/html/9abeeab96ad5d9e275c206d799ebf554.html?suspect

* [[https://www.bilibili.com/video/BV13s98Y2EWr/][读懂英语新闻（第210期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. A meeting between Donald Trump and Volodymyr Zelensky descended into
bitter chaos, with Trump saying afterwards that Ukraine's president was "not
ready for peace". Zelensky left the White House early and abandoned a planned
signing of a deal giving America access to Ukraine's rare minerals. In a heated
exchange in the Oval Office, Zelensky sought to explain to Trump that Putin has
repeatedly violated previous agreements. Zelensky said Ukraine would never
accept a simple ceasefire to conclude the war and insisted a mineral deal wasn't
enough to ensure Ukraine's security. Trump said that Zelensky was "in no
position to dictate" to him.
*** descend into
https://www.oxfordlearnersdictionaries.com/definition/english/descend-into?q=descend+into
*** bitter
https://www.dicts.cn/dictword20181/html/c396593a7e951e1c6f8cfb647d2e863e.html?bitter
*** conclude
https://www.dicts.cn/dictword20181/html/8947def3f41dba1100771b96069c5308.html?conclude
*** dictate
https://www.dicts.cn/dictword20181/html/ebaac9822dbbbf240dcad86b94e19a4a.html?dictate
** Two
2. A rural county on the western edge of Texas is the center of the
largest measles outbreak in the U.S. since 2019, with almost 150 cases.
This week, health officials announced that a child died of the disease —
the country's first measles death in a decade. Robert F. Kennedy Jr., the
health secretary, said the situation was "not unusual." Measles
outbreaks do happen every year, but some public health experts argued
that rising vaccine hesitancy was making such events more common
and more dangerous.
*** hesitancy
https://www.dicts.cn/dictword20181/html/c0c1615b1f923a49ed983b8749505d4f.html?hesitancy
** Three
3. Trump Plans Order to Designate English as Official
Language of the U.S.
The order is expected to be largely symbolic but would be
a victory for America's English-only movement, which has
long had ties to efforts to reduce immigration and restrict
bilingual education.

* [[https://www.bilibili.com/video/BV1pX9oYGEmb][读懂英语新闻（第211期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** One
1. Volodymyr Zelensky, Ukraine's president, attempted to
mend relations with America after Donald Trump
suspended military aid to the country. Zelensky seemingly
denied Trump's accusations that Ukraine was not "ready
for peace" and reiterated his offer to strike a minerals deal
with America. Earlier Marco Rubio, America's secretary of
state, said squeezing Ukraine could "get the Russians to a
negotiating table"

*** mend
https://www.dicts.cn/dictword20181/html/d0a320db5e5d545574981b35487c52c2.html?mend
*** accusation
https://www.bing.com/dict/search?q=accusation
*** reiterate
https://www.bing.com/dict/search?q=reiterate&lq=0&pq=&ghsh=0&ghacc=0&ghpl=
*** strike a deal
https://www.bing.com/dict/search?q=strike+a+deal&lq=0&pq=&ghsh=0&ghacc=0&ghpl=
* [[https://www.bilibili.com/video/BV11gRYY2E5D][读懂英语新闻（第212期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** grant
/graent/ n. 拨款

** harassment
/ha'raesmant/ n. 骚扰

** set off
:PROPERTIES:
:ANKI_NOTE_ID: 1741657693321
:END:
引发

** unleash

* [[https://www.bilibili.com/video/BV14NQWYEEkB][读懂英语新闻（第213期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Wall Street is divided whether the Monday market meitdown represents something more than the short-term pain as flagged up increasingly by President Donald Trump's team. The difference this time is that it's hammering the broader market rather than just the megacaps. Tesla was hit more than most on Monday but got a nice vote of confidence from the commander-in-chief. Trump said he's going to buy a new Tesla this morning to support Musk, who confessed to struggling a bit running his business at the same time as doing his DOGE work. His next target: entitlement spending, including Social Security and Medicare.

*** meltdown
https://www.dicts.cn/dictword20181/html/149557d686979c7263fb7fced6e708f7.html?meltdown
*** flag up
https://www.oxfordlearnersdictionaries.com/definition/english/flag-up
*** entitlement
https://www.dicts.cn/dictword20181/html/7bece46303ff0e48aae0f800b5d543ac.html?entitlement
** Two
2. Aviation safety has been in the spotlight since January's tragic midair collision near DCA, with some travelers afraid that flying is suddenly more dangerous, despite contrary data. "I have friends and family [asking], 'Should I get on an airplane?' one retired controller tells Axios. " I'm like: 'Well, it's not there yet.' But it seems to be trending that way."

*** aviation
https://www.dicts.cn/dictword20181/html/7a7cf22660179908b33d97c2e071a0d5.html?aviation
*** spotlight
https://www.dicts.cn/dictword20181/html/27b2e3d5d0517d56780444b689eb54e1.html?spotlight
** Three
3. Federal immigration authorities detained Mahmoud Khalil, who was a prominent pro-Palestinian activist at Columbia University, over the weekend. Khalil is a lawful permanent resident with a green card. However, the Trump administration is seeking to deport him using an obscure legal statute.

*** prominent
https://www.dicts.cn/dictword20181/html/614ae77f26498b707832bb6879b6085e.html?prominent
*** deport
https://www.dicts.cn/dictword20181/html/3258f0e3ce2eb53d024deabb50b2bfdd.html?deport
*** obscure
https://www.dicts.cn/dictword20181/html/579278abd1ee99636b327325b4f28263.html?obscure
* [[https://www.bilibili.com/video/BV1h5QaY5EuJ][读懂英语新闻（第214期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Mark Carney was sworn in as Canada's 24th prime minister, bringing the former central banker to power in the middle of an explosive trade war with the US. The 59-year-old took the oath as Canadà's new leader at a ceremony in Ottawa on Friday, five days after Liberal Party members voted overwhelmingly for him to replace Justin Trudeau as head of the party. In his first news conference as prime minister, Carney told reporters there has been "progress" in discussions with the US, after weeks of tariff hostilities.
*** swear in
https://www.bing.com/dict/search?q=swear+in
*** oath
https://www.dicts.cn/dictword20181/html/2245636238d9d2df37efbe013b11befc.html?oath
** Two
2. A.I. systems are getting better every day Engineers and entrepreneurs in Silicon Valley often talk about the imminent creation of artificial general intelligence, or A.G.I., which is usually defined as something like "a general- purpose A.I. system that can do almost all cognitive tasks a human can do." Elsewhere in the world, many people scoff at the idea. But Sam Altman expresses optimism that we are nearing a breakthrough. He believes that by 2025, machines will think and reason like humans.
*** entrepreneur
https://www.dicts.cn/dictword20181/html/ad6eec7947370a5a1ffa093e1626a75b.html?entrepreneur
*** imminent
https://www.dicts.cn/dictword20181/html/4b55bd6330faec22a34e906b996a2bdb.html?imminent
*** cognitive
https://www.dicts.cn/dictword20181/html/2d446d303459d689644412233e8f7bc4.html?cognitive
*** [#C] scoff
https://www.dicts.cn/dictword20181/html/ad379cbb53c39f4f37b23ba2e69343d1.html?scoff
** Three
1. The Trump administration is considering targeting the citizens of as many as 43 countries as part of a new ban on travel to the United States that would be broader than the restrictions imposed during President Trump's first term, according to officials familiar with the matter.
2. The Panama deal rumbles on. Shares of the conglomerate that sold a controlling stake in Panama ports slumped in Asia after China's top office on Hong Kong affairs reposted a newspaper's sharp attack on the decision. The company, owned by one of Hong Kong's highest-profile billionaires, was guilty of "spineless groveling" and "selling out all Chinese people."

*** rumble on
[[https://www.bing.com/dict/search?q=rumble+on]]
*** highest-profile
https://www.bing.com/dict/search?q=highest-profile&lq=0&pq=&ghsh=0&ghacc=0&ghpl=
* [[https://www.bilibili.com/video/BV1BmQfYiEXe][读懂英语新闻（第215期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. After being stuck in orbit for nine months, NASA astronauts Butch Wilmore and Suni Williams finally departed the International Space Station. The SpaceX capsule is expected to fall to Earth (there will be parachutes), splashing down off the Florida coast around 6 p.m. local time. The lengthy sojourn will have made them taller, weaker and maybe given them vision trouble, according to medical studies of previous astronauts.
*** orbit
https://www.dicts.cn/dictword20181/html/1c9767bfd4acebbc26155c45027ccf96.html?orbit
*** splash down
https://www.bing.com/dict/search?q=splash+down
** Two
2. Chinese automaker BYD unveiled a line-up of electric vehicles that it says can charge almost as fast as it takes to refuel a regular car. The new battery system allows for 400 kilometers of range in just five minutes of charging that's quicker than anything else out there.
*** unveil
https://www.dicts.cn/dictword20181/html/be1afe4f231b2a6882508a731a90977e.html?unveil
** Three
3. Harvard announced today that it plans to offer free tuition for students whose families make $200,000 or less per year. Previously the university — where the annual cost to attend is about $83,000 - had waived tuition for families with incomes under $85,000.The change will make Harvard the latest in a series of elite schools that have expanded financial aid after the Supreme Court banned the use of racial preferences in college admissions.

*** tuition
https://www.dicts.cn/dictword20181/html/4ba6b75ddcf4524008ca7ce16b63f8ea.html?tuition
*** waive
https://www.dicts.cn/dictword20181/html/93863ab0d70ebbb435fe8282f94f4cec.html?waive
* [[https://www.bilibili.com/video/BV1NwozYNEAZ][读懂英语新闻（第216期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Heathrow said it would resume some flights late today, after a power outage closed the London airport for much of the day. Hundreds of flights from around the world were diverted and canceled, leaving thousands of passengers stranded at airports they hadn't intended on visiting. Heathrow expects significant disruption for days. An explosion at an electrical substation a mile and a half away shut down Europe's busiest airport and upended global air travel.
*** Heathrow
https://en.wikipedia.org/wiki/Heathrow_Airport?useskin=vector
*** outage
https://www.dicts.cn/dictword20181/html/b13d548fd07c0780c7dc5c175fcef6be.html?outage
*** much of the day
https://www.bing.com/dict/search?q=much+of+the+day
*** divert
https://www.dicts.cn/dictword20181/html/acaab9e625c28925a707e74460ada8aa.html?divert
*** strand
https://www.dicts.cn/dictword20181/html/4d8441f9199b4ae0a9296268de96540a.html?strand
*** substation
https://www.dicts.cn/dictword20181/html/f84c11f811ad94e707088d2151268dab.html?substation
*** upend
https://www.dicts.cn/dictword20181/html/3ae3f8dda2f3ecf41b1c1486d5f4040e.html?upend
** Two
2. Does anyone enjoy paying property taxes? Probably not. In Florida, as home values and insurance costs rise, a movement is gaining ground to ditch property taxes altogether. State lawmakers have filed dozens of bills on the issue, ranging from an end to property taxes to more targeted tweaks. The Sunshine State would be the first in the nation to eliminate the taxes entirely if it proceeds.
*** gain ground
https://www.bing.com/dict/search?q=gain+ground
*** ditch
https://www.dicts.cn/dictword20181/html/e5593345ab9d11b88b1b02ebf6e398d1.html?ditch
*** tweak
https://www.dicts.cn/dictword20181/html/da47bc7fb9ed3036c13b7b6b16e4c00b.html?tweak
** Three
3. Columbia will cede to President Trump in a battle over more than $400 million in federal funding. The university agreed to ban masks, empower 30 campus police with new powers to arrest students and appoint a senior vice provost to oversee its Middle East studies, among other White House demands. Columbia's acquiescence is a significant moment in the intensifying fight between Trump and elite universities. The president campaigned on curbing what he sees as leftist ideology in higher education and has moved to investigate allegations of campus antisemitism.
*** cede
https://www.dicts.cn/dictword20181/html/22057640398d04206a24c2d39831bd70.html?cede
*** acquiescence
https://www.dicts.cn/dictword20181/html/6bd76c5e5976cfe2d943b03dcc224544.html?acquiescence
*** curb
https://www.dicts.cn/dictword20181/html/5d431c4c9da0db78baed8e747aed99c4.html?curb
* [[https://www.bilibili.com/video/BV1uFZKYnERb][读懂英语新闻（第217期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. After being widely mocked on MAGA media, Disney's live-action "Snow White" remake got off to a rough start. The film - which had a $250 million budget - opened with $43 million in domestic ticket sales, well below expectations. It arrived in theaters "dogged with controversies, including criticism about the film's depiction of the seven dwarves, complaints about changes to the nearly 100-year-old story and calls for boycotts because of co-stars Rachel Zegler and Gal Gadot's public stances on the Israel-Hamas war," Variety notes.

*** mock
https://www.dicts.cn/dictword20181/html/8bdf972695b48db350ab15e395b8d6bb.html?mock
*** get off to a rough start
https://ludwig.guru/s/off+to+a+rough+start
*** dog
[[https://www.bing.com/dict/search?q=dog]]
*** boycott
https://www.dicts.cn/dictword20181/html/0925893610ba1e18664ff3c7e630ff7c.html?boycott
** Two
2. Tesla's headwinds are strengthening protests, slowing sales, and a rough ride in Europe and China. But not everyone's betting against the EV giant. Ark Investment's Cathie Wood is doubling down, predicting Tesla shares will soar to $2,600 in five years, driven by a robotaxi revolution. Elon Musk's fans seem to agree -they're scooping up Tesla shares like never before.

*** headwind
https://www.dicts.cn/dictword20181/html/0807633f0aa3d0e57d1f7622b4ed9b89.html?headwind
*** a rough ride
https://www.bing.com/dict/search?q=a+rough+ride
*** double down
https://www.bing.com/dict/search?q=double+down
*** scoop up
https://www.bing.com/dict/search?q=scoop+up
** Three
3. Defense Secretary Pete Hegseth texted plans for military strikes in Yemen in a Signal group chat with U.S. officials that also inadvertently included the top editor of The Atlantic. The editor said that Michael Waltz, the national security adviser, had added him to the chat by mistake days earlier. Until the strikes, he suspected it to be a hoax. Security experts expressed horror at the inclusion of the magazine editor and the use of a consumer app, warning of dangerous ramifications for US national security.
*** hoax
https://www.dicts.cn/dictword20181/html/9fe0153b91d6b96a918a886bf48b0618.html?hoax
* [[https://www.youtube.com/watch?v=R90KpyjZ-pE][(35) 读懂英语新闻（第218期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Egg prices are finally falling: Inventories are recovering amid a sudden and largely unexplained slowdown in bird flu cases. The average wholesale price of a dozen eggs was $3 yesterday, down 63% from a record $8.15 in the Feb. 21 report. Retail prices, which typically trail wholesale, are beginning to fall as well. Agriculture Secretary Brooke Rollins warned that the Easter season has "the highest price for eggs" and prices could "inch back up." Ironically, as egg prices are coming down, coffee prices are poised to spike by double digits, Reuters reports.

*** inventory
https://www.dicts.cn/dictword20181/html/65cf78ee6cd061e6cba358bf7f4017bb.html?inventory
*** wholesale
https://www.dicts.cn/dictword20181/html/a29a6742384c834398a473df8d85af2a.html?wholesale
*** trail
https://www.dicts.cn/dictword20181/html/6383d722c023427390e43b04fb879233.html?trail
*** Easter season
https://en.wikipedia.org/w/index.php?title=Eastertide&useskin=vector
*** poised to
https://www.bing.com/dict/search?q=poised+to
*** spike
https://www.dicts.cn/dictword20181/html/fcd072aea334ccf51b73150af851b6b4.html?spike
** Two
2. Vice President Vance claimed in a brief Greenland visit yesterday that Denmark had failed to keep Greenland safe, and that President Trump is prepared to make the Arctic island "much more secure" and stronger economically. Trump reiterated his argument before Vance's trip that "we need Greenland," with the added warning that "we'll go as far as we have to go" to get it. But the future Vance seemed to propose was not of U.S. ownership but of an independent Greenland opting into a new security and economic partnership with the U.S.
Greenlanders overwhelmingly reject the notion of joining the U.S.

*** Denmark
https://en.wikipedia.org/wiki/Denmark?useskin=vector
*** arctic
https://www.dicts.cn/dictword20181/html/868e7bff58ebed3284562363fd325eb8.html?arctic
*** reiterate
https://www.dicts.cn/dictword20181/html/1afdcb278d17cf6fec8e9476998ccb22.html?reiterate
** Three
3. A series of earthquakes in Myanmar killed 144 people and injured more than 700 as of Friday evening local time, authorities said. The first was a 7.7-magnitude quake in the early afternoon, according to the U.S. Geological Survey. The death toll is expected to rise. Tremors felt hundreds of miles away collapsed a high-rise building under construction in Bangkok, killing at least three people and injuring dozens, Thai officials said.

*** Myanmar
https://en.wikipedia.org/wiki/Myanmar?useskin=vector
*** magnitude
https://www.dicts.cn/dictword20181/html/7d0a37abeb7081cda32a067c86eebb76.html?magnitude
*** tremor
https://www.dicts.cn/dictword20181/html/1f30455ed3ef68d51bece762910e87f0.html?tremor
*** high-rise
https://www.dicts.cn/dictword20181/html/0ddb66aade4ddc78a58c7d86f845df04.html?high-rise
* [[https://www.bilibili.com/video/BV1fufKYTE2D][读懂英语新闻（第219期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Attorney General Pam Bondi announced today that she would seek the death penalty for Luigi Mangione, who was charged with murdering the health insurance executive Brian Thompson in front of a hotel in midtown Manhattan in December. Mangione, who is 26, has pleaded not guilty. The decision followed an executive order by Trump directing the Justice Department to renew death penalty requests after former President Joe Biden declared a moratorium on capital punishment for most federal offenders in 2021.

*** plead not guilty
https://www.bing.com/dict/search?q=plead+not+guilty
*** moratorium
https://www.dicts.cn/dictword20181/html/416e48d67da472682c95bb327541916b.html?moratorium
*** offender
https://www.dicts.cn/dictword20181/html/6dabb97247329a3d5be1d53e1dfa0dcb.html?offender
** Two
2. Trump confirmed he will hit "all countries" with new tariffs on April 2, calling it "Liberation Day." The White House warned "There are no exemptions at this time," despite pushback from allies and U.S. industries. Trump's tariffs rates, however, reportedly remain undecided with Trump weighing across-the-board hikes up to 20% or "reciprocal" tariffs matched to what each country charges the U.S.

*** pushback
https://www.bing.com/dict/search?q=pushback&lq=0&pq=
*** across-the-board
https://www.bing.com/dict/search?q=across-the-board&lq=0&pq=
*** reciprocal
https://www.dicts.cn/dictword20181/html/2672cbdf2bb3323156febe9d9ac08d96.html?reciprocal
** Three
3. Tinder introduced an in-app game that allows users to flat with artificially intelligent chatbots, aiming to boost user engagement. "The Game Game" uses OpenAI's GPT-40 and GPT-40 mini models to generate romantic comedy scenarios. Still, Tinder isn't going so far as to introduce an Al companion. Other dating apps such as Grindr have also been testing Al- powered features.

*** scenario
https://www.dicts.cn/dictword20181/html/dd8845d438ad923dc0a132762483d2d7.html?scenario
* [[https://www.bilibili.com/video/BV1vzRqYVEaG][读懂英语新闻（第220期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, From friend, to foe, Donald Trump's latest trade salvo impacts just about everyone. Federal Reserve Chairman Jerome Powell warned that price increases and weaker economic growth are more likely than they seemed a few weeks ago as tariffs were raised more than expected. Powell added that it was too early to discuss interest rate adjustments. For now, Americans worried about rising prices are stocking up on televisions, soy sauce and Lululemon gear, while the rest of the world is bracing for an influx of cheap Chinese goods. And people in remote parts of the globe are wondering how they got on the tariff list.

*** foe
https://www.dicts.cn/dictword20181/html/c7ccc89c6168463d363113a921b053cb.html?foe
*** stock up on
https://www.bing.com/dict/search?q=stock+up+on
*** gear
https://www.dicts.cn/dictword20181/html/ad7f2ca3b1355b0b3a264d84b92a5255.html?gear
*** brace
https://www.dicts.cn/dictword20181/html/5f531bd71d97e1446bc4d8c36f6011f9.html?brace
*** influx
https://www.dicts.cn/dictword20181/html/3255933e209b30f377e560298b7d3c26.html?influx
** Two
2. With the historic two-day rout on Thursday and yesterday, the major indexes - the S&P 500, the Nasdaq and the Russell 2000 - are all lower than they were a year ago. The market capitalization of S&P stocks fell by $4 trillion this week. As a result, your 401(k) accounts, your children's 529 college savings and your retirement funds have become "bottomless pits." All three touched all-time highs in the last six months. Now, the tech-heavy Nasdaq and the small-cap Russell are in a "bear market" — 20% off their highs — and poised to fall further. The S&P is down 17.4% from a new record in mid-February.

*** Russell 2000
https://en.wikipedia.org/wiki/Russell_2000_Index?useskin=vector
*** market capitalization
https://www.bing.com/dict/search?q=market+capitalization
*** bottomless pit
https://www.bing.com/dict/search?q=bottomless+pit&lq=0&pq=
*** all-time
https://www.bing.com/dict/search?q=all-time&lq=0&pq=
** Three
3. You make memories as a baby, new research shows. Brain scans helped scientists see how infant and toddler minds work in the first study to observe memory activity while the little ones were awake. When shown images they'd seen before, babies looked at them longer, suggesting that they'd recalled seeing them previously. The research also raises the possibility that infant memories could be unlocked later in life.
*** infant
https://www.dicts.cn/dictword20181/html/c844fbf89dea733bcde9c330eac2f3c9.html?infant
        
* [[https://www.bilibili.com/video/BV12KdNYzEq1][读懂英语新闻（第221期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. The tariffs fight is testing the durability — and compatibility — or the Trump-tech alliance. After all, the top tech companies are taking an absolute beating, with the Magnificent 7 losing more than $1 trillion in the past three trading days alone. There's only a handful of billionaires whose wealth has grown this year, and one of them is Warren Buffett. His net worth has climbed $11.5 billion to $153.5 billion, according to the Bloomberg Billionaires Index. The only other winner in the top 20 is L'Oreal heiress Francoise Bettencourt Meyers.
*** durable
https://www.dicts.cn/dictword20181/html/bd6d5615b2343e0c8757a39192ba5516.html?durable

*** handful
https://www.dicts.cn/dictword20181/html/4cc990869bf1ea540cc19de926e21ad8.html?handful

** Two
2. Wall Street has started speaking out against Trump's tariffs.Ken Griffin, better known outside finance as the man who paid $45 million for a dinosaur, said the latest levies are a "huge policy mistake" and amount to a hefty tax on US families. BlackRock CEO Larry Fink was equally blunt, saying that most business leaders tell him the US is already in a recession. Separately, Trump adviser Elon Musk is leveling veiled critiques at the White House's trade agenda.
*** speak out
https://www.bing.com/dict/search?q=speak+out

*** amount to
https://www.bing.com/dict/search?q=amount+to&lq=0&pq=

*** blunt
https://www.dicts.cn/dictword20181/html/97a1ef127703c2f9ab70acc3cd1bf23e.html?blunt

*** veiled
https://www.dicts.cn/dictword20181/html/a0784b67cf38e7ad279b8b9b03f5e9d2.html?veiled

** Three
3. A new train station appeared overnight It took less than six hours for workers in the Japanese city of Arida to assemble a brand-new, 3D-printed train station. Construction of the minimalist structure began after the last train pulled away at 11:57 p.m. and it ended before the first train arrived at 5:45 a.m. Japanese rail officials said they hoped it would serve as an example for other rural stations.

*** pull away
https://www.bing.com/dict/search?q=pull+away&lq=0&pq=

*** rural
https://www.dicts.cn/dictword20181/html/6e634a155b4d30709f9c14b6b4096c4e.html?rural
* [[https://www.bilibili.com/video/BV1HFd6YhEza][读懂英语新闻（第222期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Boarding passes and flight check-in could soon be obsolete. The International Civil Aviation Organization - the UN body that crafts airline policy and that the FAA takes cues from — is considering the biggest shake-up to air travel in 50 years, The Times of London reports. Under the new rules, passengers will be issued a "journey pass" when they book a flight, which will be continually updated with changes and replace the boarding pass. Passengers also will be able to upload their passports to their phones and skip manual check-in. Airlines will just be notified when they've arrived at the airport via facial recognition scanners. These changes could come in two to three years.

*** take cue from
https://www.bing.com/dict/search?q=take+cue+from
*** shake-up
https://www.dicts.cn/dictword20181/html/23a8ca52b8f9d2992f98d4c3e61cc639.html?shake-up
** Two
2. Billed on Wall Street as so rock-solid safe they're risk-free, US Treasury bonds have long served as first port of call for investors during times of panic. They rallied during the global financial crisis, on 9/11 and even when America's own credit rating was cut. But now, as President Donald Trump unleashes an all-out assault on global trade, their status as the world's safe haven is increasingly coming into question. Yields, especially on longer-term debt, have surged in recent days while the dollar has plunged.

*** port of call
https://www.bing.com/dict/search?q=port+of+call&lq=0&pq=
*** unleash
https://www.dicts.cn/dictword20181/html/72714d535a70bdb2bf92895fcd69abb8.html?unleash
*** all-out
https://www.dicts.cn/dictword20181/html/1ca03f60d5ef10f01dadb1923bfa5199.html?all-out
*** haven
https://www.dicts.cn/dictword20181/html/8859f563ae23fc224ced5e6376455628.html?haven
** Three
3. The world's best golfers are competing this weekend in the Masters Tournament at Augusta National Golf Club in Georgia. It is one of the game's most beloved courses — a serene landscape of perfectly manicured Bermuda grass surrounded by majestic trees and more than 30 varieties of bright azaleas. It is also an allergy nightmare this time of year. Players have tried sunglasses, medication and low-histamine diets to battle the conditions, which a local allergy and rheumatology expert said were "another order of magnitude in Augusta."

*** order of magnitude
https://www.bing.com/dict/search?q=order+of+magnitude&go=Search
* [[https://www.bilibili.com/video/BV1kToTY6E7c][读懂英语新闻（第223期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Unlike Columbia University, Harvard University refused to accept a deal with the Trump administration two weeks after he threatened to halt $9 billion in funding. The university vowed it won't "surrender its independence or its constitutional rights." "Neither Harvard nor any other private university can allow itself to be taken over by the federal government," Harvard's lawyers wrote in a letter Monday to US agencies including the Department of Education.

*** surrender
https://www.dicts.cn/dictword20181/html/d7f1e479bfa8decfba5af520782acb43.html?surrender
*** take over
https://www.bing.com/dict/search?q=take+over
** Two
2. A Pennsylvania man broke into Gov. Josh Shapiro's home and set it on fire while the governor and his family were inside. The suspect, Cody Balmer, told police he intended to kill Shapiro with a hammer. He used gasoline-filled beer bottles to start the fire and fled the scene before turning himself in. Shapiro's family escaped unharmed. Balmer faces multiple charges, including attempted murder and terrorism.
*** set on fire
https://www.bing.com/dict/search?q=set+on+fire&go=Search
*** turn oneself in
https://www.bing.com/dict/search?q=turn+oneself+in
*** attempted murder
https://www.bing.com/dict/search?q=attempted+murder
** Three
3. Judge Scolds Government for Doing 'Nothing' to Retum Deported Man The Trump administration, which admitted to wrongly sending a man to a notorious prison in El Salvador (violating a court order in the process) and declined to try and get him back, on Friday went a step further. Lawyers for Trump, despite an order by the US Supreme Court, refused to tell a federal judge where the man was or what it's doing to get him back.
* [[https://www.bilibili.com/video/BV185Lwz1EUi][读懂英语新闻（第224期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Astronomers Detect a Possible Signature of Life on a Distant Planet
A team of researchers is offering what it contends is the strongest indication yet of extraterrestrial life, not in our solar system but on a massive planet, known as K2-18b, that orbits a star 120 light-years from Earth.
*** contend
https://www.dicts.cn/dictword20181/html/404d1d76cf33a587ac5e33704db3b265.html?contend
*** indication
https://www.dicts.cn/dictword20181/html/bcea8c022d798989497d0a60ef5ef1e1.html?indication
** Two
2. The drugmaker Eli Lilly announced today that it had developed a daily pill that in clinical trials appeared to be as effective in aiding weight loss as blockbuster injectable drugs like Ozempic. Eli Lilly said it would seek approval from the F.D.A. to market the pill as a treatment for obesity later this year and for diabetes early in 2026.
*** obesity
https://www.dicts.cn/dictword20181/html/3eadf91f267164ea2b99c7b7e7e103ff.html?obesity
*** diabetes
https://www.dicts.cn/dictword20181/html/7fe696979c55bf434d839adaa0afcb9b.html?diabetes
** Three
3. According to a recent Wall Street Journal report, Elon Musk is constantly scanning the horizon for new potential mothers for his children, using everything from X interactions and DMs to huge cash incentives to entice would-be incubators, whom he requires to sign legally binding payment agreements with nondisclosure clauses. As a result , Musk has an undisclosed number of children that is likely well above the 14 already publicly known , and he's shown no obvious intention to stop sowing his seed. Musk seems to have reduced traditional family relationships to mere financial arrangements, undermining longtime conservative agreement around the importance of family.
*** incentive
https://www.dicts.cn/dictword20181/html/ec8fc5920012723d70db343d47fff341.html?incentive
*** sow
https://www.dicts.cn/dictword20181/html/c448f63b92d7692963027c56a300fa6f.html?sow
* [[https://www.bilibili.com/video/BV1MML8zWEmi][读懂英语新闻（第225期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Pope Francis, the Catholic church's first Latin American pope, has died at 88. He rose from a humble childhood in Argentina to become the leader of the world's largest and most powerful church. He was hospitalized in mid-February with bronchitis, which progressed to pneumonia in both lungs. The pope will be remembered for encouraging Catholics to embrace a more compassionate view on many issues, while finding it difficult to close the book on past abuses by clergy. On Sunday, he met with Vice President JD Vance and blessed thousands gathered in St. Peter's Square for Easter.

*** pope
https://www.dicts.cn/dictword20181/html/fb4a5760b6058091315a4c28764ab758.html?pope
*** humble
https://www.dicts.cn/dictword20181/html/873c4cb795e590ef48c50be11c18f838.html?humble
*** compassionate
https://www.dicts.cn/dictword20181/html/994c1254e9d477c4f5e5f3b3f748f91a.html?compassionate
*** clergy
https://www.dicts.cn/dictword20181/html/06c3807468cd3574270b28a8de88d0fe.html?clergy
** Two
2. Lawyers for the Justice Department told a judge in a Washington, D.C.. courthouse today that the best way to address Google's monopoly in internet search was to break up the $1.81 trillion company. The government encouraged the judge to force Google to sell its popular Chrome web browser, while Google's lawyers are pushing for far narrower remedies.

*** monopoly
https://www.dicts.cn/dictword20181/html/32ae4a77646f7a0d8c6ab54851cea90c.html?monopoly
*** break up
https://www.bing.com/dict/search?q=break+up
*** remedy
https://www.dicts.cn/dictword20181/html/f63887ba3f5b46fc53c1fbcd9996a565.html?remedy
** Three
3. Pete Hegseth's Pentagon has been overwhelmed by staff drama and turnover, going into a "full-blown meltdown", according to Hegseth's former spokesman. In the latest controversy, the NYT said Hegseth shared sensitive plans about Yemen strikes in a Signal chat with his wife, brother and personal lawyer.

*** meltdown
https://www.dicts.cn/dictword20181/html/149557d686979c7263fb7fced6e708f7.html?meltdown

* [[https://www.youtube.com/watch?v=J5D9SSRsREw][(47) 如何养成好习惯，改掉坏习惯｜英语外刊精读｜词汇量暴涨｜英语阅读｜英语听力｜英文写作｜一起读懂美国新闻｜趣味学英语｜《经济学人》文章精读｜外刊精读第125期 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** trick
https://www.dicts.cn/dictword20181/html/1a41404a12fc8b1229d47776b51207f7.html?trick
** scenery
https://www.dicts.cn/dictword20181/html/8d966d210148079528ec983890d669ed.html?scenery
** rigorous
https://www.dicts.cn/dictword20181/html/4dbe9801722c1708c56ca19aee4d8125.html?rigorous
** dopamine
https://www.dicts.cn/dictword20181/html/4d26d0bc4ac3e7c9b8e3234c057e5465.html?dopamine
** cortex
https://www.dicts.cn/dictword20181/html/98757cbdc03fb96de57b6745b78da920.html?cortex
** cognitive
https://www.dicts.cn/dictword20181/html/2d446d303459d689644412233e8f7bc4.html?cognitive
** work out
https://www.bing.com/dict/search?q=work+out
** subvert
https://www.dicts.cn/dictword20181/html/9cbbe7b905f8f739e41a7a9e2554f917.html?subvert
** addiction
https://www.dicts.cn/dictword20181/html/13dce1ad9383cdb4645d3aa8e55b1aa9.html?addiction
** procrastination
https://www.dicts.cn/dictword20181/html/89effe21a401a9baac5d5c0c290b17ed.html?procrastination
** willpower
https://www.dicts.cn/dictword20181/html/b46ae7c13e4e70678d63abc4ae4802cf.html?willpower
* [[https://www.bilibili.com/video/BV1mCLqzkE44][读懂英语新闻（第226期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. F.B.I. agents arrested a Milwaukee county judge today on charges of obstructing immigration agents. They accused the judge, Hannah Dugan, of guiding an undocumented immigrant through a side door in her courtroom while the agents waited to arrest him in a public hallway. The arrest was a major escalation in the Trump administration's battle with local authorities over deportations. President Trump and his top advisers have repeatedly assailed "local judges" and vowed to prosecute local officials who do not assist federal immigration enforcement efforts.

*** on charge of
https://www.bing.com/dict/search?q=on+charge+of
*** obstruct
https://www.dicts.cn/dictword20181/html/24a69bf3c0ec960424e1571b98c7e005.html?obstruct
*** escalation
https://www.dicts.cn/dictword20181/html/c5d3d17181988eada1f63d8ca7d5fdd6.html?escalation
*** assail
https://www.dicts.cn/dictword20181/html/c82a3e00c3192a0704f2bd4784566274.html?assail
*** prosecute
https://www.dicts.cn/dictword20181/html/d209608ec55e3d7c56185b78da2947c9.html?prosecute
** Two
2. Heads of state and royalty were among the 250,000 people gathered in St. Peter's Square at the Vatican for Pope Francis' funeral this morning. Cardinal Giovanni Battista Re, dean of the College of Cardinals, delivered : spirited and highly personal homily, AP reports. "He was a pope among the people, with an open heart towards everyone," Re said. "The guiding thread of his mission was also the conviction that the church is a home for all, a home with its doors always open." After the service concluded, a motorcade took Pope Francis's body through Rome to the Santa Maria Maggiore Basilica for his final rest.

*** head of state
https://www.bing.com/dict/search?q=head+of+state&lq=0&pq=
*** conviction
https://www.dicts.cn/dictword20181/html/45235565652313b2b6289320d37232d0.html?conviction
** Three
3. Young adults are increasingly taking health decisions into their own hands. 45% of adults ages 18-34 said they've disregarded their health provider's guidance in favor of information from a friend or family member in the past year — a 13-point increase from the previous year. The vast majority of young adults (82%) still said their doctor influences their health decisions. But one-third also reported that content creators without medical training had influenced health decisions.
*** disregard
https://www.dicts.cn/dictword20181/html/8c3f7e04c9b834dca3d407ac585bd7d9.html?disregard
* [[https://www.bilibili.com/video/BV1NUGtzqEAb][读懂英语新闻（第227期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Prime Minister Mark Carney's Liberal Party won Canada's snap federal election, capping a stunning turnaround in fortunes fueled by President Trump's annexation threats and trade war. In a victory speech before supporters in Ottawa, Carney said: "We are over the shock of the American betrayal, but we should never forget the lessons ... As I've been warning for months, America wants our land, our resources, our water, our country."
*** cap
https://www.bing.com/dict/search?q=capping&lq=0&pq=
*** snap
https://www.dicts.cn/dictword20181/html/1b727a48c66f3f1c14132c14cf729adc.html?snap
*** betrayal
https://www.dicts.cn/dictword20181/html/17259be8997f268539d635efbcc7132e.html?betrayal

** Two
2. President Trump signed an executive order on Monday that requires commercial truck drivers in the United States to be proficient in English. The text of the order acknowledges the essential role that truck drivers play in the U.S. economy and the livelihood of American people. "Every day, truckers perform the demanding and dangerous work of transporting the Nation's goods to businesses, customers, and communities safely, reliably, and efficiently," the order said.

*** proficient
https://www.dicts.cn/dictword20181/html/1c42cced0ca718b806fe311b9fdd8995.html?proficient

*** demanding
https://www.dicts.cn/dictword20181/html/806a434de96d22958c34826a2317c878.html?demanding
** Three
3. A set of chemicals found in food packaging, plastics, and lotions and shampoos has been linked to hundreds of thousands of deaths from heart disease, according to a study published Tuesday in the journal eBioMedicine. These chemicals, known as phthalates, were responsible for more than 350,000 deaths worldwide in 2018, researchers found. About 75 percent of the deaths were in Asia, the Middle East and the Pacific - reflecting growing concern about the amount of plastic proliferating in developing countries.

*** proliferate
https://www.dicts.cn/dictword20181/html/c4f3dbe665b404e474f5748025dc8b78.html?proliferate

        
* [[https://www.bilibili.com/video/BV1qtVPzoEJh][读懂英语新闻（第228期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Universal antivenom may grow out of a Wisconsin man From his home in Two Rivers, Wis., Tim Friede has been allowing venomous snakes to bite him — about 200 times over the years. Some venomous snake bites can kill a human within an hour, but Friede survives because, for 18 years, he has injected himself with carefully escalating doses of venom to build his immunity. Now, scientists say that his daredevilry could help to solve a dire global health problem. Venomous snakes kill at least 120,000 people a year, and research on Friede's blood might be able to be used to create an antivenom.

*** grow out of
https://www.bing.com/dict/search?q=grow+out+of&lq=0&pq=

*** immunity
https://www.dicts.cn/dictword20181/html/a4f4c2b28cdea18a31bfe6f5944ab759.html?immunity

*** dire
https://www.dicts.cn/dictword20181/html/4d1d9462edf28818cdb1913026e5ee7d.html?dire

** Two
2. Mark Zuckerberg and Meta are pitching a vision of Al chatbots as an extension of your friend network and a potential solution to the "loneliness epidemic." "The average American has, I think, it's fewer than three friends," Zuckerberg said during a podcast interview Monday. "And the average person has demand for meaningfully more." But where Zuckerberg sees opportunity, critics see alarm bells, especially given Meta's history and business model. "The more time you spend chatting with an Al 'friend,' the more of your personal information you're giving away," Robbie Torney, Common Sense Media's senior director of AI programs, told Axios. "It's about who owns and controls and can use your intimate thoughts and expressions after you share them."

*** pitch
https://www.dicts.cn/dictword20181/html/9bdaccdde8fe1faa1c2e500063dc1608.html?pitch

*** intimate
https://www.dicts.cn/dictword20181/html/71810cf023386b29b9abdf19c1b07182.html?intimate

** Three
3. Trump said today that Harvard would be stripped of its tax-exempt status, doubling down on his threat after the school rejected a list of government demands. "It's what they deserve!" Trump wrote on social media. It's not clear if the I.R.S. will proceed with such a move; federal law prohibits the president from directing the tax agency to investigate specific institutions.

*** strip
https://www.dicts.cn/dictword20181/html/9801b5b7621551b4c765818f00132628.html?strip

*** double down
https://www.bing.com/dict/search?q=double+down

*** IRS
https://en.wikipedia.org/w/index.php?title=Internal_Revenue_Service&useskin=vector
* [[https://www.bilibili.com/video/BV1rtVhzrExr][读懂英语新闻（第229期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Trump ordered federal agencies to rebuild and reopen Alcatraz, the former island prison shut down in 1963 over high costs and failing infrastructure. Alcatraz is currently a federally protected historic site run by the National Park Service, which draws more than 1 million visitors a year as a major San Francisco tourist attraction. "REBUILD, AND OPEN ALCATRAZ," Trump said, claiming it would detain the "most ruthless and violent Offenders" and stand as a symbol of "Law, Order, and JUSTICE." The Bureau of Prisons said it would begin an assessment, despite the island's lack of water, power, and modern utilities.

*** Alcatraz
https://en.wikipedia.org/w/index.php?title=Alcatraz_Island&useskin=vector
*** draw
https://www.dicts.cn/dictword20181/html/ecd0945aec433e9cb67c32aa352cb3b3.html?draw
*** tourist attraction
https://www.bing.com/dict/search?q=tourist+attraction
*** ruthless
https://www.dicts.cn/dictword20181/html/3d56115665ac97cf2b3813cd93daf236.html?ruthless
** Two
2. Warren Buffett changed the way many investors think The idea of "value investing" existed well before Warren Buffett began his career. But no one did it as well, or for as long, as he did. In the process, Buffett, 94, built up a $168 billion fortune and influenced generations of investors, promoting the now-common advice about investing for the long term. This weekend, Buffett, who said "our favorite holding period is forever," announced something that the finance world had been discussing for many years: the "Oracle of Omaha" was stepping down and handing his $1.1 trillion conglomerate to a new leader, Gregory Abel.

*** build up
https://www.bing.com/dict/search?q=build+up
*** oracle
https://www.dicts.cn/dictword20181/html/282cffecb186ad8301f171c4ccf4b3fc.html?oracle
*** step down
https://www.bing.com/dict/search?q=step+down&lq=0&pq=
*** conglomerate
https://www.dicts.cn/dictword20181/html/76f01eb636db07f2f6856052ff539843.html?conglomerate
** Three
3. Canadian Prime Minister Mark Carney, in his first White House meeting with President Trump since becoming leader, reiterated that his country won't be the 51st state. Carney said he plans to recast the economic and security relationship between the countries.

*** recast
https://www.dicts.cn/dictword20181/html/1a29e10210eed86e43c635bda9e435b4.html?recast
* [[https://www.bilibili.com/video/BV1uiEgz5EoL][读懂英语新闻（第230期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Bill Gates is planning to wind down his foundation The Gates Foundation, one of the world's most consequential global-health philanthropies, celebrated its 25th anniversary today by announcing its plans to close up shop. Bill Gates said the foundation would accelerate the pace of its aid spending over the next 20 years — giving away at least $200 billion - before ending his initiative decades earlier than he originally planned.

*** wind down
https://www.collinsdictionary.com/dictionary/english/wind-down
*** close up shop
https://dictionary.cambridge.org/dictionary/english/close-up-shop

** Two
2. Nuclear-armed neighbours India and Pakistan agreed to a ceasefire on Saturday after U.S. pressure and diplomacy, but within hours, blasts were reported from the main cities of Indian Kashmir, the centre of four days of fighting. The fighting had been the worst between the old South Asian enemies in nearly three decades and threatened to erupt into a full-scale war in one of the world's most volatile and densely populated regions.

*** blast
https://www.dicts.cn/dictword20181/html/cbd0ab64a9c11d79df23276b578d94a5.html?blast

*** Kashmir
:LOGBOOK:
- Note taken on [2025-05-12 Mon 09:48] \\
  由中国、印度与巴基斯坦三个国家管理
:END:
https://en.wikipedia.org/wiki/Kashmir?useskin=vector

*** volatile
https://www.dicts.cn/dictword20181/html/c184edbe3efd87c4456c4ffcbd932125.html?volatile

** Three
3. President Trump suggested this morning that he was open to sharply reducing the tariffs on imports from China. Trump said that an 80 percent tariff on China "seems right," adding that it would be "up to" Treasury Secretary Scott Bessent, who is set to meet this weekend with Chinese negotiators. Chinese shipments to the U.S. have plunged 21 percent from a year earlier.

*** plunge
https://www.dicts.cn/dictword20181/html/9b14e4ff1740dfe1792b969392cd5dd2.html?plunge
* [[https://www.bilibili.com/video/BV1jhEqzaEMS][读懂英语新闻（第231期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, China reopened itself to Boeing, the biggest U.S. exporter, after the two countries reached a temporary truce in their trade war. Beijing told Chinese airlines that they can take delivery on pre-existing Boeing jet orders, according to people familiar with the situation. Meanwhile, the Trump administration said it would cut tariffs on low-value parcels from China to 54% from 120%.

*** truce
https://www.dicts.cn/dictword20181/html/a712d4b6d5292822da987c3a6840425e.html?truce

*** parcel
https://www.dicts.cn/dictword20181/html/a25a4021222d90ede3546f0c6c730ff7.html?parcel

** Two
2. California Governor Gavin Newsom called on cities in his state to ban and remove homeless encampments from sidewalks, bike paths and other public property, ratcheting up his effort to tackle the crisis.

*** call on
https://www.bing.com/dict/search?q=call%20on

*** ratchet up
https://www.bing.com/dict/search?q=ratchet+up&lq=0&pq=ratchet+up

** Three
3. President Trump kicked off his Middle East tour by nixing sanctions on. Syria, signing investment deals with Saudi Arabia and issuing an ultimatum to Iran. Trump also plans to accept a luxury Boeing 747-8 jet from Qatar's royal family for use as Air Force One - a move that follows the Trump Organization's deal to build a $5.5 billion golf resort in Qatar. The jet, valued at roughly $400 million, would be used by Trump while in office, then transferred to his presidential library. Despite the Constitution's emoluments clause, which bars gifts from foreign governments without congressional approval, Trump called it a "great gesture" and said turning down the offer would be "stupid."

*** kick off
https://www.bing.com/dict/search?q=Kick+Off&qs=n&form=Z9LH5&sp=-1&lq=0&pq=kick+off&sc=3-8&sk=&cvid=026F32E57DD04BBB9FC6C5A1EE01AD19

*** ultimatum
https://www.dicts.cn/dictword20181/html/ae2220a2ed64bf105f4f40716e5d3653.html?ultimatum

*** resort
https://www.dicts.cn/dictword20181/html/ba8a010fcd4958736733dacf330e2579.html?resort

*** bar
https://www.dicts.cn/dictword20181/html/de1f3011fd620acb0252c9fed1a3a8c7.html?bar

*** turn down
https://www.bing.com/dict/search?q=turn%20down
* [[https://www.bilibili.com/video/BV1sEJVzjEd3][读懂英语新闻（第232期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-05-20 Tue 09:46] \\
  [[https://www.youtube.com/watch?v=VjLjNLeNEjI][听力训练]]
:END:
** One
1. Walmart plans to raise prices this month and early this summer, when tariff-affected merchandise hits its store shelves. Some prices already have increased, the retail giant said. The duties' full impact hasn't hit yet partly due to stockpiling and postponed shipments from China. Shares of Walmart closed down 0.5%. Separately, the Fed is adjusting its policy framework to account for meaningful changes in the outlook for inflation and interest rates postpandemic, Chair Jerome Powell said. Investors are increasingly confident that trade tensions will ease and the U.S. economy will prove resilient.

*** stockpiling
https://www.dicts.cn/dictword20181/html/119ba8e06ee24b9980cca3a358729b18.html?stockpiling
*** account for
https://www.bing.com/dict/search?q=account%20for
*** ease
https://www.dicts.cn/dictword20181/html/7815da847a5769d678c2da4072220f06.html?ease
*** resilient
https://www.dicts.cn/dictword20181/html/0c9457f4bb5b1655115920098e1ae3f4.html?resilient
** Two
2. A financial reckoning has started at universities as Trump's funding cuts hit home. Schools such as Harvard, Columbia, Princeton and Michigan State are limiting their spending everything from research pauses and hiring freezes to eliminating desk phones and coffee in the faculty lounge. So far, the undergraduate experience hasn't changed at most universities, but cuts in the coming months could have a significant impact by fall. But prestigeat least at Harvard Business School-remains intact. Speaking to students there is on A-list celebrities' bucket lists, and their teams are inundating HBS with invitation requests.

*** prestige
https://www.dicts.cn/dictword20181/html/24a54bcd20d24b931ae731fefc970384.html?prestige
*** intact
https://www.dicts.cn/dictword20181/html/db64717ce0bdf601d324c343baa49d11.html?intact
*** A-list
https://www.bing.com/dict/search?q=A-list
*** bucket list
https://www.bing.com/dict/search?q=bucket+list&qs=n&form=Z9LH5&sp=-1&lq=0&pq=bucket+list&sc=0-11&sk=&cvid=B5901920B2DA4080BB9BCF140989C25D
** Three
3. The Pope Grew Up in This House. Now, It Could Be Yours. Pope Leo's childhood home will be sold to the highest bidder in an online auction. A house flipper bought it before Leo became pope and is expected to make a windfall. The same auction house that sold President Trump's childhood home for millions in 2017 will take bids for the modest three-bedroom where Pope Leo XIV once lived.

*** flipper
https://www.dicts.cn/dictword20181/html/ccda328d5e4e1cd60169b25170a972d7.html?flipper
*** auction
https://www.dicts.cn/dictword20181/html/da8dbec9863e989aa36bb37f09100655.html?auction
*** windfall
https://www.dicts.cn/dictword20181/html/4db909f14e81c33dac5d809701ed7835.html?windfall
* [[https://www.bilibili.com/video/BV1zBJ6z7ERN][读懂英语新闻（第233期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Joe Biden was diagnosed with an aggressive fom.
of prostate cancer that has spread to his bones, his office
announced. The former president, 82, is reviewing
treatment options with his medical team. Prostate cancer
is among the most common cancers in men, especially as
they age, but survival rates have improved over the past
few decades.

*** diagnose
https://www.dicts.cn/dictword20181/html/4718b488b7bf7a53ed024c309fd80c7b.html?diagnose
*** prostate
https://www.dicts.cn/dictword20181/html/748c546d6c20680cfe04675146b65774.html?prostate
*** survival rate
https://www.bing.com/dict/search?q=survival%20rate
** Two
2. The F.D.A. is poised to restrict access to Covid vaccines 2*8 bilbi
The Food and Drug Administration's new leaders announced today that
the U.S. might require additional research before approving this year's
Covid vaccines for healthy Americans younger than 65. The agency will
still permit adults over 65 and those with a long list of medical conditions
to get the shots in the fall. However, the F.D.A.'s Trump-appointed leaders
said, the additional doses offer "uncertain" benefits to many young and
middle-aged people who have been vaccinated or have had the virus.

** Three
3. Trump abandoned his pledge to broker an immediate
ceasefire between Russia-Ukraine after a two-hour call with
Putin. Instead, Trump said Russia and Ukraine should negotiate
directly without U.S. involvement, backing away from his
earlier threats of sanctions. Trump called the conversation with
Putin "excellent" and said talks would begin "immediately,
suggesting the Vatican as a host.

*** broker
https://www.dicts.cn/dictword20181/html/f9f7e3234c205ab0e2874dd07c3bd46d.html?broker
*** Vatican
https://en.wikipedia.org/wiki/Vatican_City?useskin=vector
* [[https://www.bilibili.com/video/BV11Sj3ziEWc][读懂英语新闻（第234期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. A federal judge temporarily blocked the government's bid to prevent Harvard from enrolling international students. The Trump administration had revoked the university's authorization to admit the students, and Harvard sued earlier today to block the move. Harvard has about 7,000 international students- more than 25% of the student body-and relies on their tuition payments, which are often full-fee. The government previously pulled billions of dollars of the university's research funding and threatened to revoke its tax exempt status, citing concerns about antisemitism and DEI.

*** enroll
https://www.dicts.cn/dictword20181/html/364105bf289a953e6dbbe7aac726f777.html?enroll
*** revoke
https://www.dicts.cn/dictword20181/html/a7e563aa4ca507e84869cdc518f4e55b.html?revoke
*** pull
https://www.dicts.cn/dictword20181/html/2ae016aa93638fa1068d65834ac5a75f.html?pull
** Two
2. It was a big week for testy exchanges. When South African President Cyril Ramaphosa sat down with Donald Trump on Wednesday, the US president upbraided Ramaphosa over claims of genocide against White Afrikaner farmers — a widely debunked accusation that the US has used to justify ceasing most aid to the country. It was the latest in a series of broadsides and reneged pledges that are fostering ill will toward the US across African countries.

*** justify
https://www.dicts.cn/dictword20181/html/32835b57bd9d6a6430c6a07aa1cb84f5.html?justify
*** foster
https://www.dicts.cn/dictword20181/html/735dcc9b4a55a8a561fbbe5489b0884f.html?foster
** Three
3. In theaters across the country this weekend, Tom Cruise is reprising his role as Ethan Hunt, the American operative extraordinaire, in the eighth installment of "Mission: Impossible." The new film, apparently Cruise's last in the series, is enjoyably unhinged, our critic wrote. The movie star is also reprising his role as Hollywood's most enthusiastic evangelist of moviegoing. Cruise reached out directly to the C.E.O. of IMAX — the large-format technology that's been a recent industry bright spot — to ensure that the company's giant screens would exclusively show his new blockbuster.

*** installment
https://www.dicts.cn/dictword20181/html/41e47973ac40eefb529a35547b9c096c.html?installment
*** evangelist
https://www.dicts.cn/dictword20181/html/108085ecf045563edef75a24b71ff986.html?evangelist
*** exclusively
https://www.dicts.cn/dictword20181/html/277e8094e1100601f8bca7cb55b3a511.html?exclusively
*** blockbuster
https://www.bing.com/dict/search?q=blockbuster&FORM=HDRSC6
* [[https://www.bilibili.com/video/BV1jfjzzPERb][读懂英语新闻（第235期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. French President Emmanuel Macron played down a video of his wife, Brigitte, shoving him before they stepped off their plane in Vietnam over the weekend. "We are squabbling and, rather, joking with my wife," he said, adding that the incident was being overblown into "a sort of geo-planetary catastrophe."

*** play down
https://www.bing.com/dict/search?q=play%20down
*** shove
https://www.dicts.cn/dictword20181/html/fc0714b7705e706ad406a76c01195d49.html?shove
*** step off
https://www.bing.com/dict/search?q=step%20off
*** squabble
https://www.dicts.cn/dictword20181/html/37c02179b3d1dfd1a27a1a6499324f97.html?squabble
*** overblow
https://www.bing.com/dict/search?q=overblow&qs=n&form=Z9LH5&sp=-1&lq=0&pq=overblow&sc=0-8&sk=&cvid=03557CE405354562A712A6B8C5DB6EDD
*** catastrophe
https://www.dicts.cn/dictword20181/html/58586940703b0a51cb174e15d2fb70ad.html?catastrophe
** Two
2. A third arrest in a Bitcoin kidnapping case
A third person was arrested today in New York City for kidnapping a man and torturing him for nearly three weeks to steal his cryptocurrency fortune. The case burst into view last week when the victim escaped from a lavish townhouse in the NoLIta neighborhood of Manhattan, where his captors had demanded that he hand over the password to a Bitcoin wallet worth millions.

*** kidnap
https://www.dicts.cn/dictword20181/html/bb4ddf1fb3e515f688730100852551c3.html?kidnap
*** burst into
https://www.bing.com/dict/search?q=burst+into&qs=n&form=Z9LH5&sp=-1&lq=0&pq=burst+into&sc=0-10&sk=&cvid=2233278B90394FD8AD26824B180A7E85
*** lavish
https://www.dicts.cn/dictword20181/html/07a5a1b784935d9975807c4e769f5550.html?lavish
*** captor
https://www.dicts.cn/dictword20181/html/a29688b344e05391aca10aa016326ae5.html?captor
*** hand over
https://www.bing.com/dict/search?q=hand+over&qs=n&form=Z9LH5&sp=-1&lq=0&pq=hand+over&sc=0-9&sk=&cvid=E90F0D4DD851426DA432A9A10C47A594
** Three
3. The Trump administration reportedly told American embassies to stop scheduling student-visa appointments so that it could prepare for "an expansion" of applicants' social-media vetting requirements. Meanwhile, Trump moved to sever all government ties with Harvard. A Trump-appointed official wrote a letter to federal agencies announcing that the government would cancel its remaining $100 million worth of federal contracts with Harvard. Trump officials have cast the campaign as a battle for civil rights against a school that they have accused of liberal bias. Harvard has described the fight as one over its First Amendment rights.

*** embassy
https://www.dicts.cn/dictword20181/html/95be45f6d499915d959a17cb0e94a288.html?embassy
*** sever
https://www.dicts.cn/dictword20181/html/168142f6310a85af90b2663b279aa13b.html?sever
*** cast
https://www.dicts.cn/dictword20181/html/2db895f5546b98ced6a818a7f072c273.html?cast
* [[https://www.bilibili.com/video/BV1bK7kzcEko][读懂英语新闻（第236期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-04 Wed 09:38] \\
  [[https://www.youtube.com/watch?v=cQZqSQA5EiI][(3) 看美剧练听力（第236期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第236期新闻精读配套听力练习 - YouTube]]
:END:
** One
1. Succession creator Jesse Armstrong returns to HBO with Mountainhead, a scathing satire of tech billionaires set in an Utah compound. It's a timely film about the dangers of Al, the world falling apart and powerful men who care only about their own portfolios. While it doesn't have the same depth, Armstrong's hallmarks are still present: a brutal sense of interpersonal power dynamics, a flair for creative profanity and an abiding belief that the worst people will succeed.

*** portfolio
https://www.dicts.cn/dictword20181/html/dc2e4131929aeca25729778f8d3ff368.html?portfolio
*** hallmark
https://www.dicts.cn/dictword20181/html/89e66d176e1691db9f56f676b11c36eb.html?hallmark
*** brutal
https://www.dicts.cn/dictword20181/html/8a5879fde2e23b105c55bd3056129437.html?brutal
*** abiding
https://www.dicts.cn/dictword20181/html/588f4eb2683d497acd4abe79aaa2f3ae.html?abiding
** Two
2. Babies don't need Mozart recordings— just a parent who sings.
The salutary effect of music on infants is more about happiness than smarts. A new study found that it can help if you create the tunes with your own vocal cords. No need for moms and dads to worry if they don't sound like the Mamas and the Papas: Even folk songs do the trick, according to researchers.

*** salutary
https://www.dicts.cn/dictword20181/html/8e3b597e53c0214cc7a2a8ae32beec3d.html?salutary
*** tune
https://www.dicts.cn/dictword20181/html/4d9fcfec31cf339ceb40e4f45d903a7f.html?tune
*** do the trick
https://www.bing.com/dict/search?q=do+the+trick
*** folk
https://www.dicts.cn/dictword20181/html/d1886e9717e539c59ae36cb69a2a63f8.html?folk
** Three
3. The administration says it wants fewer Chinese students in the United States. What will revoking many of their visas mean? Of the 1.1 million international students in the U.S. during the 2023-24 academic year, some 277,000 were from China. The most educated Chinese students stay in the U.S. after graduation. One study found that 90 percent of Chinese graduates of Ph.D. programs in science and tech fields from 2000 to 2015 were still in the country in 2017.The administration's threats to revoke student visas are part of a broader effort to decouple the United States from China.

*** decouple
https://www.dicts.cn/dictword20181/html/6e96b7e9d42bf79612d32cbb0d264ad1.html?decouple
* [[https://www.bilibili.com/video/BV1SfTEzgE1j][读懂英语新闻（第237期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Turning the tide on cancer. Immunotherapy treatments are making strides against early and mid-stage cancers like gastric, colon, and head and neck, as well as advanced conditions. New trials show that drugs such as Opdivo, Imfinzi and Tecentriq are effective at reducing the risk of cancer recurrence and boosting survival rates, according to the American Society of Clinical Oncology.

*** tide
https://www.dicts.cn/dictword20181/html/a3997ac48897e0ca261806d5b4b56471.html?tide
*** stride
https://www.dicts.cn/dictword20181/html/5cbec875810736cd3899f9d9d00f5baa.html?stride
*** gastric
https://www.dicts.cn/dictword20181/html/b4ed3b53b455a74a16946bbe30787348.html?gastric
*** Oncology
https://www.dicts.cn/dictword20181/html/19f85f536cea4309edf073207bba1bea.html?oncology
** Two
2. Ukraine has detonated a massive underwater blast targeting the key road and rail bridge connecting the Russian-occupied Crimean peninsula to Russia, damaging its underwater supports. The operation, for which Kyiv's SBU security service claimed responsibility, is the second high-profile operation by Ukraine in days striking significant Russian assets after a sophisticated drone raid on Moscow's strategic bomber fleet on Sunday.

*** detonate
https://www.dicts.cn/dictword20181/html/a72d6829f2ef41af14d64d219b9b0208.html?detonate
*** peninsula
https://www.dicts.cn/dictword20181/html/35acdb5701f6e01948b4be91fa53b8e4.html?peninsula
*** high-profile
https://www.bing.com/dict/search?q=high-profile
** Three
3. South Korea's opposition candidate Lee Jae-myung was elected president. With almost 95% of the ballots counted, Lee, a left-leaning former labor activist, had won 48.8% of the vote while the ruling People Power Party's candidate Kim Moon-soo had 42.0%, according to the National Election Commission. The election is expected to mark a turning point for South Korea after six months of chaos following ousted leader Yoon Suk Yeol's botched attempt to revive martial law.

*** oust
https://www.bing.com/dict/search?q=oust
*** martial
https://www.dicts.cn/dictword20181/html/39b810aae888633550fc5da73d7ec0db.html?martial
* [[https://www.bilibili.com/video/BV14hTRzKEW2][读懂英语新闻（第238期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-10 Tue 09:19] \\
  [[https://www.youtube.com/watch?v=7ChUz7mSOCA][(6) 看美剧练听力（第238期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第238期新闻精读配套听力练习 - YouTube]]
:END:
** One
1. Long-simmering tensions between President Trump and Elon Musk burst into the open. They traded barbs and insults, signaling the disintegration of a relationship that had been one of the most consequential in modern U.S. politics. The president threatened to eliminate government subsidies and contracts for Musk's businesses, while the Tesla CEO called Trump "ungrateful" after his support during the 2024 campaign. Musk floated the idea of starting a third political party and agreed with a tweet that Trump should be impeached. Tesla's market value declined around $152.4 billion, its biggest one-day slide on record.

*** insult
https://www.dicts.cn/dictword20181/html/f86496e668a2c3ee7572fd696e152441.html?insult
*** disintegration
https://www.dicts.cn/dictword20181/html/4cd5d8dec2897b9126864d99595abe0e.html?disintegration
*** float
https://www.dicts.cn/dictword20181/html/8b77109b8810c1f7e4a338c4f74c510f.html?float
*** impeach
https://www.dicts.cn/dictword20181/html/740c306eea2ea580c052195f512b979e.html?impeach
** Two
2. An investigation into Kentucky's organ donor system found flaws
Four years ago, an unconscious Kentucky man began to awaken as he was about to be removed from life support so his organs could be donated. Even though the man cried, pulled his legs to his chest and shook his head, officials still tried to move forward. That man, Anthony Hoover, is still alive. His case spurred an investigation, which found that officials at the nonprofit in charge of coordinating the state's organ donations ignored signs of growing alertness in him and dozens of other potential donors.

*** spur
https://www.dicts.cn/dictword20181/html/b8cbed82cfee0838b10a8cdae6661f9b.html?spur
*** in charge of
https://www.bing.com/dict/search?q=in+charge+of
** Three
3. Trump banned individuals from 12 countries from entering the US, reinstating one of the most controversial measures from his first term. It also partially limits entry by people from seven nations including Cuba and Laos. He also signed an executive action that prevents foreign nationals from entering the US to study at Harvard. That may let his administration sidestep a ruling that allowed the university to temporarily continue enrolling students.

*** reinstate
https://www.dicts.cn/dictword20181/html/f3096fc38d0d1395ba3b8c79f94fd5c1.html?reinstate
*** sidestep
https://www.dicts.cn/dictword20181/html/eceea88f3a73cd22b701884412fcbc1a.html?sidestep
* [[https://www.bilibili.com/video/BV1oJMHztEEN][读懂英语新闻（第239期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-13 Fri 09:19] \\
  [[https://www.youtube.com/watch?v=YbHqYyZ-XUY][(8) 一周听力合集（第238期+第239期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第239期新闻精读配套听力练习 - YouTube]]
:END:
** One
1. California officials insisted they could maintain order in the L.A. protests and blamed federal immigration raids and military deployments for raising tensions. They urged a judge to block the National Guard or Marines from being used for law enforcement. Trump has defended his decision to send the troops to L.A. after demonstrations turned violent. More than 100 people were arrested during the latest protests, which lasted into early this morning, nearly all for failure to disperse, the LAPD said. The demonstrations followed a crackdown on L.A. migrants, sparked by instructions from Trump adviser Stephen Miller: "Just go out there and arrest illegal aliens.

*** demonstration
https://www.dicts.cn/dictword20181/html/220e892807c46e1469ac26240225362b.html?demonstration
*** disperse
https://www.dicts.cn/dictword20181/html/d10bcd8f027455442f32fac8f1b60cca.html?disperse
*** spark
https://www.dicts.cn/dictword20181/html/e53dd40494a7b790eb0a7e4d240fd930.html?spark
** Two
2. The S&P 500 notched a sixth gain in seven sessions after signs of progress in the U.S.-China trade talks in London. The broad index hit session highs. Traders have been optimistic that a deal is coming, until proven otherwise. Commerce Secretary Howard Lutnick said the talks are "going really, really well." Also supporting shares was a survey showing U.S. small businesses grew more optimistic last month.

*** notch
https://www.bing.com/dict/search?q=notch
** Three
3. Trump is warning Musk to stay out of the midterm elections. Some Democrats have suggested that they try to win Elon Musk over to their side after the billionaire's epic falling out with the president. Asked by NBC News this weekend if he was concerned that his former ally could start funding Democratic candidates, Trump said "he'll have to pay very serious consequences if he does that." Meanwhile, in the aftermath of the Trump-Musk breakup, DOGE staffers worry the government-cutting effort-and their jobs could be in jeopardy.

*** stay out of
https://www.bing.com/dict/search?q=stay%20out%20of
*** win over
https://www.bing.com/dict/search?q=win+over&qs=n&form=Z9LH5&sp=-1&lq=0&pq=notch&sc=0-5&sk=&cvid=338D7A6E877F4816B3C66BE8A76E4A27

I'll win her over.
*** fall out
https://www.bing.com/dict/search?q=fall+out&qs=n&form=Z9LH5&sp=-1&lq=0&pq=fall+out&sc=0-8&sk=&cvid=B3ACE2A31867460286238371AA2744D4
*** aftermath
https://www.dicts.cn/dictword20181/html/5654743e4ccb3faa84b295a6ad1bde7b.html?aftermath
*** jeopardy
https://www.dicts.cn/dictword20181/html/297a5ac03e43b93c0d7cba39d778802f.html?jeopardy

* [[https://www.bilibili.com/video/BV1UDM8zuEZa][读懂英语新闻（第240期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-17 Tue 09:21] \\
  https://www.youtube.com/watch?v=3dwSBCgM5y8
:END:
** One
1. Israel launched a major attack on Iran. The strikes killed Iran's top three generals, according to Iranian state media, and targeted military bases and nuclear sites across the country. Tehran launched drones at Israel in response. Israel described the strikes as a last resort to keep Iran from acquiring nuclear weapons. Its military said it struck Natanz, Iran's main nuclear enrichment facility. Israel also killed top Iranian generals and scientists. In the hours before and after the strike, the Trump administration distanced itself from the Israeli operation in public statements and private messages to allies.

*** major
:LOGBOOK:
- Note taken on [2025-06-16 Mon 09:59] \\
  https://github.com/peng051410/today_i_learn/issues/236
:END:
https://www.dicts.cn/dictword20181/html/5d612bbee634d9ce32dd899d8d324bc6.html?major
*** target
:LOGBOOK:
- Note taken on [2025-06-16 Mon 10:00] \\
  https://github.com/peng051410/today_i_learn/issues/237
:END:
https://www.dicts.cn/dictword20181/html/eea34adc1a61363f0bc397782412f2b7.html?target
*** resort
:LOGBOOK:
- Note taken on [2025-06-16 Mon 10:00] \\
  https://github.com/peng051410/today_i_learn/issues/238
:END:
https://www.dicts.cn/dictword20181/html/ba8a010fcd4958736733dacf330e2579.html?resort
*** enrichment
https://www.dicts.cn/dictword20181/html/bdb52c704297a602c043d3aaf9aea960.html?enrichment
** Two
2. Washington prepares for a major military parade Some roads near the National Mall were closed today in anticipation of a parade to celebrate the Army's 250th birthday. Thousands of soldiers in uniforms representing conflicts from the Revolutionary War to today's will march in formation through the nation's capital, accompanied by tanks, helicopters and marching bands. It's the kind of event that Trump has fantasized about since his first term. (It also happens to be on his 79th birthday.) Opponents of Trump have organized "No Kings" protests nationwide to coincide with his parade in Washington tomorrow. Trump has bristled: "I don't feel like a king, I have to go through hell to get stuff approved," he said.

*** parade
https://www.dicts.cn/dictword20181/html/f07b532eadb7c2a12c36087a071bb9c3.html?parade
*** in anticipation of
https://www.bing.com/dict/search?q=in+anticipation+of&lq=0&pq=
*** march
https://www.dicts.cn/dictword20181/html/83b254dc4db7cb8204f5087190beb645.html?march
*** formation
https://www.dicts.cn/dictword20181/html/920e45deb34ab2bdb8b35c0f3dc99175.html?formation
*** helicopter
https://www.dicts.cn/dictword20181/html/fb8fa65fdf965cbb8c53c28405123212.html?helicopter
*** marching band
https://en.wikipedia.org/wiki/Marching_band?useskin=vector
*** fantasize
https://www.dicts.cn/dictword20181/html/e6478c63e45996aef9e18c60820a5698.html?fantasize
*** coincide
https://www.dicts.cn/dictword20181/html/b8a98eae342ca91a9fe505d6c00b59d4.html?coincide
*** bristle
https://www.dicts.cn/dictword20181/html/6b1d17163c1f0a1d2089b8d24603e73b.html?bristle
** Three
3. The miracle of Seat 11A. Ramesh Vishwaskumar, a 40- year-old UK citizen, tells the tale of how he was the sole survivor of Air India Flight AIl71. Seated in the first row of economy class, he managed to escape through a broken door on his side of the plane. The crash killed 241 passengers in the deadliest aviation accident in over a decade.

*** miracle
https://www.dicts.cn/dictword20181/html/36be27ae9b82d8a7c24e6d4cfa409642.html?miracle
*** tale
https://www.dicts.cn/dictword20181/html/b08eccf9ce7502cf3bbf00a3598efb09.html?tale
*** manage to
:LOGBOOK:
- Note taken on [2025-06-17 Tue 09:49] \\
  Seemingly simple, but give it a complex concept, achievement " cut ceaseless, manage to return chaos" .
:END:
https://www.bing.com/dict/search?q=manage+to
* [[https://www.bilibili.com/video/BV1AwNHzFEAb][读懂英语新闻（第241期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-20 Fri 09:46] \\
  [[https://www.youtube.com/watch?v=DX2XJB1JsZM][(10) 一周听力合集（第241期+第240期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第241期新闻精读配套听力练习 - YouTube]]
- Note taken on [2025-06-19 Thu 09:32] \\
  [[https://www.bilibili.com/video/BV1AwNHzFEAb/?share_source=copy_web&vd_source=dd4b143e9184c5bca09b19c03cacb5e5&t=487][单词回顾]]
:END:
** One
1. President Trump raised the possibility of killing Iran's supreme
leader, demanded Iran's "unconditional surrender" and said he was no
longer in the mood to negotiate in the hours before meeting today with
his national security staff. The president, who has long professed
opposition to getting involved in foreign wars, has shifted his position
since Israel attacked Iran five days ago. After first calling for peace, he
is now seriously considering sending in American aircraft to help refuel
Israeli combat jets and to try to take out Iran's nuclear site deep
underground at Fordo with 30,000-pound bombs.

*** raise
https://www.dicts.cn/dictword20181/html/414408a2e72c24acdd6ced10c9c2c7b7.html?raise
*** profess
https://www.dicts.cn/dictword20181/html/6e722781592a70e8fef823354ddf63f1.html?profess
*** call for
https://www.bing.com/dict/search?q=call+for&lq=0&pq=
*** take out
https://www.bing.com/dict/search?q=take+out&qs=n&form=Z9LH5&sp=-1&lq=0&pq=take+out&sc=0-8&sk=&cvid=3596607982814B6E8313658F87822C2D
** Two
2. The man accused of assassinating a Minnesota state lawmaker
and her husband, as well as of shooting another lawmaker and his
wife, was charged with murder. "This was a political assassination,
which is not a word we use very often in the United States," a federal
prosecutor said. He added that the suspect had been planning the
attacks for "at least months," and that all of the targeted officials
were Democrats.

*** assassinate
https://www.dicts.cn/dictword20181/html/b3c5add715323ea72871b55e6b0010ad.html?assassinate
*** prosecutor
https://www.dicts.cn/dictword20181/html/31c70222fa13dbc17000c6c324ddd220.html?prosecutor
** Three
3. As winters get warmer, ticks of several kinds are
flourishing. Deer ticks, known for transmitting Lyme
disease, are moving farther north; the longhorned tick
has gained a foothold on the East Coast; and the lone
star tick, which can make people allergic to red meat,
is fanning out from the South.

*** tick
https://en.wikipedia.org/wiki/Tick?useskin=vector
*** flourish
https://www.dicts.cn/dictword20181/html/4c8babb56465b53834db8ebb55e45519.html?flourish
*** Lyme
https://en.wikipedia.org/wiki/Lyme_disease?useskin=vector
*** gain a foothold
https://www.bing.com/dict/search?q=gain%20a%20foothold
*** allergic
https://www.dicts.cn/dictword20181/html/8325f1ce37a9baaf729fb60e8415b7ab.html?allergic
*** fan out
https://www.bing.com/dict/search?q=fan+out&qs=n&form=Z9LH5&sp=-1&lq=0&pq=fan+out&sc=0-7&sk=&cvid=03B7290EF52B46DAA8F17D27E3E97CCC
* [[https://www.bilibili.com/video/BV1y8KWzrEXe][读懂英语新闻（第242期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
:LOGBOOK:
- Note taken on [2025-06-24 Tue 09:30] \\
  [[https://www.youtube.com/watch?v=ScWmkuEBIdM][(12) 看美剧练听力（第242期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第242期新闻精读配套听力练习 - YouTube]]
:END:
** One
1, Preventing harm before it happens is a powerful motivation, one that's also animating the Japanese government's crackdown on "host clubs" where women pay for male companionship. The clubs were long viewed as harmless, but their reputation is souring as an increasing number of younger, poorer women take on debt — or even engage in sex work — to pay for them. Host clubs' appeal speaks to a growing economic divide in Japan, while the new rules of engagement reflect government efforts to maintain order in a nation known for its low crime rate.

*** animate
https://www.dicts.cn/dictword20181/html/3e6ec91b503a7471b1325fc08d89d822.html?animate
*** Host clubs
https://en.wikipedia.org/w/index.php?title=Host_and_hostess_clubs&useskin=vector#Host_clubs
*** companionship
https://www.dicts.cn/dictword20181/html/2dec010544497668440ca8015efe7621.html?companionship
*** sour
https://www.dicts.cn/dictword20181/html/fa7286403bdb7a467a53f10d3228c325.html?sour
*** engage in
https://www.bing.com/dict/search?q=engage%20in
*** divide
:LOGBOOK:
- Note taken on [2025-06-24 Tue 09:42] \\
  https://github.com/peng051410/today_i_learn/issues/225
:END:
https://www.dicts.cn/dictword20181/html/4f800fb6c31993b80bd293a318c1899c.html?divide
** Two
2, Social Security's potential insolvency date is now one year sooner than reported last year. Due to an aging population and a smaller share of U.S. workers paying in, the program could become unable to pay full retirement and disability benefits in 2034, its trustees said. Without congressional action, elderly and disabled Americans could see their payments reduced by 19% in 2034. Changes to benefits could touch off a fierce public debate ahead of the 2026 midterm elections.

*** insolvency
https://www.dicts.cn/dictword20181/html/a856f46289009ea04a1110f0e469af74.html?insolvency
*** pay in
https://www.bing.com/dict/search?q=pay+in&lq=0&pq=
*** trustee
https://www.dicts.cn/dictword20181/html/6aaab812fb9afae684856deb642ca2d5.html?trustee
*** touch off
https://www.bing.com/dict/search?q=touch+off&lq=0&pq=

** Three
3. A federal judge today ordered the Trump administration to release Mahmoud Khalil, the Columbia University graduate and prominent pro-Palestinian protester who has been jailed in Louisiana for the last three months. The government is seeking to deport Khalil based on a law that allows for the expulsion of people who oppose the nation's foreign policy objectives. The judge said that he had been persuaded by Khalil's arguments that his detention was an unlawful retaliation against his pro-Palestinian speech.

*** expulsion
https://www.dicts.cn/dictword20181/html/67248c726f909cd15209ba5ebe40fb93.html?expulsion
*** detention
https://www.dicts.cn/dictword20181/html/80b555cde3ec6322ce5a0614dc8a60fd.html?detention
*** retaliation
https://www.dicts.cn/dictword20181/html/33648ba318de45349b4fa8f73d61c8f8.html?retaliation
** Four
4. Mr Trump said that America had "completely and totally obliterated" three nuclear sites in Iran: Fordow, Natanz and Isfahan. America probably used huge bunker- busting bombs, which only it possesses. Abbas Araghchi, Iran's foreign minister, called America's actions "outrageous" and "criminal" and said they would have "everlasting consequences"

*** obliterate
https://www.dicts.cn/dictword20181/html/2114fafbdced9127cf7a7c634ef907ae.html?obliterate
*** outrageous
https://www.dicts.cn/dictword20181/html/8e2203cfc9fedfd06758fcb1473ea3cc.html?outrageous
*** everlasting
https://www.dicts.cn/dictword20181/html/2bb8509bab1514fd552c4e002f80fe5b.html?everlasting

* [[https://www.bilibili.com/video/BV1geKnzGEnz][读懂英语新闻（第243期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One

*** scold
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:44] \\
  https://www.bing.com/dict/search?q=scold
:END:
https://www.dicts.cn/dictword20181/html/a44bb5300269c401aa8dfb430d611b98.html?scold

*** broker
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:45] \\
  https://www.bing.com/dict/search?q=broker
:END:
https://www.dicts.cn/dictword20181/html/f9f7e3234c205ab0e2874dd07c3bd46d.html?broker

*** prevail
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:46] \\
  https://www.bing.com/dict/search?q=prevail&go=Search
:END:
https://www.dicts.cn/dictword20181/html/777692eac48155437d7ae9ae5eba521e.html?prevail

*** off-ramp
https://www.bing.com/dict/search?q=off-ramp

*** pillar
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:47] \\
  https://www.bing.com/dict/search?q=pillar&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/8696737266fd68ac4fb3c0f7132af5f6.html?pillar

*** theocracy
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:48] \\
  https://www.bing.com/dict/search?q=theocracy&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/4b4c66e89b69c625628ee94e6a9fdbc3.html?theocracy

*** recuperate
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:49] \\
  https://www.bing.com/dict/search?q=recuperate&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/ad69fd135ec9f0e5ee74f5dab4c4725b.html?recuperate

** Two
2. Stocks absolutely, positively don't want to go down. Tarifs? War in
the Middle East? Rising energy prices? Surging deficits? High interest
rates? Weak dollar? Plunging CEO confidence? Climate change?
Nope, nope, nope. Investors are already ignoring a slew of headwinds.
Lots of risks could become the final straw that breaks the market's
climb.Stocks rallied hard yesterday after Iran conducted a performative
retaliation, sending oil plunging more than 7%, and reinforcing
investors' relentless optimism.

*** headwind
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:49] \\
  https://www.bing.com/dict/search?q=headwind&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/0807633f0aa3d0e57d1f7622b4ed9b89.html?headwind

*** straw
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:49] \\
  https://www.bing.com/dict/search?q=straw&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/dded2464a3a2969bdaa07f61b2cda77d.html?straw

*** reinforce
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:49] \\
  https://www.bing.com/dict/search?q=reinforce&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/e8ce435c34fbf4740354b93e8fec0115.html?reinforce

*** relentless
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:49] \\
  https://www.bing.com/dict/search?q=relentless&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/953551085a6aa852261031705e85ea9a.html?relentless

** Three
3. China could generate over 100 DeepSeek-like
breakthroughs in artificial intelligence in the next 18
months, a development that "will fundamentally
change" the Chinese economy, according to Zhu Min, a
former deputy governor of the People's Bank of China.
       
*** deputy
:LOGBOOK:
- Note taken on [2025-06-26 Thu 09:50] \\
  https://www.bing.com/dict/search?q=deputy&lq=0&pq=
:END:
https://www.dicts.cn/dictword20181/html/f5abf61ad032a38166765604c198fcac.html?deputy
* [[https://www.youtube.com/watch?v=j5oMlAwV3Nw][(14) 一周听力合集（第242期+第243期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第243期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** court
:LOGBOOK:
- Note taken on [2025-06-27 Fri 09:49] \\
  https://github.com/peng051410/today_i_learn/issues/252
:END:
https://www.dicts.cn/dictword20181/html/5fe1e12a84349626bf02ab2079019db3.html?court
** dignity
:LOGBOOK:
- Note taken on [2025-06-27 Fri 09:50] \\
  https://github.com/peng051410/today_i_learn/issues/253
:END:
https://www.dicts.cn/dictword20181/html/4e2429949305627aa57e8464ac0af118.html?dignity
** attack
:LOGBOOK:
- Note taken on [2025-06-27 Fri 09:53] \\
  https://github.com/peng051410/today_i_learn/issues/254
:END:
https://www.dicts.cn/dictword20181/html/5e81d9a69883de0c947f062ba580bb46.html?attack
** one-time
https://www.bing.com/dict/search?q=one-time

* [[https://www.bilibili.com/video/BV1PV3AzhEd6][读懂英语新闻（第244期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. In a ruling in President Trump's birthright citizenship case, the Supreme Court restricted the power of individual judges to issue orders with nationwide effect. The 6-3 decision didn't resolve the policy's underlying legality. Trump signed an Inauguration Day executive order denying citizenship to U.S.-born children unless one parent was a citizen or permanent legal resident. In other rulings, the Supreme Court sided with Maryland parents opposed to LGBTQ books in schools and upheld a Texas law requiring certain porn websites to verify viewers' ages.

*** ruling
:LOGBOOK:
- Note taken on [2025-06-30 Mon 09:58] \\
  https://github.com/peng051410/today_i_learn/issues/255
:END:
https://www.dicts.cn/dictword20181/html/39c1457a8e98da6ff4dbbb4747966807.html?ruling

*** side with
https://www.bing.com/dict/search?q=side+with&lq=0&pq=

** Two
2. Trump ended trade talks with Canada "Effective immediately," Trump declared this afternoon, the U.S. will terminate all trade discussions with Canada. The president said the decision was in response to Canada's 3 percent digital services tax, which has been in place since last year - but the first, retroactive payments from U.S. companies, roughly $2.7 billion, are due Monday. Trump described those taxes as a "blatant attack" on the U.S., and he vowed to inform Canada within seven days of the tariffs that Canadian imports to the U.S. will face.

*** retroactive
https://www.dicts.cn/dictword20181/html/e12684b22a56d5d76f129a4ff5b78807.html?retroactive

*** blatant
https://www.dicts.cn/dictword20181/html/5a7fe578bbb8005acd3590a9200a365d.html?blatant

** Three
3, Cocaine's global shift. Drug cartels are moving cocaine
production outside Colombia, smuggling coca paste to labs as
far away as Italy to be processed into powder and concealing it
in goods like paint and plastic. The trend reflects booming
supply—up over 30% globally-as Colombia scales back the
military campaign against the private armies of the traffickers.

*** drug cartel
https://www.bing.com/dict/search?q=drug%20cartel

*** smuggle
https://www.dicts.cn/dictword20181/html/6497c3e7d1f11cd06a6663b8724e3a82.html?smuggle

*** powder
https://www.dicts.cn/dictword20181/html/74f157a0b3591afc82c0258fee1e78e8.html?powder

*** conceal
https://www.dicts.cn/dictword20181/html/6665159ff56cca40edf9507422334ab4.html?conceal

*** trafficker
https://www.dicts.cn/dictword20181/html/0f1a1adec0bc01364237866c451c357f.html?trafficker

*** scale back
https://www.bing.com/dict/search?q=scale%20back

* [[https://www.youtube.com/watch?v=doFSKmhWlZ4][(18) 看美剧练听力（第244期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第244期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** hang out
https://www.bing.com/dict/search?q=hang%20out
        
** I have a fover to ask you 
* [[https://www.bilibili.com/video/BV1ry34z4E5X][读懂英语新闻（第245期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. The Senate muscled through Trump's big policy bill
Senate Republicans managed to secure exactly enough votes today to pass the party's marquee bill to slash taxes and social safety net programs. The legislation, which was designed to deliver on President Trump's agenda, passed with a 51- to-50 margin after Vice President JD Vance cast the tiebreaking vote. The bill now heads to the House, where it still must pass before becoming law. Yale University economists forecast that the bill will cost the bottom 20% of taxpayers an average of $560 a year while giving a boost of $6,055 to those at the top end.

*** secure
:LOGBOOK:
- Note taken on [2025-07-03 Thu 09:45] \\
  https://github.com/peng051410/today_i_learn/issues/258
:END:
https://www.dicts.cn/dictword20181/html/a7dcc8c825c47387ace525c537b3eff6.html?secure
*** marquee
https://www.dicts.cn/dictword20181/html/ba3dbf2943a83cc4d5df53e265e36133.html?marquee
*** slash
https://www.dicts.cn/dictword20181/html/ff42d5ab765a076f7a9b5c724838ce00.html?slash
*** tiebreaking
https://www.bing.com/dict/search?q=tiebreaking&lq=0&pq=
*** top end
https://www.bing.com/dict/search?q=top+end&qpvt=top+end
** Two
2. Trump visited 'Alligator Alcatraz'
The president jetted off to Florida this morning to visit an abandoned airport in the Everglades that is being turned into a migrant detention center. Trump and his allies have decided to call the site "Alligator Alcatraz, " to highlight the remote location and dangerous local wildlife that they believe will make it difficult to escape. Environmental groups have sued to stop the project, arguing that environmental regulations have been disregarded in a rush to build the facility.

*** alligator
https://www.dicts.cn/dictword20181/html/f415042e19650994a6e6452590321f13.html?alligator
*** disregard
https://www.dicts.cn/dictword20181/html/8c3f7e04c9b834dca3d407ac585bd7d9.html?disregard
*** regulation
https://www.dicts.cn/dictword20181/html/d6e0f5d2a825315c8dc1353a3016a126.html?regulation
** Three
3. This summer blockbuster might feel familiar
It's been 32 years since dinosaurs started roaming the earth again — that is, since the original "Jurassic Park" opened in theaters. This week, the seventh entry in the series, "Jurassic World Rebirth," is hoping to draw a flood of nostalgic holiday- week moviegoers.

*** roam
https://www.dicts.cn/dictword20181/html/04d6817a165f4df5fe8d37799fc2f00a.html?roam
*** nostalgic
https://www.dicts.cn/dictword20181/html/b9bc3cafb7f3f019b7e41263ec56217a.html?nostalgic
*** moviegoer
https://www.dicts.cn/dictword20181/html/c0e0b33be863b5c3627b3463869f3eda.html?moviegoer

* [[https://www.youtube.com/watch?v=OXEJUnzRQGg][一周听力合集（第244期+第245期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第245期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


* [[https://www.youtube.com/watch?v=QYlc44zT5Jk][(22) 读懂英语新闻（第246期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, In central Texas, sudden floods swept through a summer camp and homes, killing at least 24. Rescuers are frantically searching for as many as 25 missing girls. Rain led to a rapid rise of the Guadalupe River, which accelerated to over 29 feet before sunrise on Friday. Camp Mystic, a Christian camp, said that it did not have power, water or Wi-Fi and was struggling to get more help because a nearby highway had washed away.

*** Texas
https://en.wikipedia.org/wiki/Texas?useskin=vector

*** sweep 
https://www.dicts.cn/dictword20181/html/16242a1aa963c08243d8921c94b3bf35.html?sweep

*** frantically
https://www.dicts.cn/dictword20181/html/dede5399d7e48aa0739cc3eb4d93bda8.html?frantically

*** wash away
https://www.bing.com/dict/search?q=wash%20away

** Two
2. The House narrowly passed Republicans' sprawling tax-and-spending bill, representing a major victory for President Trump. The 218-214 vote sends the measure to his desk ahead of a July 4 target. Trump and GOP leaders muscled the bill through the chamber after an all-night session, despite many lawmakers' misgivings. Overall, the legislation cuts taxes, boosts border security and lowers social safety-net spending. It delivers significant wins for some-Silicon Valley investors and airlines among them-and losses for others, including hospitals and online retailers.

*** sprawling
https://www.dicts.cn/dictword20181/html/4504fd23523eda02a38dcc0520db124a.html?sprawling

*** chamber
https://www.dicts.cn/dictword20181/html/385c52ce4511fb6fdf940723fe9acfca.html?chamber

*** all-night
https://www.dicts.cn/dictword20181/html/ad0a84a849fcbad5a8b5996fa5b8980e.html?all-night

*** misgiving
https://www.dicts.cn/dictword20181/html/3a0d5cc2f54846e56745c329c4bb98fa.html?misgiving

** Three
3. Sean "Diddy" Combs was found not guilty of racketeering and sex trafficking but convicted of less serious offenses. The jury's verdict was a blow for prosecutors who had alleged he ran a criminal enterprise for over two decades and coerced women into participating in sex parties he called freak-offs. In a letter to the judge, prosecutors estimated that under sentencing guidelines, the music mogul could face at least four to five years in prison.

*** racketeering
https://www.dicts.cn/dictword20181/html/48f195ab74fa65b23d888b28499e4ccf.html?racketeering

*** trafficking
https://www.dicts.cn/dictword20181/html/fc05076e5dbc3661a4cf7d0ed0d68ebe.html?trafficking

*** coerce
https://www.dicts.cn/dictword20181/html/4b63c011883151c49a23655f73bbe7b8.html?coerce

*** mogul
https://www.dicts.cn/dictword20181/html/b3fa1ea91efb53bb05b814f24f804433.html?mogul
* [[https://www.youtube.com/watch?v=3mg9wNU0k2Y][(22) 看美剧练听力（第246期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第246期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** rat
https://www.dicts.cn/dictword20181/html/f09937863c7a03e807271c2dc3d28c8c.html?rat
** refugee
https://www.dicts.cn/dictword20181/html/cd50b5efe629142a523c8bfd4507778c.html?refugee
** work out
https://www.bing.com/dict/search?q=work%20out
** fraud
https://www.dicts.cn/dictword20181/html/a89625aed3c3f9a38b993c62390d5e83.html?fraud
** gross
https://www.dicts.cn/dictword20181/html/0105d8b9a7f3e2ad02a4501103d3629f.html?gross
** run away
https://www.bing.com/dict/search?q=run%20away
* [[https://www.bilibili.com/video/BV1KFGAzPEGC][读懂英语新闻（第247期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. The deluge in Texas last week that killed more than 100 people ranks as one of the deadliest and costliest flash floods in US history, highlighting the mounting threat to communities that aren't prepared for extreme rainfall triggered by accelerating global warming. The area, known locally as "Flash Flood Alley" due to a history of deadly deluges, lacked public alarms or warning sirens that could have woken people up overnight and sent them to higher ground, partly due to the expense required to set them up. Cuts by the Trump administration at federal weather agencies are also coming under scrutiny in relation to the disaster.

*** deluge
https://www.dicts.cn/dictword20181/html/4e4ea156b72101f24f3ab2f2acb8abf9.html?deluge
*** siren
https://www.dicts.cn/dictword20181/html/3a38b609426b48f115ba5ffd2319f65f.html?siren
** Two
2. Tesla shares fell after Elon Musk announced he's forming a new political party, digging deeper into a pursuit that's been a drag on his most valuable business. Musk announced over the weekend that he'll take on Republicans and Democrats with the "America Party," focusing on House and Senate seats for the next 12 months. After that, backing a candidate for president isn't out of the question, Musk wrote on X.

*** dig into
https://www.bing.com/dict/search?q=dig+into&qs=n&form=Z9LH5&sp=-1&lq=0&pq=dig+into&sc=0-8&sk=&cvid=FF39E16BBE7D4DB18BF8CEDBC5F0A70F
*** take on
https://www.bing.com/dict/search?q=take+on&qs=n&form=Z9LH5&sp=-1&lq=0&pq=out+of+the+question
*** out of the question
https://www.bing.com/dict/search?q=out%20of%20the%20question
** Three
3. You may soon be able to stop worrying about removing your shoes to go through standard airport security checkpoints. The TSA is said to be planning to update its policies to end what has been one of the most visible-and criticized — features of the post-9/11 heightened US airport security system.

*** heighten
https://www.dicts.cn/dictword20181/html/2e835e9ce313e4633258f5af3e51939e.html?heighten

* [[https://www.youtube.com/watch?v=7iaJNYSUTZc][(26) 一周听力合集（第246期+第247期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第247期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** dam
https://www.dicts.cn/dictword20181/html/5124c0fefa00c96d306e24bcb2eed901.html?dam

** basin
https://www.dicts.cn/dictword20181/html/603cacf023ed510127c5cb2b40346557.html?basin

** cavalry
https://www.dicts.cn/dictword20181/html/33f8786e1cf360390ddf31637b469457.html?cavalry
* [[https://www.youtube.com/watch?v=W_sLANCI9dg][(29) 读懂英语新闻（第248期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Fed up with your paycheck? How does $200 million-plus sound? That's what Meta is apparently paying Ruoming Pang, who used to run Apple's AI models team. And it's in line with the compensation of other members of Meta's new "superintelligence" group. As the Al competition heats up, OpenAl's Sam Altman admitted he still hasn't spoken to Mark Zuckerberg since his rival poached some of his top engineers.

*** fed up
https://www.bing.com/dict/search?q=fed+up&FORM=HDRSC6
*** compensation
https://www.dicts.cn/dictword20181/html/40a48c6ed176788ec832c2773ce1b6fc.html?compensation
*** poach
https://www.dicts.cn/dictword20181/html/e0d7773b0862acb41c0bbca3d6ebcdaf.html?poach
** Two
2. Bitcoin's broken through $112,000 for the first timenow derivatives suggest the next stop may be $120,000, according to Bloomberg's MLIV. Meanwhile, Trump's trade policies gave traders pause for thought on US equities as they await a fresh catalyst for the next leg up.

*** derivative
https://www.dicts.cn/dictword20181/html/9ac5de9fa25a8357036f525d0cbfec21.html?derivative
*** catalyst
https://www.dicts.cn/dictword20181/html/d879b539d93a2209033f8a1d2cce55f5.html?catalyst
** Three
3. A British masterpiece is returning to England
More than 900 years ago, a 230-foot work of embroidery depicting the 1066 Norman Conquest was made in England to be hung in the nave of a cathedral in France. It became known as the Bayeux Tapestry, and Britain's culture secretary described it as "one of the most iconic pieces of art ever produced in the U.K."Next year, for the first time since its creation, the epic artwork will temporarily return to Britain, where it will be displayed at the British Museum in London.

*** masterpiece
https://www.dicts.cn/dictword20181/html/8a22e3b1015177e501c75729ad85f38d.html?masterpiece
*** embroidery
https://www.dicts.cn/dictword20181/html/0a3db8f1a2066b06a218a341ecd2f316.html?embroidery
*** depict
https://www.dicts.cn/dictword20181/html/005fb83a40de576bae62a07fb324dba8.html?depict
*** nave
https://www.dicts.cn/dictword20181/html/3b0f4a0138fa8869b31fc9bb9756a882.html?nave
*** cathedral
https://www.dicts.cn/dictword20181/html/1a33e47dc8feb61d0a9d15a44992df9b.html?cathedral
*** tapestry
https://www.dicts.cn/dictword20181/html/001ba031ff71435affc0d849e92ec8b5.html?tapestry
*** iconic
https://www.dicts.cn/dictword20181/html/781c48da889294160ccc498163cde791.html?iconic
*** epic
https://www.dicts.cn/dictword20181/html/79674190e8eb58a9b2827e4235e5eb3c.html?epic
* [[https://www.youtube.com/watch?v=GZX9WTdrJzY][(31) 看美剧练听力（第248期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第248期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** sick of 
https://www.bing.com/dict/search?q=sick%20of