#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil
#+FILETAGS: ANKI
#+STARTUP: indent
#+ANKI_DECK: English

* [[./news-100-200.org][news-100-200]]
* [[./news-200-300.org][news-200-300]]

* [[https://www.youtube.com/watch?v=_kyKBD2NEdQ][(51) 读懂英语新闻（第301期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Trump threatens to use brute force to lower prices
With many Americans frustrated over the high cost of living, the president has embraced a strategy of brute force. He has pressured the Federal Reserve in an effort to make mortgages more attractive, demanded credit card companies lower their fees and lashed out at businesses over high costs, among other threats. Consumer prices were 2.7 percent higher than a year ago, according to the latest data, and food prices climbed sharply last month.

*** brute force
https://www.bing.com/dict/search?q=brute%20force

*** lash out
https://www.bing.com/dict/search?q=lash+out&lq=0&pq=

** Two
2. Donald Trump urged protesters in Iran to "TAKE OVER" state institutions, saying that "HELP IS ON ITS WAY" as nationwide protests continued. He said all meetings with Iranian representatives would be cancelled until the killings stopped. An Iranian official estimated that around 2,000 people have died since the demonstrations erupted in late December, according to Reuters, a news agency.

*** Reuters
https://en.wikipedia.org/wiki/Reuters?useskin=vector

** Three
3. Prosecutors resign over Justice Dept.'s response to ICE shooting
Six federal prosecutors in Minnesota resigned today over the Trump administration's push to investigate the widow of the woman an ICE agent killed last week in Minneapolis. They also objected to the Justice Department's reluctance to investigate the shooter.

*** prosecutor
https://www.dicts.cn/dictword20181/html/31c70222fa13dbc17000c6c324ddd220.html?prosecutor

* [[https://www.youtube.com/watch?v=g2rP3Bw5LFw][(51) 一周听力合集（第300期+第301期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第301期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** fist
https://www.dicts.cn/dictword20181/html/d3818eae2938c4a0400daba891818f78.html?fist

* [[https://www.bilibili.com/video/BV15GkaBXEpt][读懂英语新闻（第302期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** One
1. What's the best activity for longevity?
Research has repeatedly shown that regular exercise is one of the most effective ways to lengthen your life. Even just a few minutes a day has real benefits. However, some activities seem to come with extra benefits. In particular, tennis has been linked with longevity. One study found that tennis players lived almost 10 years longer than their sedentary peers — and longer than soccer players, cyclists and swimmers. That may be because tennis is a full-body workout that often involves socializing and can be played later in life.

*** longevity
https://www.dicts.cn/dictword20181/html/e291106ed285bcc652fe84de0e883fe1.html?longevity

** Two
2. Venezuelan opposition leader María Corina Machado said she "presented" President Trump with her Nobel Peace Prize during an Oval Office meeting yesterday. Trump, who has publicly campaigned for the prize, wrote on Truth Social: "María presented me with her Nobel Peace Prize for the work I have done. Such a wonderful gesture of mutual respect."

*** mutual
https://www.dicts.cn/dictword20181/html/fc64263140871358a7e9c55f8bc57904.html?mutual

** Three
3. Donald Trump announced that he would impose escalating tarifis on Denmark and other European countries, including Britain, France and Germany, that fail to support his bid to purchase Greenland. Writing on his Truth Social platform, he threatened a 10% levy on all goods starting on February 1st, increasing to 25% on June 1st. His threats followed mass protests in Denmark and Greenland in response to America's push to acquire the Arctic territory.

*** Arctic
https://en.wikipedia.org/wiki/Arctic?useskin=vector
* [[https://www.youtube.com/watch?v=9uxZlZ7C6Xg][(57) 看美剧练听力（第302期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第302期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** dormant
https://www.dicts.cn/dictword20181/html/0a37fb433c659bba5ec0e5b130b62b23.html?dormant
* [[https://www.youtube.com/watch?v=0_78c8bBzBE][(59) 读懂英语新闻（第303期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Canadian Prime Minister Mark Carney used a major address in Davos to urge world leaders to see the reality of a world that's increasingly governed by superpower aggression. Recent events have shown the "rules-based international order" is effectively dead, Carney said, which means Canada and other countries have no choice but to create new alliances to oppose pressure tactics and intimidation.
   
*** Davos
https://en.wikipedia.org/wiki/Davos?useskin=vector
*** effective
https://www.dicts.cn/dictword20181/html/25926b7d34dd0f019fe250777f933563.html?effective
*** tactic
https://www.dicts.cn/dictword20181/html/d58d0ac1436d0103df3c7ce6d139e6fe.html?tactic
** Two
2. Fewer people are jumping off the Golden Gate Bridge
The Golden Gate Bridge, the iconic span that hangs between San Francisco Bay and the Pacific Ocean, has been the site of more than 2,000 confirmed suicide leaps since it opened in 1937. For decades, the death toll hovered around 30 a year. But now, after the completion of a $224 million project to install stainless-steel nets below the bridge, the number of suicides has noticeably dropped. There were none in the second half of 2025.

*** jump off
https://www.bing.com/dict/search?q=jump%20off
*** Golden Gate Bridge
https://en.wikipedia.org/wiki/Golden_Gate_Bridge?useskin=vector
*** stainless-steel
https://en.wikipedia.org/w/index.php?title=Stainless_steel&useskin=vector
** Three
3. After deadly train crash, investigators focus on the track
Spanish authorities struggled today to identify those killed in Sunday's high-speed train collision, which left at least 41 people dead. Investigators there are focusing on whether a track problem may have caused the incident, and a train undercarriage found in a stream may be a clue.

*** [#A] track
https://www.dicts.cn/dictword20181/html/9577da8e56547833c5c7982a66c0df80.html?track
*** stream
https://www.dicts.cn/dictword20181/html/fdd35a283c3c1e300ca192e9fdea4e7f.html?stream
* [[https://www.youtube.com/watch?v=pW-ibJl2-UE][(62) 一周听力合集（第302期+第303期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第303期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** distress
https://www.dicts.cn/dictword20181/html/6f6f163ece0ac37fbb9a126643802080.html?distress
** pour
https://www.dicts.cn/dictword20181/html/e9795bd9cfc73ee676039a1eb1b35437.html?pour
* [[https://www.bilibili.com/video/BV1PTzhB4Ejm][读懂英语新闻（第304期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Federal immigration agents shot and killed a man in Minneapolis. Video of the incident shows several agents wrestling the man to the ground before he was shot multiple times. The Department of Homeland Security claimed the victim had a gun and resisted attempts to disarm him. This was the third shooting involving federal agents in Minneapolis this month. Minnesota's governor, Tim Walz, called on the Trump administration to end its immigration crackdown in the city.

*** Minneapolis
https://en.wikipedia.org/wiki/Minneapolis?useskin=vector
** Two
2. A winter storm expected to be the largest of the season is already causing major disruptions across the US, with airlines cutting more than 2,300 flights. The storm is expected to span nearly 1,500 miles, bringing heavy snow, crippling ice and subzero wind chill to some of the biggest US cities, threatening power outages for much of the nation. Heavy snow will likely start falling across New York City early Sunday, with more than 14 inches possible throughout the metro area before the storm subsides late Monday.

*** span
https://www.dicts.cn/dictword20181/html/507be733145069715aca758dddbee71d.html?span
*** chill
https://www.dicts.cn/dictword20181/html/075aecc4bc6d39f0ca513513ca101dd5.html?chill
*** outage
https://www.dicts.cn/dictword20181/html/b13d548fd07c0780c7dc5c175fcef6be.html?outage
*** metro area
https://www.bing.com/dict/search?q=metro%20area
*** subside
https://www.dicts.cn/dictword20181/html/119ca95fff76b218e42dbf8585a11ca9.html?subside
** Three
3. Vaccine panel chair says shots should be optiona!
Kirk Milhoan, a doctor who leads the federal panel that recommends vaccines for Americans, said this week that shots protecting against polio and measles — and perhaps all diseases — should be optional. The polio and measles vaccines are widely credited with preventing millions of deaths, and many public health experts strongly disagree with Milhoan.

*** panel
https://www.dicts.cn/dictword20181/html/101a03bacf841a718473b07c62e727df.html?panel
* [[https://www.youtube.com/watch?v=_9G1-3_BxMQ][(63) 看美剧练听力（第304期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第304期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** mess up
https://www.bing.com/dict/search?q=mess%20up
* [[https://www.youtube.com/watch?v=inaNRx11FGQ][(64) 读懂英语新闻（第305期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Yale will offer free tuition to undergraduates from families making less than $200,000. The changes, which take effect in the 2026-2027 academic year, will also eliminate all expected costs for families with typical assets and incomes below $100,000. The decision matches a move by Harvard University last year to broaden educational affordability.

** Two
2. Trump faults Pretti for carrying a gun
Speaking to reporters this afternoon, the president promised a "very honorable and honest investigation" into the killing of Alex Pretti, who was shot dead over the weekend by federal agents in Minneapolis. Trump also cast blame on Pretti for carrying the legally permitted weapon that was seized from him before he was shot. "You can't walk in with guns," the president said. "You can't do that."

*** fault
https://www.dicts.cn/dictword20181/html/f1cd1c2856ff323e2ebd2d77de256e30.html?fault
** Three
3. Are social media apps addictive like cigarettes? Do they harm young users?
Meta, Snap, TikTok and YouTube will be forced to confront such questions in a series of landmark trials. The first began today in California, where a young woman said she had become addicted to the sites as a child and had experienced anxiety and depression as a result. TikTok and Snap settled the case, but they remain defendants in more than a dozen others, which may result in huge monetary payments or changes to the platforms.

*** landmark
https://www.dicts.cn/dictword20181/html/638d89fc791a2f5451aca0ed2293a0f5.html?landmark
*** [#A] trial
https://www.dicts.cn/dictword20181/html/0e11ce59fc8e84c3f7d29ab33fd40593.html?trial
*** monetary
https://www.dicts.cn/dictword20181/html/e73958ad5aad92f3dabf50fd2aef96f3.html?monetary
* [[https://www.youtube.com/watch?v=nDU25kwv2tw][(68) 一周听力合集（第304期+第305期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第305期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** assimilate
https://www.dicts.cn/dictword20181/html/cb2fd4fb854efe7a4e58e8e671ee9777.html?assimilate
** rid
https://www.dicts.cn/dictword20181/html/9a1e874c68ea993a0f122a5010ba1ce0.html?rid
* [[https://www.youtube.com/watch?v=KeZ8UvfO4ME][(70) 读懂英语新闻（第306期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Kevin Warsh has been preparing to lead the Fed for more than a decade.
He thought he had the job in 2017, but President Trump had doubts. Today, however, the president announced that he would nominate the 55-year-old former Fed official to chair the central bank. If confirmed by the Senate, Warsh would succeed Jerome Powell in mid-May. Wall Street has conflicting views on Warsh, as reflected in falling stocks, steady bond yields, a rallying dollar and the worst day for gold and silver in more than four decades.

*** Kevin Warsh
https://en.wikipedia.org/wiki/Kevin_Warsh?useskin=vector
*** [#A] conflict
https://www.dicts.cn/dictword20181/html/101bd50ac6603cb4db5d6ef9c9d40243.html?conflict
** Two
2. Genes may determine longevity, no matter your health choices
Researchers used data from thousands of twins, who share identical genes, to conclude that aging is mostly hereditary. You can lengthen it a bit, the new study suggests: One of the researchers calculated that healthy or unhealthy habits can add or subtract five years or so from a life expectancy. But if your genetic potential is to live to be 80, for example, it is unlikely that anything you do will push your age at death up to 100.

*** identical
https://www.dicts.cn/dictword20181/html/637c83d172e03f7fe6c32df1fb588672.html?identical
*** hereditary
https://www.dicts.cn/dictword20181/html/42f1b6bea80ffe1e912dcb4b7d09fae0.html?hereditary
** Three
3. 'House burping' is catching on
In Germany, it is second nature for people to open their windows a few times each day to cycle out stale air. They call the practice "lüften," which roughly translates to "ventilate" or "air out." In recent weeks, lüften has gained traction with Americans, who have flooded social media with videos referring to the practice as "house burping. Unlike many online trends, there are real benefits: Experts say that opening windows can help clean the air and reduce mold.

*** catch on
https://www.bing.com/dict/search?q=catching%20on
*** second nature
https://www.bing.com/dict/search?q=second%20nature
*** mold
https://www.dicts.cn/dictword20181/html/cea5e8dc8edb7f6c6dd91ef221c446e1.html?mold
* [[https://www.youtube.com/watch?v=yLUOYdhXKoM][(70) 看美剧练听力（第306期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力｜美剧听力｜第3066期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** congenital
https://www.dicts.cn/dictword20181/html/0b32f4f0e2287196c9d55969c4e60c04.html?congenital
** feminism
https://www.dicts.cn/dictword20181/html/49ce18863ce92cdbf06e747e575cff4b.html?feminism
** spare me
https://www.bing.com/dict/search?q=spare%20me
* [[https://www.youtube.com/watch?v=LX9JWXgDXUE][(70) 读懂英语新闻（第307期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Former President Bill Clinton and his wife Hillary will appear before a congressional committee investigating disgraced financier Jeffrey Epstein. A full House vote had been planned this week to hold the Clintons in criminal contempt if they continued to defy subpoenas in its Epstein inquiry. Testimony by a former president to a congressional body is almost unheard of, so this should be quite a moment.

*** appear before
https://idioms.thefreedictionary.com/appear+before

*** contempt
https://www.dicts.cn/dictword20181/html/83b89dfc48f0785c48aa15e029f2571e.html?contempt

*** testimony
https://www.dicts.cn/dictword20181/html/24c8c8e1226badde1d42cfa69a68650b.html?testimony
** Two
2. The internet is awash in speculation, suspicion and disgust over the millions of new pages of Jeffrey Epstein files released by the Justice Department on Friday. Some Epstein associates - British power broker Peter Mandelson, Norwegian royal Mette-Marit, celebrity doctor Peter Attia - are paying real reputational and professional costs. The Epstein files are being consumed in an information ecosystem that struggles with nuance, context and legal standards — where guilt by association is the default. Al compounds the confusion: Fake emails, doctored screenshots and Al-generated images circulate alongside authentic ones, tricking even veteran journalists.

*** disgust
https://www.dicts.cn/dictword20181/html/9b4a644e0b7b712fce61cabc4cd86cc9.html?disgust

*** circulate
https://www.dicts.cn/dictword20181/html/6bd3d73eeca0cd35a6e9fadaf35d992a.html?circulate
** Three
3. Elon Musk's SpaceX has acquired xAI in a deal that encompasses the billionaire's increasingly costly ambitions to dominate artificial intelligence and space exploration. The deal, which gives the combined company a valuation of $1.25 trillion, was announced to employees in a memo on Monday, Bloomberg News reported earlier.

*** encompass
https://www.dicts.cn/dictword20181/html/8cda19a94b02ce40d7a08344248d346b.html?encompass
* [[https://www.youtube.com/watch?v=5Bw1K2OIBKk][(96) 一周听力合集（第306期+第307期）｜词汇精听｜纯正美音｜英语新闻精听｜听新闻学英语｜单词轻松记｜听力跟读版｜英语听力合集｜美剧听力｜第307期新闻精读配套听力练习 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** pity
https://www.dicts.cn/dictword20181/html/613c25e5b363cdecc37a4db0bb236e57.html?pity
** rage
https://www.dicts.cn/dictword20181/html/dd3d18b12a5d9d4e502e2001faccf73d.html?rage
** tender
https://www.dicts.cn/dictword20181/html/b1a46b58dc65767214595a986a658560.html?tender