#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil

* [[https://www.youtube.com/watch?v=DFZRg8z_AJg][(10) 读懂英语新闻（第186期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Judges rejected TikTok's effort to avoid a U.S. ban
TikTok, a video app used by more than 170 million Americans,
moved one step closer today to disappearing from the U.S. market. A
panel of federal judges unanimously upheld a new law that requires
the app's Chinese owner to either sell TikTok to a non-Chinese owner
by mid-January or face a nationwide ban in the U.S. While Donald
Trump has promised to save the app, the law is set to go into effect
the day before his inauguration and it's unclear how he could evade
an act of Congress and whether he wants to risk much political
capital on this given his hawkish stance on China.
*** upheld
*** inauguration
*** evade
** Two
2. N.Y.P.D. said the shooting suspect may have left the city
New York's police commissioner said today that the man who
fatally shot a health insurance executive in Midtown
Manhattan might have left the city. The authorities said they
have video of the man taking a cab to an interstate bus station
in Upper Manhattan and entering it on the day of the attack,
but never exiting. So far, there have been no arrests and the
authorities have not established a motive.
*** NYPD
:LOGBOOK:
- Note taken on [2024-12-11 Wed 09:51] \\
  纽约市警察局（NYPD）是美国最大的市警局，下设多个部门，负责维护纽约市治安。
:END:
https://en.wikipedia.org/w/index.php?title=New_York_City_Police_Department&useskin=vector
*** Manhattan
https://en.wikipedia.org/wiki/Manhattan?useskin=vector
*** interstate
https://en.wikipedia.org/w/index.php?title=Interstate_Highway_System&useskin=vector

* [[https://www.youtube.com/watch?v=46AovK1-eX4][(10) 读懂英语新闻（第187期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Suspect in C.E.O. killing is fighting extradition
The 26-year-old man who was charged with murder in the assassination of a
health insurance executive in Midtown Manhattan was denied bail today.
Mangione saw himself as a hero fighting a corrupt health insurance industry,
the authorities said in an internal report obtained by The Times. The police
also expressed concern that the attack could inspire violence against similar
executives or other extreme behavior.
Here's what we know about the suspect: Mangione was a high school
valedictorian and an Ivy League tech graduate from a prominent Maryland
family. The subject of a missing-person report filed in San Francisco by his
mother last month, he had stopped communicating with friends and family
about six months ago.

*** extradition
https://en.wikipedia.org/wiki/Extradition?useskin=vector

引渡是一个复杂的问题，涉及主权、司法合作和人权等多方面因素。
*** bail
*** Ivy League
https://en.wikipedia.org/wiki/Ivy_League?useskin=vector

常春藤联盟（Ivy League）是美国东北部八所私立研究型大学组成的大学体育联盟，也是全球知名的精英大学联盟，以其学术卓越、录取率极低以及社会精英地位而闻名。
** Two
2. Hundreds of firefighters are racing to control a fast-
moving Southern California wildfire that's threatening
the wealthy town of Malibu and has forced the
evacuation of thousands of residents. The Franklin fire
has swelled to more than 2,700 acres and remained
completely out of control as of Tuesday afternoon.
*** Malibu
:LOGBOOK:
- Note taken on [2024-12-12 Thu 10:03] \\
  马里布独特的地理位置、气候条件和历史文化，使其成为一个备受瞩目的海滨城市，但同时也面临着自然灾害和环境保护等方面的挑战。
:END:
https://en.wikipedia.org/wiki/Malibu%2C_California?useskin=vector

*** evacuation
** Three
3. Syrian rebels rushed to impose order in Damascus
after Bashar al-Assad's regime collapsed over the
weekend. Leader Abu Mohammed al-Jawlani moved to
form a transitional government, get the buses running
and turn the power back on. Many foreign countries,
including the U.S., classify his group as a terrorist
organization.
*** rebel
*** rush to
*** move to