#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil
#+FILETAGS: ANKI
#+STARTUP: indent
#+ANKI_DECK: English

* [[https://www.youtube.com/watch?v=GvqIuDE2Vlc][(21) 一周英语新闻精学（第1期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜英语纠音｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. More than half of U.S. states have taken steps to ban or restrict cellphone use in K-12 schools. Even some students admit that their phones can be hugely disruptive during class, and cyberbullying is a persistent issue — but many parents see phones as critical safety tools in the event of a shooting or other emergency. In some schools, students are expected to put their devices in a secure pouch they can unlock when leaving for the day, or during an emergency.

*** in the event of
https://www.bing.com/dict/search?q=in+the+event+of

** Two
2. Shigeru Ishiba officially takes office as Japan's prime minister Tuesday, replacing Fumio Kishida, who resigned in no small part because of record-high disapproval numbers for their ruling Liberal Democratic Party. But this hardly heralds big change. Like Kishida, Ishiba is a second-generation LDP politician. And the LDP remains in power. The Liberal Democratic Party has ruled Japan for all but four of the past 69 years, leading some to ask whether its parliament is truly representative.

*** take office
https://www.bing.com/dict/search?q=take%20office

*** in no small part
https://www.iciba.com/word?w=in+no+small+part

*** herald
https://www.dicts.cn/dictword20181/html/7be1eccc148c67bbf5b60ac1a1107c97.html?herald

*** all but
https://www.bing.com/dict/search?q=all%20but

** Three
3. China's stockmarket enjoyed its best day of trading since 2008, with its benchmark CSI300 surging over 8%, following nine days of consecutive gains. Investors were buoyed by the government's announcement of stimulus policies last week. The measures include cutting interest rates, trimming bank reserve requirements and lowering rates for existing mortgages.

** Four
4. The stock market has been on a tear of late — up 34% over the past year and up 20% year-to-date. That's the best stock- market performance in the first three quarters since 1997, and it's boosted total returns over almost any time horizon. The index's 30-year return is 1,135% — it's risen more than twelvefold in the past three decades — and currently stands at an all-time high.

*** on a tear
https://www.merriam-webster.com/dictionary/on%20a%20tear

*** year-to-date
https://www.bing.com/dict/search?q=year-to-date

*** horizon
https://www.dicts.cn/dictword20181/html/9f9627a538428ef9e326d0822f18a5fe.html?horizon


* [[https://www.youtube.com/watch?v=XTxFYQHuwQg&t=580s][(28) 一周英语新闻精学（第2期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜英语纠音｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:


** One
:LOGBOOK:
- Note taken on [2025-12-26 Fri 09:46] \\
  https://youtu.be/XTxFYQHuwQg?si=omu2HhCFrqjXrLuv&t=877
:END:
1. OpenAI just closed one of the largest fundraising rounds in history, valuing the company at $157 billion, a huge leap for a scrappy startup run by a handful of executives. But as OpenAl races to build a global business, it has been roiled by an exodus of top officials and much of the brain trust that put the startup on the map, including most recently Chief Technology Officer Mira Murati. Employees at various levels of the company are now wrestling with exhaustion as concerns grow that OpenAl's initial commitment to responsible Al development may be wavering.

*** handful
https://www.dicts.cn/dictword20181/html/4cc990869bf1ea540cc19de926e21ad8.html?handful

*** exodus
https://www.dicts.cn/dictword20181/html/88d47704c04d38de0d31a16d9dcee8f8.html?exodus

*** brain trust
https://www.bing.com/dict/search?q=brain%20trust

*** put on the map
https://www.bing.com/dict/search?q=put%20on%20the%20map

*** Mira Murati
https://en.wikipedia.org/wiki/Mira_Murati?useskin=vector

*** exhaustion
https://www.dicts.cn/dictword20181/html/133671edbf82717d47938a7ad853b251.html?exhaustion

*** commitment
https://www.dicts.cn/dictword20181/html/032440e053f16f776518b5bb9335901b.html?commitment

** Two
:LOGBOOK:
- Note taken on [2025-12-26 Fri 09:49] \\
  https://youtu.be/XTxFYQHuwQg?si=Ui6zzIgQp7rNSpPC&t=925
:END:
2. Victor Rambros and Gary Ruvkin won the Nobel prize for physiology or medicine for their discovery of micro-RNA and "its role in post-transcriptional gene regulation". The Nobel Assembly of the Karolinska Institute, in Stockholm, which awards the prize, said that micro-RNAs are crucial "for how organisms develop and function". The American scientists will share a prize of 11m Swedish kronor ($1.06m).

*** regulation
https://www.dicts.cn/dictword20181/html/d6e0f5d2a825315c8dc1353a3016a126.html?regulation

*** organism
https://www.dicts.cn/dictword20181/html/ce399c7fc789891f07a8a6150a18d853.html?organism

** Three
:LOGBOOK:
- Note taken on [2025-12-26 Fri 09:51] \\
  https://youtu.be/XTxFYQHuwQg?si=weW4c29g7Q9XVxsB&t=944
:END:
3. Melania Trump made an extraordinary declaration in an eagerly awaited memoir to be published a month from election day: she is a passionate supporter of a woman's right to control her own body- including the right to abortion. Melania Trump has rarely expressed political views in public. Her book, Melania, which reveals the former first lady to be so firmly out of step with most of her own party, will be published in the US next Tuesday.

*** passionate
https://www.dicts.cn/dictword20181/html/050079603ca6079746440c2aaa474d3b.html?passionate

*** abortion
https://www.dicts.cn/dictword20181/html/d4e74a47a656294b00edfb3ea5808c87.html?abortion

*** out of step
https://www.bing.com/dict/search?q=out%20of%20step