#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil

* [[https://www.youtube.com/watch?v=DFZRg8z_AJg][(10) 读懂英语新闻（第186期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Judges rejected TikTok's effort to avoid a U.S. ban
TikTok, a video app used by more than 170 million Americans,
moved one step closer today to disappearing from the U.S. market. A
panel of federal judges unanimously upheld a new law that requires
the app's Chinese owner to either sell TikTok to a non-Chinese owner
by mid-January or face a nationwide ban in the U.S. While Donald
Trump has promised to save the app, the law is set to go into effect
the day before his inauguration and it's unclear how he could evade
an act of Congress and whether he wants to risk much political
capital on this given his hawkish stance on China.
*** upheld
*** inauguration
*** evade
** Two
2. N.Y.P.D. said the shooting suspect may have left the city
New York's police commissioner said today that the man who
fatally shot a health insurance executive in Midtown
Manhattan might have left the city. The authorities said they
have video of the man taking a cab to an interstate bus station
in Upper Manhattan and entering it on the day of the attack,
but never exiting. So far, there have been no arrests and the
authorities have not established a motive.
*** NYPD
:LOGBOOK:
- Note taken on [2024-12-11 Wed 09:51] \\
  纽约市警察局（NYPD）是美国最大的市警局，下设多个部门，负责维护纽约市治安。
:END:
https://en.wikipedia.org/w/index.php?title=New_York_City_Police_Department&useskin=vector
*** Manhattan
https://en.wikipedia.org/wiki/Manhattan?useskin=vector
*** interstate
https://en.wikipedia.org/w/index.php?title=Interstate_Highway_System&useskin=vector

* [[https://www.youtube.com/watch?v=46AovK1-eX4][(10) 读懂英语新闻（第187期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. Suspect in C.E.O. killing is fighting extradition
The 26-year-old man who was charged with murder in the assassination of a
health insurance executive in Midtown Manhattan was denied bail today.
Mangione saw himself as a hero fighting a corrupt health insurance industry,
the authorities said in an internal report obtained by The Times. The police
also expressed concern that the attack could inspire violence against similar
executives or other extreme behavior.
Here's what we know about the suspect: Mangione was a high school
valedictorian and an Ivy League tech graduate from a prominent Maryland
family. The subject of a missing-person report filed in San Francisco by his
mother last month, he had stopped communicating with friends and family
about six months ago.

*** extradition
https://en.wikipedia.org/wiki/Extradition?useskin=vector

引渡是一个复杂的问题，涉及主权、司法合作和人权等多方面因素。
*** bail
*** Ivy League
https://en.wikipedia.org/wiki/Ivy_League?useskin=vector

常春藤联盟（Ivy League）是美国东北部八所私立研究型大学组成的大学体育联盟，也是全球知名的精英大学联盟，以其学术卓越、录取率极低以及社会精英地位而闻名。
** Two
2. Hundreds of firefighters are racing to control a fast-
moving Southern California wildfire that's threatening
the wealthy town of Malibu and has forced the
evacuation of thousands of residents. The Franklin fire
has swelled to more than 2,700 acres and remained
completely out of control as of Tuesday afternoon.
*** Malibu
:LOGBOOK:
- Note taken on [2024-12-12 Thu 10:03] \\
  马里布独特的地理位置、气候条件和历史文化，使其成为一个备受瞩目的海滨城市，但同时也面临着自然灾害和环境保护等方面的挑战。
:END:
https://en.wikipedia.org/wiki/Malibu%2C_California?useskin=vector

*** evacuation
** Three
3. Syrian rebels rushed to impose order in Damascus
after Bashar al-Assad's regime collapsed over the
weekend. Leader Abu Mohammed al-Jawlani moved to
form a transitional government, get the buses running
and turn the power back on. Many foreign countries,
including the U.S., classify his group as a terrorist
organization.
*** rebel
*** rush to
*** move to
* [[https://www.youtube.com/watch?v=zrmOoQ8bwBw][(12) 读懂英语新闻（第188期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Trump had his perfect 1980s day. He rang the bell to open the
stock exchange and was named Person of the Year by Time magazine.
Trump, speaking with Time, pledged to start pardoning Jan. 6 rioters
once he enters office. He sounded open to banning some childhood
vaccines and reversing protections for transgender kids. During the
campaign, Trump said he'd lower grocery prices. Yesterday, he told
Time that "it's hard to bring things down once they're up," but he
added that he was still hopeful.
*** pardon
*** rioter
*** it's hard to bring things down once they're up
** Two
2. Lisa Su - chief executive of chipmaker AMD — is TIME's
" CEO of the Year." AMD's stock price has increased 50x since Su
took over a decade ago, fueled by Al - as well as smart planning
that put the company in a position to benefit when some of its
rivals, like Intel, have faltered. "It really is one of the great
turnaround stories of modern American business history," Chris
Miller, a historian of the semiconductor industry, told TIME.
*** falter
** Three
3. The NYPD is investigating a number of 'WANTED' posters of
senior executives that are showing up in parts of Manhattan. They
included images of UnitedHealth's Brian Thompson, who was
murdered last week, as well as executives from American Express,
Goldman Sachs, Bank of America and JPMorgan Chase. The arrest of
Luigi Mangione this week has failed to fill in some key details of
Thompson's killing, while dark glee over the murder is stoking fear
among insurers about copycats.
*** WANTED
*** fill in
*** glee
*** stoke
*** copycat
** Four
4. Extreme weather this year across chili planting regions from
Mexico to India has sapped supply, pushed up prices and-worst
of all-distorted their flavor. The perfect growing conditions for
chili peppers and other crops are becoming harder to find as
climate change increases the frequency of weather extremes such
as drought and floods, according to researchers. Some suppliers
are under pressure and chefs will soon be forced to innovate.
*** sap
*** flavor
*** drought
*** chefs
* [[https://www.youtube.com/watch?v=0V-erwAAzeM][(13) 读懂英语新闻（第189期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Madison mourned after a school shooting
A makeshift memorial grew on a sidewalk outside a Christian
school in Madison, Wis., where a teenage student fatally shot a
teacher and a fellow student yesterday. Police identified the
shooter as Natalie Rupnow, a 15-year-old student who died from
what appeared to be a self-inflicted gunshot wound. Much is
still unknown about the attack.
*** Madison
https://en.wikipedia.org/wiki/Madison,_Wisconsin?useskin=vector
*** mourn
*** makeshift
https://en.wiktionary.org/wiki/makeshift
*** fellow student
** Two
2. Mangione Faces First-Degree Murder Charge That Brands Him a Terrorist
A grand jury formally indicted Luigi Mangione in the killing of Brian
Thompson, the chief executive of UnitedHealthcare. "This was a frightening,
well-planned, targeted murder that was intended to cause shock and attention
and intimidation, " said Alvin L. Bragg, the Manhattan district attorney, at a
news conference on Tuesday. A lawyer for Mr. Mangione, Karen Friedman
Agnifilo, declined to comment on the new charges. If convicted on the highest
charges, Mr. Mangione faces a sentence of life in prison without parole.
*** brand
*** indict
*** intimidation
:LOGBOOK:
- Note taken on [2024-12-25 Wed 09:49] \\
  https://www.dicts.cn/dictword20181/html/22471f08fae98218f73617e7e599bc63.html?intimidate
:END:

*** declined
:LOGBOOK:
- Note taken on [2024-12-25 Wed 09:49] \\
  https://www.dicts.cn/dictword20181/html/fe911eb0a594a4f847ef6f0548db4270.html?decline
:END:

*** parole
https://en.wikipedia.org/wiki/Parole?useskin=vector
** Three
3. A Russian general was killed today by a bomb on a
Moscow street. Ukraine claimed responsibility for what
appears to be one of the most brazen assassinations since
Russia's full-scale invasion nearly three years ago.
Yesterday, Kyiv had blamed him for the "massive use of
banned chemical weapons" in Ukraine.
*** what appears to be
*** brazen
:LOGBOOK:
- Note taken on [2024-12-25 Wed 09:53] \\
  https://www.dicts.cn/dictword20181/html/73cd04c35219dfdd2975c5c74bde97b6.html?brazen
:END:

*** full-scale
*** Kyiv
https://en.wikipedia.org/wiki/Kyiv?useskin=vector

* [[https://www.youtube.com/watch?v=xv5OLy8J5wU][(15) 读懂英语新闻（第190期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1. A driver plowed a vehicle into a Christmas market in the city of
Magdeburg in central Germany this evening, killing at least two
people and injuring more than 65 others, 14 of them severely. The
driver, identified as a 50-year-old Saudi Arabian citizen, was
arrested, the authorities said. They said they believe it was a
deliberate attack. More than 1,000 Christmas markets pop up every
year in Germany, and have been targeted by terrorists before.
*** plow into

*** Magdeburg
https://en.wikipedia.org/wiki/Magdeburg?useskin=vector
*** deliberate

*** pop up

** Two
2. Hopes were high that the Fed's rate cuts could make homes
more affordable, but so far, that hasn't happened. Average rates
on 30-year mortgages have climbed to around 6.7% from
roughly 6.1% since the central bank started lowering rates in
September, according to Freddie Mac. And they're only poised
to rise further. That's because mortgage rates move with the
yield on the 10-year Treasury, which has surged this week.
*** mortgage
https://en.wikipedia.org/wiki/Mortgage?useskin=vector
*** poised to

*** yield
https://en.wikipedia.org/wiki/Yield_(finance)?useskin=vector
** Three
3. Anthony Loke, Malaysia's transportation minister, announced
plans for a robotics company to renew a search for the plane that
disappeared in 2014. "We think that this is another attempt to find
[Malaysia Airlines Flight] 370, and it is our responsibility, and our
obligation, and our commitment to the families." The flight was en
route to Beijing from Kuala Lumpur with 239 people on board. An
approximately $150 million multiyear search effort-the most
expensive in aviation history— ended in 2017.
*** en route
:LOGBOOK:
- Note taken on [2024-12-24 Tue 09:48] \\
  on the way
:END:

*** aviation
https://en.wikipedia.org/wiki/Aviation?useskin=vector
* [[https://www.youtube.com/watch?v=Gb63l2VsyWQ][(15) 读懂英语新闻（第191期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, American Airlines briefly grounded all U.S. flights
On one of the busiest travel days of the year, American Airlines grounded all
its flights in the U.S. this morning for about an hour. American said a vendor
technology issue had affected systems needed to release flights. While
relatively brief, the ground stop could result in heavy delays in the coming
days. Tens of millions of people fly from mid-December to shortly after New
Year's Day, and a travel record is expected to be set this year. The airline
issued a waiver allowing people flying through some airports to reschedule
their flights through Thursday.
*** American Airline
https://en.wikipedia.org/wiki/American_Airlines?useskin=vector
*** briefly
*** ground
*** vendor
*** ground stop
https://en.wikipedia.org/wiki/Ground_stop?useskin=vector
*** waiver
** Two
2. Believe it or not, there's a long tradition of Santa Claus
polls. The Times ran one in 1985 and, over the years, belief has
held quite steady, even if some parents now wonder if joy will
turn to trauma for their children when the truth comes out.
Americans don't just believe in Santa. They approve of his
performance. In a 2020 poll, 73 percent of respondents gave
him a positive rating.
*** believe it or not
*** Santa Claus
https://en.wikipedia.org/wiki/Santa_Claus?useskin=vector
*** trauma
*** come out
** Three
3. President-elect Trump has big plans to make America
greater — in terms of square mileage. He has floated
acquiring Greenland, reclaiming the Panama Canal,
annexing Canada, and potentially invading Mexico - to the
intense consternation of their leaders.
*** in terms of
*** float
*** reclaim
*** Panama Canal
https://en.wikipedia.org/wiki/Panama_Canal?useskin=vector
*** annex
*** consternation

* [[https://www.youtube.com/watch?v=SDEGEVFrvOM][(18) 读懂英语新闻（第192期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:

** One
1, "Physical and technical external interference" caused the plane crash
that killed 38 people flying to southern Russia, Azerbaijan Airlines said.
That's the closest officials have come to confirming mounting suspicions
that a Russian air-defense system downed the jet. Russia's aviation
authority said that the plane had tried to land in Grozny in Russia's
Chechnya region amid difficult conditions during a Ukrainian drone
strike. Missiles are now the biggest killer of airline passengers, aviation
safety data show.
*** Azerbaijan Airline
https://en.wikipedia.org/wiki/Azerbaijan_Airlines?useskin=vector
*** mounting
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:00] \\
  https://en.wiktionary.org/wiki/mounting
:END:

*** drone
** Two
2. Musk vowed last night to "go to war" to defend the H-1B visa program for
foreign tech workers, branding some Republican opponents as "hateful,
unrepentant racists." The MAGA-DOGE civil war that erupted over the last 48
hours has hit a tipping point, with President-elect Trump's new techno-libertarian
coalition of billionaires taking full aim at his base. Steve Bannon, one of the
longest-tenured voices in Trump's orbit, had multiple guests on his show this week
to talk about his hardline anti-H-1B views. Bannon tells Axios he helped kick off
the debate with a now-viral Gettr post calling out a lack of support for the Black
and Hispanic communities in Big Tech.
*** unrepentant
*** tipping point
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:00] \\
  https://en.wiktionary.org/wiki/tipping_point
:END:

*** take aim at
*** Steve Bannon
https://en.wikipedia.org/wiki/Steve_Bannon?useskin=vector
*** kick off
*** call out
:LOGBOOK:
- Note taken on [2024-12-31 Tue 10:04] \\
  https://en.wiktionary.org/wiki/call_out
:END:

** Three
3. Your so-called face age can tell doctors important
information about your health. Scans of face photos can
estimate people's "biological age." A study found that
an Al-trained model did a better job than doctors of
predicting how long cancer patients will live.
Researchers hope that one day the tool could be a
standard part of assessing health.
* [[https://www.youtube.com/watch?v=1law8VzRdNE][(19) 读懂英语新闻（第193期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Wall Street sees more gains ahead
The S&P 500 index was down slightly today, the final trading day of
2024, but it rose about 23.3 percent this year, roughly matching its gain
in 2023. It was the first time the benchmark index had risen more than
20 percent in consecutive years since 1998. Investors are heading into
2025 in an optimistic mood, believing that, with the economy on firm
footing and the White House in their corner, the stock market will
continue to climb.
*** see
*** gain
*** ahead
*** on firm footing
*** in their corner
:LOGBOOK:
- Note taken on [2025-01-02 Thu 09:50] \\
  来自拳击
:END:

** Two
2. Jimmy Carter, the 39th US president who brokered peace between
Israel and Egypt in the historic Camp David Accords, has died at 100.
His one-term presidency was marred by high inflation, an oil shortage
and the Iran hostage crisis, but some of his most notable achievements
came after he left the White Househis humanitarian work won him
the 2002 Nobel Peace Prize. The former president will get a state
funeral, and Joe Biden designated Jan. 9 as a national day of mourning.
*** Jimmy Carter
https://en.wikipedia.org/wiki/Jimmy_Carter?useskin=vector
*** broker
:LOGBOOK:
- Note taken on [2025-01-03 Fri 09:35] \\
  https://www.dicts.cn/dictword20181/html/f9f7e3234c205ab0e2874dd07c3bd46d.html?broker
:END:

*** Egypt
https://en.wikipedia.org/wiki/Egypt?useskin=vector
*** mar
:LOGBOOK:
- Note taken on [2025-01-03 Fri 09:36] \\
  https://www.dicts.cn/dictword20181/html/897567e13a4312342fb2dace4bec593f.html?mar
:END:

** Three
3. More people of all sizes and speeds are taking on
26.2-mile runs, thanks to super-cushioned sneakers,
running groups and the races' appeal to Gen Z athletes.
The pandemic helped fuel the running craze because
folks wanted exercise they could do alone and outdoors.
*** sneaker
https://en.wikipedia.org/wiki/Sneakers?useskin=vector
*** Gen Z
https://en.wikipedia.org/w/index.php?title=Generation_Z&useskin=vector
* [[https://www.youtube.com/watch?v=oz75nCQjgCA][(3) 读懂英语新闻（第194期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Alcoholic drinks like beer and wine should carry warnings of their links to
cancer, the US's top doctor said. Evidence of links between drinking and cancer
has been rising for decades, yet fewer than half of Americans recognize that it
raises their chances of developing several cancers, Surgeon General Vivek
Murthy said Friday. Alcohol causes about 100,000 cases of cancer and 20,000
related deaths each year in the US, far more than the 13,500 alcohol-associated
annual traffic fatalities. Adding a cancer warning would highlight severe health
concerns for products that more than 70% of US adults consume at least once a
week, with some $260 billion in 2022 nationwide sales. Shares of drinks makers
declined after the announcement.
*** Surgeon General
https://en.wikipedia.org/wiki/Surgeon_general?useskin=vector
** Three
3. The Green Beret who blew up a Tesla outside a Trump hotel in
Las Vegas left notes praising Donald Trump and Elon Musk. Friends
said he had struggled with P.T.S.D. and mental health issues.
*** Green Beret
https://en.wikipedia.org/w/index.php?title=United_States_Army_Special_Forces&useskin=vector
*** blew up
** Four
4. A New York judge upheld Donald Trump's criminal conviction in
the hush-money trial, but signaled that he was likely to spare Trump
jail time. The sentencing is set for Jan. 10.
*** spare
* [[https://www.youtube.com/watch?v=AEK8NHChUGs][(3) 读懂英语新闻（第195期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1 • Wildfires are spreading rapidly in Los Angeles, fanned by a
fierce windstorm. Gusts of up to 100 m.p.h., stronger than any the
region has seen in a decade, are forecast to blow through the night.
The flames are threatening Pacific Palisades, an affluent coastal
neighborhood that is home to about 24,000 people, roughly 20
miles west of downtown Los Angeles. Officials ordered residents
to evacuate immediately.
*** gust
*** evacuate
** Two
2 • Donald Trump said today at a news conference that he
would not rule out the use of military or economic coercion
to retake control of the Panama Canal and to force Denmark
to sell Greenland to the U.S. He also suggested that Canada
should become a U.S. state by getting "rid of that artificially
drawn line." The four nations have rejected his entreaties.
*** rule out
*** coercion
*** Denmark
*** entreaty
** Three
3 • Prime Minister Justin Trudeau is resigning after more
than nine years leading Canada, bowing to sagging
approval numbers and a rebellion within his own party.
Currently the longest-serving leader of any Group of Seven
country, the 53-year-old said Monday he'll step down as
head of the governing Liberal Party within months. He will
remain as prime minister until a new leader is selected.
*** bow
*** sag
*** rebellion
*** Group of Seven
*** step down
* [[https://www.youtube.com/watch?v=x8jeSzbSsqQ][(19) 读懂英语新闻（第204期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Get ready for Super Bowl Sunday
We're just two days away from America's biggest annual sporting event, the
Super Bowl. Kansas City and Philadelphia will meet at New Orleans's famous
Superdome, where Kansas City is narrowly favored to win its third consecutive
title. Kendrick Lamar will headline the halftime show, President Trump is
expected to show up and Taylor Swift will almost certainly be there. Most of us
will watch from home - a ticket costs more than most mortgage payments —
where treats like chicken wings and artichoke dip will be the real stars.
*** headline
*** treat
** Two
2. A federal judge temporarily blocked Elon Musk and some
of his team at the Department of Government Efficiency from
accessing sensitive Treasury payment systems. Last week Mr
Musk claimed doge was cancelling "illegal" payments,
sparking concerns that he had gained access to systems
handling trillions in Social Security and Medicare funds.
*** spark
** Three
3. How to sanitize your kitchen sink
After the effort of cooking a meal and clearing a sink full of dishes, cleaning
the sink itself may be the last thing you want to do. Unfortunately, it's
important: It kills pathogens from produce and raw meat, and it helps keep the
kitchen from getting smelly. Luckily, cleaning your sink can be an easy, two-
step process. Scrub off grime with a bit of dish soap on a brush or sponge and
then rinse the sink down. Next, sanitize it with a spray containing bleach,
making sure to cover the faucets and handles. Let the spray sit for the
recommended time, rinse with water, and voilà.
*** sanitize
*** sink
*** produce
*** scrub off
*** grime
* [[https://www.youtube.com/watch?v=LBUKbSskiSU][(4) 读懂英语新闻（第205期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. Trump plans to put the brakes on a law that forbids U.S. A blit
companies from bribing foreign officials to win business. The
measure disadvantages U.S. firms because they can't do what
overseas rivals do, and excessive enforcement crimps the president's
authority to conduct foreign affairs, the White House said. From big
bucks to one cent: Trump said he instructed the Treasury to stop
producing pennies because minting them is a waste of money. Others
say abolishing the penny would impact traders and consumers.
*** brake
*** buck
*** Treasury
https://en.wikipedia.org/wiki/Treasury?useskin=vector
*** mint
** Two
2. Trump announced a 25% tariff on all steel and
aluminum imports. Trump said the new tariffs would
apply to "everybody," including Canada and Mexico,
and take effect immediately. He also plans to introduce
reciprocal tariffs to match duties imposed by other
nations on U.S. goods.
*** reciprocal
** Three
3. Musk led a bid to buy OpenAI
A group of investors led by Elon Musk has made a $97.4 billion bid to buy the
nonprofit that controls OpenAl, the artificial intelligence company that created
ChatGPT. OpenAI declined to comment, but Sam Altman, the company's
chief executive, posted a response on social media: "No thank you but we will
buy twitter for $9.74 billion if you want." Musk, who has had a yearslong
rivalry with Altman, replied to the post: "Swindler," he said.
*** bid
* [[https://www.youtube.com/watch?v=vlYkm1B2rO0][(4) 读懂英语新闻（第206期）｜听新闻学英语｜词汇量暴涨｜英语读报｜美国新闻解读｜英语听力｜英文写作提升｜英语阅读｜时事英文｜单词轻松记｜精读英语新闻｜如何读懂英文新闻｜趣味学英语 ｜真人美音朗读 - YouTube]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. A man in Chile was briefly "swallowed' by a whale
Adrián Simancas was rafting with his
father in the waters of Chilean Patagonia
when a humpback whale suddenly lunged
at him, mouth open, from the waves
below. In an interview, Simancas said he
quickly realized he was trapped in the
whale's mouth: "Something dark blue or
white enveloped me, and a slimy texture
brushed my face." He emerged unharmed.
and his father caught it all on video.
*** Chile
https://en.wikipedia.org/wiki/Chile?useskin=vector
*** brief
https://www.dicts.cn/dictword20181/html/3f1c95fe12f6ed69d08688ef418c34bd.html?brief
*** raft
https://www.dicts.cn/dictword20181/html/220952e78c7fa4650f13a52dc7434e53.html?raft
*** humpback whale
https://en.wikipedia.org/wiki/Humpback_whale?useskin=vector
*** lunge
https://www.dicts.cn/dictword20181/html/c6ae78b7872e4f24c8f3f79a6fca8040.html?lunge
*** envelope
https://www.dicts.cn/dictword20181/html/cbac5e558b06a004b7899f7f4d778fef.html?envelope
*** slimy
https://www.dicts.cn/dictword20181/html/cfc208a5e81e8912c7f1dbc44a67506f.html?slimy
*** texture
https://www.dicts.cn/dictword20181/html/67b3671cf8ebdb8fc49d5a63e844d3bf.html?texture
** Two
2. Every year, Americans import hundreds of millions of rioweis in
the weeks leading up to Valentine's Day. Most of them, of course,
are roses — the classic symbol of love. But the tulip is becoming an
increasingly popular alternative. They are usually less expensive and
more environmentally friendly. And florists we spoke to said they
actually preferred the aesthetic of tulips, which, unlike roses,
continue to change and grow after they're cut.
*** lead up to
*** Valentine's Day
https://en.wikipedia.org/wiki/Valentine%27s_Day?useskin=vector
*** tulip
https://www.dicts.cn/dictword20181/html/3d601b6c3338f8d3f0f8b3729589ea8f.html?tulip
*** florist
https://www.dicts.cn/dictword20181/html/1cb6b06e3a3938fda0b38b46d7d8ba33.html?florist
*** aesthetic
https://www.dicts.cn/dictword20181/html/6aa905ab743076bfe978860df4d13df8.html?aesthetic
** Three
3. Good news, Gen Z! Apple and Google plan to restore
TikTok to their app stores following a letter from the
Department of Justice saying a ban wouldn't be immediately
enforced. The two companies had removed TikTok in the US
last month to comply with a law passed in 2024, before
Trump delayed it taking effect.
*** Department of Justice
https://en.wikipedia.org/w/index.php?title=Ministry_of_justice&useskin=vector
https://en.wikipedia.org/wiki/United_States_Department_of_Justice?useskin=vector
* [[https://www.bilibili.com/video/BV14XAre8EBq/][读懂英语新闻（第207期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. A Delta plane from Minneapolis crashed and flipped on its
back while landing in Toronto yesterday - injuring 18 but not
killing anybody. Officials said all 80 on board were evacuated
from the aircraft, which flipped amid windy weather after a
weekend snowstorm hit the area. One of the plane's wings was
torn off during the incident, which left three people — including
a child — critically injured.
*** Minneapolis
https://en.wikipedia.org/wiki/Minneapolis?useskin=vector
*** Tornonto
https://en.wikipedia.org/w/index.php?title=Toronto&useskin=vector
*** evacuate
https://www.dicts.cn/dictword20181/html/46a6ad040c1d60d7d8e92ce24f01b059.html?evacuate
*** tear off
https://www.dicts.cn/dictword20181/html/8d97007ab591fb684dc7248e507eec62.html?tear%20off
*** critically
https://www.dicts.cn/dictword20181/html/82d6e5335735a5fa7e2c7c31c9e811b6.html?critically
** Two
2. The worst flu season in 15 years has left hundreds of thousands
of Americans hospitalized while straining physicians' offices and
emergency departments. The virus is causing more severe
complications and hitting young children especially hard. This flu
season is classified as a "high-severity" season, with estimates of
at least 29 million cases - the most since the 2009-2010 flu
season, according to CDC data. There have been at least 370,000
hospitalizations and 16,000 deaths from flu as of Feb. 8.
*** strain
https://www.dicts.cn/dictword20181/html/0510eab5dad48207914fa152b60043a9.html?strain
*** complication
https://www.dicts.cn/dictword20181/html/54fef76b059890a1b874e8ce16ade4d3.html?complication
*** CDC
https://en.wikipedia.org/wiki/Centers_for_Disease_Control_and_Prevention?useskin=vector
*** as of
** Three
3. The U.S. and Russia began talks to try to end the war in Ukraine.
At meetings in Saudi Arabia, Washington will push for a quick
cease-fire, and Moscow is expected to call for large concessions.
Ukraine wants to be a party to the talks and has said it's not
obliged to agree to a peace deal negotiated in its absence.
*** call for
https://www.dicts.cn/dictword20181/html/4732c04a96cae8551afec1c841ce6a45.html?call%20for
*** concession
https://www.dicts.cn/dictword20181/html/72c7b3f70891bb51525832609e9f85e6.html?concession
* [[https://www.bilibili.com/video/BV1QdASebEza/][读懂英语新闻（第208期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Archaeologists found a pharaoh's tomb
Egypt's ministry of antiquities announced this week that
researchers had discovered what they described as the "the last
missing royal tomb of the 18th Dynasty." It belonged to Thutmose
II, who is believed to have reigned around 1480 B.C. The Egyptian
officials described the finding as the first excavation of a pharaoh's
tomb since Tutankhamen's burial chamber was unearthed in 1922.
*** archaeologist
*** tomb
*** Egypt
https://en.wikipedia.org/wiki/Egypt?useskin=vector
*** antiquity
https://www.dicts.cn/dictword20181/html/3bfa37a2d6854c03774cd89c74c76b6c.html?antiquity
*** Thutmose II
https://en.wikipedia.org/wiki/Thutmose_II?useskin=vector
*** reign
*** excavation
https://www.dicts.cn/dictword20181/html/44f9545cb2ae962412c865b6bc0bdb9b.html?excavation
*** unearth
https://www.dicts.cn/dictword20181/html/99640a1f16a29e60383d1848fa6ae0d5.html?unearth
** Two
2. The Broccoli family, who've long controlled the
007 franchise, agreed to hand over creative control to a
new joint venture with Amazon MGM Studios. Amazon
will now decide who will play Bond, who will write
the next script and when the film goes into production
—three critical components held up by a yearslong
stalemate.
*** franchise
https://www.dicts.cn/dictword20181/html/19fc5834efb1cbdbfb9dbae0431760c1.html?franchise
*** hand over
*** hold up
*** stalemate
https://www.dicts.cn/dictword20181/html/21b9400777ae09f28cadc5a3cb361abf.html?stalemate
** Three
3. Luigi Mangione, the 26-year-old accused of killing UnitedHealthcare
CEO Brian Thompson, had his first court appearance on Friday since he
was arraigned in December on charges which include murder as an act of
terrorism. Mangione appeared in Manhattan Criminal Court handcuffed
and wearing a bulletproof vest. His lawyer, Karen Friedman Agnifilo,
protested the unfair treatment of her client, who is battling three sets of
criminal charges. Friday morning shares of UnitedHealth Group fell after
reports that the Department of Justice has started investigating the
company's Medicare billing practices.
*** arraign
https://www.dicts.cn/dictword20181/html/269f05d39afb9ae54fc2b6339d819e2e.html?arraign
*** handcuff
https://www.dicts.cn/dictword20181/html/48e4adea7bb174cf290e397efd95ab15.html?handcuff
*** bulletproof
https://www.dicts.cn/dictword20181/html/906e9536aedfd51e936f35d40aa275f5.html?bulletproof
* [[https://www.bilibili.com/video/BV1YwP7egEXi/][读懂英语新闻（第209期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1, Ukraine agreed to turn over mineral revenue to the U.S. billb
The agreement came under heavy pressure from the Trump
administration. It's unclear what Ukraine will gain from the deal,
the final details of which are not yet public. President Trump had
suggested that the U.S. need not give up anything in exchange for
the mineral revenue. He described it as "payback" for past U.S. aid
to Ukraine during its war against Russia.
*** turn over
https://www.dicts.cn/dictword20181/html/24625630fe25b0342092283690500822.html?turn%20over
*** in exchange for
** Two
2. Trump backed adviser Elon Musk's Saturday email that demanded
millions of federal workers justify what they did last week. Musk had
said that nonresponses would be considered resignations. The email gave
workers until 11:59 p.m. today to respond with a list of their five
accomplishments. Musk is bringing his 2022 Twitter-takeover playbook
to the Department of Government Efficiency, though critics say it doesn't
translate to government. Trump-appointed top officials at several federal
agencies told employees to ignore Elon Musk's demand.
** Three
3. Warren Buffett is still sitting on a huge pile of cash.
His Berkshire Hathaway hoard grew to a record $334.2
billion in the fourth quarter as operating earnings surged
71%. The billionaire's firm has paid Uncle Sam more
than $101 billion in taxes since he took the helm 60 years
ago, more than any other company in history.
*** pile
https://www.dicts.cn/dictword20181/html/0dd4ede3f546816241c651dc44507052.html?pile
*** hoard
https://www.dicts.cn/dictword20181/html/1787e02d20db54a97cd10d18259be049.html?hoard
*** take the helm
* [[https://www.bilibili.com/video/BV1kRP1eqEod/][读懂英语新闻（第203期）｜听新闻学英语｜词汇量暴涨｜英语听力｜英文写作提升｜英语阅读｜单词轻松记_哔哩哔哩_bilibili]]
:PROPERTIES:
:CAPTURED_ON: [2024-01-05 Fri 14:22]
:END:
** One
1. The leaders of Canada and Mexico made last-minute deals with
President Trump to avoid a trade war. Trump postponed tariffs of up
to 25 percent after the leaders said they would do more to block
drugs and migrants. China hit back with new tariffs on US products
and started an antitrust probe into Google in response to Donald
Trump's 10% levies. Beijing also added Calvin Klein owner PVH
and gene sequencing company Illumina to a blacklist of entities.
*** hit back
https://www.collinsdictionary.com/dictionary/english/hit-back
*** probe
https://www.dicts.cn/dictword20181/html/4f595a9232346e4ca5855f3e2b777566.html?probe
** Two
2. Video game executives did not expect The Sims to be a
hit when it was released on this day in 2000. It was a
virtual dollhouse where players could raise families, build
houses and cause disasters. But unlike popular games at
the time, there was no clear objective. Now a quarter
century later, more than 500 million people have played
games in the Sims franchise.
*** franchise
** Three
3. A shooting today at an adult education campus in
central Sweden left at least 10 people dead. The prime
minister called it the worst mass shooting in the country's
history. The suspect was among the dead, officials said.
But the authorities released few other details, including
the person's identity and a possible motive.
*** campus
https://www.dicts.cn/dictword20181/html/e06ab55a7671736469f7e815d5bfa2a8.html?campus
*** suspect
https://www.dicts.cn/dictword20181/html/9abeeab96ad5d9e275c206d799ebf554.html?suspect
