#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil

Record my english study process.

* some
https://www.collinsdictionary.com/dictionary/english/some
又表示大，又表示小
** 一些

*** He went to fetch some books.

** 大量

*** He remained silent for some time.

** 有几分

*** Is't there some chance that William might lead a normal life?

** (整体的)部分

*** Some of us like football, others like basketball.

** 某个

*** If you are worried about some aspect of you child's health, call us!

** 大约(用在数字前)

*** I have kept birds for some 30 years.

** 有点

*** I party some.

** 赞同/不赞同

*** That was some party last night!

* fine
https://www.collinsdictionary.com/dictionary/english/fine
不仅代表好，可能还是罚款

** 好的

*** This is a fine book.

** 健康的

*** Lina is fine and sends you her love and best wishes.

** 满意的

*** Everything was going to be just fine.

** 可以

*** This fine with me.

** 纤细的

*** Very fine hairs.

** 精美的

*** We waited in our fine clothes.

** 精确的

*** The market like the broad outline but is reserving judgment on the fine detail.

** 高尚的

*** You feather is a fine man, a real gentlemen.

** 天气晴朗的

*** If it's fine tomorrow we will go out.

** 罚款

*** She was fined for speeding.
* bold
:PROPERTIES:
:ID:       1E459DE3-54E0-4A3D-B1FB-8C7471524E5D
:END:
https://www.collinsdictionary.com/dictionary/english/bold
bold不只表示粗体，还可以很勇敢

** 勇敢的，大胆的
*** Poland was already making bold economic reforms.
** 放肆的
*** She marched into his office as bold as brass.
** 明显的
*** Bold colours
** 粗体
*** All the headings are in bold type.
* detail
:PROPERTIES:
:ID:       0DDC7D03-D4BC-460B-98D7-2DC668084CC3
:END:
https://www.collinsdictionary.com/dictionary/english/detail
detail的细节还挺多

** 细节
I recall every detail of the party.
** 信息
Full details will be announced soon.
** 枝节
Only minor details now remain to be settled.
** 细微之处
We like his attention to detail and enthusiasm.
** 详述
The report details the progress we have made over the last years.
** 指派
Four soldiers were detailed to guard duty.
* firm
:PROPERTIES:
:ID:       A71B1211-501D-4AED-B537-D664A70ADAFC
:END:
https://www.collinsdictionary.com/dictionary/english/firm
商户是坚挺的
** 商户(小型的)
The firm's employees were expecting large bonuses.
** 坚固的
Choose a soft, medium or firm mattress to suit their individual needs.
** 强有力的
The quick handshake was firm and cool.
** 坚决的
China express strong indignation and firm opposition.
** 确定的
It is my firm belife that an effective partnership approach between police and the public is absolutely necessary.
** 坚挺的
Cotton prices remain firm and demand is strong.
** 压
Firm more soil over the roots and water thoroughly.
* false
[[https://www.collinsdictionary.com/dictionary/english/false]]
假的就是假的
** 不正确的
You do not know whether what you're told is true or false.
** 人造的，假的
I don't want to give you any false hopes.
** 虚伪的
She bowed her head and smiled in false modesty.

She's so false.
* string
:PROPERTIES:
:ID:       75792300-A4B7-4075-801C-55FDE5F2F185
:END:
不只表示字符串，还可以是琴弦
** 细绳
He held out a small bag tied with string.
** 一串
She wore a string of pearls around her neck.
** 一系列
The incident was the latest in a string of attacks.
** 弦
He went off to change a guitar string.
** 计算机中的字符串
** 系
He had strug a banner across the wall.