#+OPTIONS: toc:1 ^:nil ~:nil num:nil reveal_title_slide:nil timestamp:nil

Record my english study process.

* some
https://www.collinsdictionary.com/dictionary/english/some
又表示大，又表示小
** 一些

*** He went to fetch some books.

** 大量

*** He remained silent for some time.

** 有几分

*** Is't there some chance that William might lead a normal life?

** (整体的)部分

*** Some of us like football, others like basketball.

** 某个

*** If you are worried about some aspect of you child's health, call us!

** 大约(用在数字前)

*** I have kept birds for some 30 years.

** 有点

*** I party some.

** 赞同/不赞同

*** That was some party last night!

* fine
https://www.collinsdictionary.com/dictionary/english/fine
不仅代表好，可能还是罚款

** 好的

*** This is a fine book.

** 健康的

*** Lina is fine and sends you her love and best wishes.

** 满意的

*** Everything was going to be just fine.

** 可以

*** This fine with me.

** 纤细的

*** Very fine hairs.

** 精美的

*** We waited in our fine clothes.

** 精确的

*** The market like the broad outline but is reserving judgment on the fine detail.

** 高尚的

*** You feather is a fine man, a real gentlemen.

** 天气晴朗的

*** If it's fine tomorrow we will go out.

** 罚款

*** She was fined for speeding.
* bold
:PROPERTIES:
:ID:       1E459DE3-54E0-4A3D-B1FB-8C7471524E5D
:END:
https://www.collinsdictionary.com/dictionary/english/bold
bold不只表示粗体，还可以很勇敢

** 勇敢的，大胆的
*** Poland was already making bold economic reforms.
** 放肆的
*** She marched into his office as bold as brass.
** 明显的
*** Bold colours
** 粗体
*** All the headings are in bold type.
* detail
:PROPERTIES:
:ID:       0DDC7D03-D4BC-460B-98D7-2DC668084CC3
:END:
https://www.collinsdictionary.com/dictionary/english/detail
detail的细节还挺多

** 细节
I recall every detail of the party.
** 信息
Full details will be announced soon.
** 枝节
Only minor details now remain to be settled.
** 细微之处
We like his attention to detail and enthusiasm.
** 详述
The report details the progress we have made over the last years.
** 指派
Four soldiers were detailed to guard duty.
* firm
:PROPERTIES:
:ID:       A71B1211-501D-4AED-B537-D664A70ADAFC
:END:
https://www.collinsdictionary.com/dictionary/english/firm
商户是坚挺的
** 商户(小型的)
The firm's employees were expecting large bonuses.
** 坚固的
Choose a soft, medium or firm mattress to suit their individual needs.
** 强有力的
The quick handshake was firm and cool.
** 坚决的
China express strong indignation and firm opposition.
** 确定的
It is my firm belife that an effective partnership approach between police and the public is absolutely necessary.
** 坚挺的
Cotton prices remain firm and demand is strong.
** 压
Firm more soil over the roots and water thoroughly.
* false
[[https://www.collinsdictionary.com/dictionary/english/false]]
假的就是假的
** 不正确的
You do not know whether what you're told is true or false.
** 人造的，假的
I don't want to give you any false hopes.
** 虚伪的
She bowed her head and smiled in false modesty.

She's so false.
* string
:PROPERTIES:
:ID:       75792300-A4B7-4075-801C-55FDE5F2F185
:END:
不只表示字符串，还可以是琴弦
** 细绳
He held out a small bag tied with string.
** 一串
She wore a string of pearls around her neck.
** 一系列
The incident was the latest in a string of attacks.
** 弦
He went off to change a guitar string.
** 计算机中的字符串
** 系
He had strug a banner across the wall.
* approach
:PROPERTIES:
:ID:       022796B3-DE24-4A1B-9C49-43DC818B76C2
:END:
接近的方式
** 接近
When i approached, they grew silent.
** 处理
Employees are insterested in how you approach problems.
** 方法
We will be exploring different approaches to gathering information.
* take
:PROPERTIES:
:ID:       5B88B8C2-8B33-4C93-8165-92D8F4E61B5F
:END:
不只有拿意思
** 移动
John took us to the airport.
** 动作
Would like to take a look?
** 拿走
Take you feet off the seats.
** 花费
It took a few minutes for his eyes to adjust to the dark.
** 接受
Will you take the job?
** 拿着
Let me take you coat.
** 收集
The police took a statement from both witness.
** 感觉
You will take pride in you work.
** 服用
Take two tablets before bedroom.
** 教
Who take you for english?
** 写
Let me take you email address.
** 升级
If you want take it further, you should consult an attorney.
* over
在结束之上
** 在xxx之上
A bridge over the river Danube.
** 挂在xxx上面
A grey mackintosh was folded over her arm.
** 可以看见
His rooms looked out over a narrow lane behind the collge.
** 穿过
I stepped over a broken piece of wood.
** 在xxx的另一边
John, who lived in the house over the road.
** 去，到
I thought you might have invited her over.
** 倒下
He was knocked over by a bus and broke his leg.
** 超过
The japanese were producing over 100 million tons of steel.
** 结束
The time for empty talk is  over.
* double
成双成对
** 语义
*** 成双的
A pair of double doors into the room from the new entrance hall.
*** 双重的
The government committed a double blunder.
*** 两倍的
These designers was discussing how to double the scale of the park.
*** 双人间
Bed and breakfast for $180 for two people in a double room.
*** 加倍
The number of managers must double to 100 whithin 3 years.
*** 相似的
You mother sees you as her double.
*** 兼职
Jack doubles as director and producer.
** 短语
*** double shift
双班倒
* right
正确的权力
** 语义
*** 正确的
That absolutely right.
*** 准确的
They have conputererized systems to ensure delivery of the right pizza to the right place.
*** 正派的
Through his father, he had met all the right people.
*** 最好的
He made the right choice in leaving New York.
*** 正常的
He went info hospital and came out after a week. But he still wasn't right.
*** 扭转
They recognise the urgency of righting the economy.
*** 纠正
We'are made progress in righting the worngs of the past.
*** 摆正
He righted the car and continued the race.
*** 右边
He had a knife in his right hand.
*** 权利
The new charter establishes the rights and duties of citizens.
** 短语
*** are going right
进展顺利

I can't think of anything in my life that't going right.
*** in the right
有理的

He was't entirely in the right.
*** Mr Right
真命王子

She confesses to having trouble finding Mr Right.